### ISSUE TITLE
Support CloudWatch as a metric provider

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#1014]
# Summary

It would be useful to gather metrics from AWS CloudWatch to drive analysis

# Use Cases

For users who are using integrations such as ALB ingress, error rate and latency would be metrics that could be used to drive rollout promotion.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by ryota-sakamoto** [comment]
Hi @jessesuen 
I'll do this issue.

**Comment by jessesuen** [comment]
@ryota-sakamoto that would be great!
