### ISSUE TITLE
Provide an official container image with the kubectl rollouts plugin

### ISSUE THREAD

**Issue by kostis-codefresh** [argoproj/argo-rollouts#1033]
I couldn't find an official docker image with kubectl rollouts plugin.

Having a container image with the plugin would be great for container based CI/CD systems such as Google cloud builder, Codefresh, CircleCI, drone.io etc.

Even though I could easily create a docker image myself with the latest plugin, it would be great if Argo would do that automatically in your CI/CD system so that each new version of the plugin will also have its respective container image.

Examples of existing official images from other command line tools which make their usage in CI/CD very easy.

https://hub.docker.com/r/hashicorp/terraform/
https://hub.docker.com/r/istio/istioctl
https://hub.docker.com/r/google/cloud-sdk/
https://hub.docker.com/r/amazon/aws-cli
https://hub.docker.com/r/pulumi/pulumi

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
There's an upcoming feature where the [plugin will serve a UI to visualize rollouts](https://github.com/argoproj/argo-rollouts/pull/1015 ). So it will make sense to make that available in a container image for those who want to expose this somehow.

**Comment by jessesuen** [comment]
This is now automatically built and published to https://quay.io/repository/argoproj/kubectl-argo-rollouts
