### ISSUE TITLE
Prometheus support should be explicit in the documentation

### ISSUE THREAD

**Issue by kostis-codefresh** [argoproj/argo-rollouts#1057]
# Summary

Right now, Prometheus is only used for some examples in the [overview](https://argoproj.github.io/argo-rollouts/features/analysis/) page of the analysis. 

Ideally Prometheus should have its own page in that section of the docs like all other metric providers (along with Datadog, NewRelic etc).

# Use Cases

A person who is quickly checking the documentation site for Prometheus support might simply expand the analysis tree, see no entry for Prometheus and think that Prometheus is not supported at all.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
You're right. This is was an oversight.
