### ISSUE TITLE
Google Cloud Load Balancer Ingress Controller

### ISSUE THREAD

**Issue by Maxweston** [argoproj/argo-rollouts#1079]
# Summary

Much like AWS Load Balancers are already supported, could support for Google Load Balancers be added?

# Use Cases

For users of Google Cloud Platform.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
If there is a Google Cloud Ingress or CRD object that can be managed to allow traffic splitting, then absolutely yes this should be possible.

**Comment by gpkc** [comment]
Have there been any developments on this?

**Comment by kostis-codefresh** [comment]
Support for Google cloud is now available via the new Gateway api https://cloud.google.com/kubernetes-engine/docs/concepts/gateway-api and the Gateway plugin 
https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi

I will soon submit a PR for documentation

**Comment by kostis-codefresh** [comment]
@Maxweston , @gpkc please check https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/tree/main/examples/google-cloud
