### ISSUE TITLE
Upgrade grpc/protobuf dependencies

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-rollouts#1091]
# Summary

Argo Rollouts API server uses old grcp libraries that have to be upgraded:

* `github.com/golang/protobuf` -  The `github.com/golang/protobuf` is v1 and it is in maintenance mode. It has to be replaced with v2 `google.golang.org/protobuf` see https://blog.golang.org/protobuf-apiv2
* `github.com/grpc-ecosystem/grpc-gateway` - v1 is in maintenance mode and has to be upgraded to v2 (see https://grpc-ecosystem.github.io/grpc-gateway/docs/development/grpc-gateway_v2_migration_guide/)

**Comment by alexmt** [comment]
Attempted to upgrade and failed. Using this ticket to document what I've tried and which issues I've faced:

* `github.com/grpc-ecosystem/grpc-gateway` v2.3.0 no longer focused on using `protoc` and trying to replace it with `buf`. Migration to `buf` was not straightforward: could not find how to point `buf` to protos from `k8s/apimachinery`, could not find a way to use `buf` without changing our proto files.

* `github.com/grpc-ecosystem/grpc-gateway` v2 generates code that relies on `google.golang.org/protobuf` (go protobuf v2). So we have to upgrade to `google.golang.org/protobuf` first

* `google.golang.org/protobuf` does not work with `github.com/gogo/protobuf`. So we have to switch back to official go plugin `google.golang.org/protobuf/cmd/protoc-gen-go`. 

* `google.golang.org/protobuf/cmd/protoc-gen-go`  - has changed and now requires to have full package name in `go_package`  . Protos from https://github.com/kubernetes/apimachinery still don't have full package name. E.g. https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/generated.proto . That was a dead-end, could not find a way to workaround.

**Comment by jessesuen** [comment]
@alexmt I've managed to split out most toolchain binaries and remove them as a `go.mod` library dependency in PR https://github.com/argoproj/argo-rollouts/pull/1095. Do you think your findings still hold true?

**Comment by jessesuen** [comment]
> google.golang.org/protobuf/cmd/protoc-gen-go - has changed and now requires to have full package name in go_package . Protos from https://github.com/kubernetes/apimachinery still don't have full package name. E.g. https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/generated.proto . That was a dead-end, could not find a way to workaround.

I spent a few hours on this and hit the same dead end as you.

```
# protoc pkg/apiclient/rollout/rollout.proto
PATH=/Users/jsuen/go/src/github.com/argoproj/argo-rollouts/dist:$PATH protoc -I . -I ./vendor -I /Users/jsuen/go/src -I ./vendor/github.com/googleapis/googleapis --go_out=plugins=grpc:/Users/jsuen/go/src --grpc-gateway_out=logtostderr=true:/Users/jsuen/go/src --swagger_out=logtostderr=true,fqn_for_swagger_name=true:. pkg/apiclient/rollout/rollout.proto
protoc-gen-go: invalid Go import path "resource" for "k8s.io/apimachinery/pkg/api/resource/generated.proto"

The import path must contain at least one forward slash ('/') character.

See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

--go_out: protoc-gen-go: Plugin failed with status code 1.
make: *** [api-proto] Error 1
```

I agree we cannot get past this upstream k8s generated.proto have this problem and its not feasible to change upstream.

Looks like we are stuck with v1 protobuf and grpc-gateway until kubernetes moves up.

**Comment by blkperl** [comment]
There is an upstream issue that will hopefully unblock us https://github.com/kubernetes/kubernetes/issues/96564

**Comment by leoluz** [comment]
FYI, I'm giving it another try in https://github.com/argoproj/argo-cd/pull/8929

**Comment by leoluz** [comment]
grpc runtime library updated in https://github.com/argoproj/argo-cd/pull/8929
