### ISSUE TITLE
Doc.: bad formatting on https://argoproj.github.io/argo-rollouts/features/canary/

### ISSUE THREAD

**Issue by dsbos** [argoproj/argo-rollouts#1113]
## Summary 

The page currently at https://argoproj.github.io/argo-rollouts/features/canary/ says:

> To control canary weights during steps, use the setCanaryScale step and indicate which scale the the canary should use: * explicit replica count * explicit weight percentage of total spec.repicas * to match current canary setWeight

(Note the asterisks showing up in the rendered page. It looks like some MarkDown/etc. source code (documentation) wasn't indented correctly).

There's also a second section in that page that seems to have the same problem.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by dsbos** [comment]
Several other pages also have the same formatting problem.

**Comment by kostis-codefresh** [comment]
Hey @dsbos. What other pages have you found that have formatting issues? It would be helpful to have a full list of them if possible.

**Comment by dsbos** [comment]
Can't you search in the documentation source for whatever pattern resulted in rendering asterisks rather than list items (perhaps wrongly indented asterisks)?

Otherwise, do something like saving a local copy of the documentation using something like `wget`'s recursive retrieval and then searching (e.g., via `grep`) for literal asterisks in the local files.
