### ISSUE TITLE
workloadRef: when referenced Deployment goes missing, we delete pods

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#1123]
## Summary 

What happened/what you expected to happen?

Using the new workloadRef feature, a user deleted the referenced deployment. When this happened, he noticed that the rollout also deleted/scaled down the RelicaSet which was created from the Deployment definition.

Instead of scaling down the ReplicaSet, we should start emitting Warning events and put rollout in degraded state, and leave the ReplicaSet running, so that it does not cause any downtime.

## Diagnostics

What version of Argo Rollouts are you running? pre v1.0 release (as of today)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by huikang** [comment]
Hi, @jessesuen , I can look into this bug. Please assign it to me. Thanks.

**Comment by huikang** [comment]
> ## Summary
> 
> What happened/what you expected to happen?
> 
> Using the new workloadRef feature, a user deleted the referenced deployment. When this happened, he noticed that the rollout also deleted/scaled down the RelicaSet which was created from the Deployment definition.
> 

Hi, @jessesuen , I tested workloadRef and noted that when the reference depoyment is deleted, the RelicaSet of rollout is still running (which is different than what you described) with the controller emitting the following message

```
ERRO[2021-04-30T00:01:22-04:00] rollout syncHandler error: deployments.apps "default/rollout-demo-deploy" not found  namespace=default rollout=rollouts-demo-canary
E0430 00:01:22.320382    4388 controller.go:172] deployments.apps "default/rollout-demo-deploy" not found
ERRO[2021-04-30T00:01:22-04:00] rollout syncHandler error: deployments.apps "default/rollout-demo-deploy" not found  namespace=default rollout=rollouts-demo-canary
E0430 00:01:22.342081    4388 controller.go:172] deployments.apps "default/rollout-demo-deploy" not found
ERRO[2021-04-30T00:01:22-04:00] rollout syncHandler error: deployments.apps "default/rollout-demo-deploy" not found  namespace=default rollout=rollouts-demo-canary
E0430 00:01:22.387388    4388 controller.go:172] deployments.apps "default/rollout-demo-deploy" not found
```

Did I miss something in reproducing the behavior?

**Comment by jessesuen** [comment]
> @jessesuen , I don't think the controller will remove the replicasets if the referenced deployment is deleted because

Thank you for the investigation, verification, and fix. I heard this second hand and never verified this myself.

Closing as fixed in https://github.com/argoproj/argo-rollouts/pull/1136
