### ISSUE TITLE
Simplify plugin promote options (deprecate `--skip-current-step`)

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#1142]
# Summary

We currently have three options to "promote" a rollout in the plugin:

```
        # Promote a paused rollout
        kubectl argo rollouts promote guestbook

        # Fully promote a rollout to desired version, skipping analysis, pauses, and steps
        kubectl argo rollouts promote guestbook --full

        # Skip currently running canary step of a rollout
        kubectl argo rollouts promote guestbook --skip-current-step
```

The different options can be hard to explain/understand, and users may not know when to use which option. To simplify things, I think the behavior of `kubectl argo rollouts promote guestbook --skip-current-step` (which increments the step index) should be merged into the existing `kubectl argo rollouts promote` command so that there are only two options for promote:

* `kubectl argo rollouts promote` - Unpause or promote the rollout to the next step
* `kubectl argo rollouts promote --full` - Fully promote a rollout to desired version, skipping analysis, pauses, and steps 

With this change, users no longer have to think about when to run `kubectl argo rollouts promote` vs. `kubectl argo rollouts promote guestbook --skip-current-step` when they just want the rollout to move past the current step.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
Another motivation for this is that the UI does not show `kubectl argo rollouts promote guestbook --skip-current-step` as an option, so the UI would benefit from having only the two options: promote and promote-full

**Comment by harikrongali** [comment]
will pick it up, please assign

**Comment by jessesuen** [comment]
Resolved in https://github.com/argoproj/argo-rollouts/pull/1156
