### ISSUE TITLE
Dashboard not working

### ISSUE THREAD

**Issue by DanTulovsky** [argoproj/argo-rollouts#1144]
## Summary 

I have a single rollout defined. When I run:

```
% kubectl argo rollouts dashboard -n web
```

it starts up the dashboard on port 3100. I can then visit it

<img width="1064" alt="Screen Shot 2021-05-06 at 9 01 54 AM" src="https://user-images.githubusercontent.com/509887/117302516-b6580700-ae49-11eb-9e83-9c1f7353f390.png">

If I then click on the rollout itself, it goes to `http://localhost:3100/rollout/quote-server-rollout`, but all I see is a blank screen. This is on latest MacOS. I've tried Chrome, Safari and Firefox with the same results.

## Diagnostics

Version: v1.0.0-rc1+4848b64

It seems to error out with a javascript error:

```
TypeError: n.containers is undefined
    Rollout rollout.tsx:122
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    u watch.ts:177
    RxJS 4
    n watch.ts:65
    RxJS 18
react-dom.production.min.js:216:199
    React 5
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    u watch.ts:177
    RxJS 4
    n watch.ts:65
    RxJS 18
```

and

```
Uncaught TypeError: n.containers is undefined
    Rollout rollout.tsx:122
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    u watch.ts:177
    RxJS 4
    n watch.ts:65
    RxJS 18
rollout.tsx:122:32

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by rbreeze** [comment]
Could you provide the spec for the `quote-server-rollout` rollout please?

**Comment by DanTulovsky** [comment]
Do you need my Deployment as well, or do you think you've already fixed this?

**Comment by rbreeze** [comment]
#1146 should have fixed this. Thanks!
