### ISSUE TITLE
Rollout-controller does not expose its version

### ISSUE THREAD

**Issue by huikang** [argoproj/argo-rollouts#1145]
# Summary

The current `kubectl argo rollouts version` only shows the version of the rollouts client binary.
~~Ideally `kubectl argo rollouts version`  should also display the version of the rollout-controller running in the cluster.~~

Add a sub-command to `rollout-controller` to show its version.

# Use Cases

As a user, I'd like to know which version of argo-rollouts is installed in the cluster.

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by huikang** [comment]
@jessesuen , I can look into this issue. Please assign it to me. Thanks.

**Comment by jessesuen** [comment]
How do you think the plugin should determine the version of the controller? Do we introduce a /version endpoint that exposes it and it reaches the endpoint via port-forwarding?

**Comment by huikang** [comment]
Hi, @jessesuen , my initial thought was something like `kubectl version` which shows both the local binary version and the server's version. However, after second thought, it sounds like a overkill.

Adding a sub-command should be good enough.
