### ISSUE TITLE
kinds other than Deployment

### ISSUE THREAD

**Issue by ryandawsonuk** [argoproj/argo-rollouts#115]
The examples currently seem to assume that what you're looking rollout is a vanilla Deployment. Are there ways roll out a StatefulSet or Custom Resource (e.g. a Knative service)? Perhaps using [kustomize transforms](https://github.com/argoproj/argo-rollouts/blob/master/docs/kustomize.md)? Or are there plans to support this?

**Comment by jessesuen** [comment]
Thanks for your question. I gave an answer here:
https://github.com/argoproj/argo-rollouts/issues/132#issuecomment-518519954
