### ISSUE TITLE
Investigate ordering of service patching vs. replicaset creation

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#1151]
## Summary 

In our environment, it was observed that some pods of a Rollout's ReplicaSet never had readiness gate injected by the aws-loadbalancer-controller, but other Pods of the ReplicaSet were.

If we create a new replicaset before we patch the preview/canary service, its possible the pods of the replicaset will be created without a readiness gate because with AWS load balancer controller, it chooses to only inject readiness gates on pods that are targeted by a Service that is associated with a Load Balancer.

Need to investigate ordering on how we create RSs vs. patching services and see if we handle this correctly.

## Diagnostics

What version of Argo Rollouts are you running? v1.0.0-rc1

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
Looks like we reconcile the new replicaset before preview service. So we can try swapping the ordering.

```golang
	err = c.reconcileBlueGreenReplicaSets(activeSvc)
	if err != nil {
		return err
	}

	err = c.reconcilePreviewService(previewSvc)
	if err != nil {
		return err
	}
```

**Comment by jessesuen** [comment]
> Looks like we reconcile the new replicaset before preview service. So we can try swapping the ordering.

Actually, after investigating, `reconcileBlueGreenReplicaSets` is not where we create the new ReplicaSet, so this is not as simple as switching the ordering. We actually create the ReplicaSets much earlier:

```golang
func (c *rolloutContext) rolloutBlueGreen() error {
	previewSvc, activeSvc, err := c.getPreviewAndActiveServices()
	if err != nil {
		return err
	}
	c.newRS, err = c.getAllReplicaSetsAndSyncRevision(true)
	if err != nil {
		return err
	}
```

`c.newRS` is assigned at that point, which is then needed by:

```
func (c *rolloutContext) reconcilePreviewService(previewSvc *corev1.Service) error {
	if previewSvc == nil {
		return nil
	}
	newPodHash := c.newRS.Labels[v1alpha1.DefaultRolloutUniqueLabelKey]
	err := c.switchServiceSelector(previewSvc, newPodHash, c.rollout)
	if err != nil {
		return err
	}

	return nil
}
```

So there is a hard ordering here in the code. I'm not sure this is worth fixing as it introduces unnecessary risk for imperceivable gain.

**Comment by jessesuen** [comment]
Actually we can achieve this with the following order:

1. create preview replicaset with size 0
2. retarget preview service to replicaset hash
3. scale up the preview replicaset

**Comment by llimon** [comment]
@jessesuen  Under ALB Ingress controller 2.2.1, when you add a readinessGate condition
```
      readinessGates:
        - conditionType: target-health.alb.ingress.k8s.aws/load-balancer-any-tg-ready
```
Causes rollout initial rollout pods to never become active because there is no target assigned to them, on the older version of ALB Ingress controller the condition is ignored, and pods become active without a readinessGate assigned.

Pods failing to become active have this error:
```
    - lastProbeTime: null
      lastTransitionTime: '2021-07-22T05:10:16Z'
      message: >-
        corresponding condition of pod readiness gate
        "target-health.alb.ingress.k8s.aws/load-balancer-any-tg-ready" does not
        exist.
      reason: ReadinessGatesNotReady
      status: 'False'
      type: Ready
```

**Comment by jessesuen** [comment]
Relevant https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1782
