### ISSUE TITLE
kubectl-argo-rollouts-linux-amd64 --timeout should take a string

### ISSUE THREAD

**Issue by DanTulovsky** [argoproj/argo-rollouts#1173]
# Summary

kubectl-argo-rollouts-linux-amd64 --timeout should take a string, like the other commands do. Currently it takes an integer seconds.

# Use Cases

This would make behavior the same as `kubectl --timeout` and match other time based flags in this package.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
> This would make behavior the same as kubectl --timeout and match other time based flags in this package.

Agree. Since `kubectl argo rollouts status` is new in v1.0, we can change the behavior since there is no backwards compatibility to worry about.

**Comment by jessesuen** [comment]
@perenesenko would you like to take this one?

**Comment by perenesenko** [comment]
Yes, I'll take this one

**Comment by jessesuen** [comment]
Fixed in https://github.com/argoproj/argo-rollouts/pull/1194
