### ISSUE TITLE
B/G Rollout status doesn't mark the rollout as paused during prePromotion analysis run 

### ISSUE THREAD

**Issue by rmorampudi** [argoproj/argo-rollouts#1174]
## Summary 

What happened/what you expected to happen?
During B/G pre promotion analysis run, the rollout doesn't have a pause condition in the status, it is expected to have pause conditions with reason 'BlueGreenPause'
## Diagnostics

What version of Argo Rollouts are you running?
This is seen when working with the master branch but with 0.10.2 it was working as expected 
```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>
Rollout status from kubectl describe ro <rollout_name>
Status from master branch for B/G: https://gist.github.com/rmorampudi/adb62d01363d57ff54c979512a3f325e
Status from 0.10.2 version for B/G: https://gist.github.com/rmorampudi/5286c3fac563636e651a76aeaff76f33#file-rollout_status_0-10-2-L28-L30
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
I think this is by design. If prePromotionAnalysis is running, we consider this as Progressing instead of Paused because we haven't reached the pause stage yet. Pause indicates that it succeeded prepromotion analysis

**Comment by rmorampudi** [comment]
@jessesuen, got it, thanks for the response.
