### ISSUE TITLE
workloadRef rollouts should record `status.workloadObservedGeneration`

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#1189]
# Summary

Rollouts that use the new workloadRef feature, currently do not benefit from client-side checks where `status.observedGeneration == metadata.generation` because changes to the referenced workload object, do not increment the rollout's `metadata.generation`. This can cause a rollout's phase (Healthy/Degraded/Progressing/Paused) to be interpreted incorrectly because a client has no way to understand if both the rollout's & workload's spec has been observed by the rollout controller.

To support more reliable detection of changes to workloadRef resources, to help detect when the workload's spec has been observed by the rollout controller, I think we can  make the following improvements:

1. Currently the informer which is watching workload resources simply enqueues the relevant rollout for reconciliation. Instead of simply enqueuing the rollout to the workqueue, it should instead *patch* the rollout with the `metadata.generation` of the workload under a new rollout annotation. e.g.:

```yaml
annotations:
  rollout.argoproj.io/workload-generation: "5"
```

2. Then when reconciling a rollout using workloadRefs, the rollout controller would then record that generation under the rollout status:

```yaml
status:
  workloadObservedGeneration: 5
```

3. Clients such as the plugin and Argo CD should then be improved to check both:
* `metadata.generation == status.observedGeneration`
* `metadata.annotations["rollout.argoproj.io/workload-generation"] == `status.workloadObservedGeneration`

in order to decide if both the rollout spec and the workload spec has been observed by the controller

It should be noted that while this technique will **_increase_** the probability that workload spec changes are observed by the rollout controller, it does not **_guarantee_** it. This is because it still relies on a running controller to patch the rollout upon workload spec changes. That said, the addition of a controller dedicated to patching the rollout upon spec changes, should help make it generally more reliable because it would not be affected by say saturation of the rollout workers.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by huikang** [comment]
Hi, @jessesuen  , I can look into this issue. Please assign it to me. Thanks.

**Comment by jessesuen** [comment]
Sure!

**Comment by huikang** [comment]
Hi, @jessesuen , following your suggestion, I updated the following method to add the `rollout.argoproj.io/workload-generation` to the rollout object on any update to the referenced workload. However, when I test the code, it always give me the error 

`updating rollout revision Rollout.argoproj.io "rollouts-demo-canary" is invalid: spec.template.spec.containers: Required value`

Could you provide any help? Thanks.

```go
// requeueReferencedRollouts re-queues all rollouts referenced by given object
func (r *informerBasedTemplateResolver) requeueReferencedRollouts(obj interface{}, gvk schema.GroupVersionKind) {
	roMeta, err := meta.Accessor(obj)
	if err != nil {
		return
	}
	rollouts, err := r.rolloutsInformer.GetIndexer().ByIndex(templateRefIndexName, refKey(v1alpha1.ObjectRef{
		Kind:       gvk.Kind,
		APIVersion: gvk.GroupVersion().String(),
		Name:       roMeta.GetName(),
	}, roMeta.GetNamespace()))
	if err != nil {
		return
	}

+	generation := strconv.FormatInt(roMeta.GetGeneration(), 10)
	for _, ro := range rollouts {
+		un, ok := ro.(*unstructured.Unstructured)
+		if ok {
+			rollout := unstructuredutil.ObjectToRollout(un)
+			updated := annotations.SetRolloutWorkloadRefGeneration(rollout, generation)
+			if updated {
+				_, err := r.argoprojclientset.ArgoprojV1alpha1().Rollouts(rollout.Namespace).Update(context.TODO(), rollout, v1.UpdateOptions{})
+				if err != nil {
+					fmt.Println("Error: updating rollout revision", err)
+				}
+			}

		}

		if key, err := cache.MetaNamespaceKeyFunc(ro); err == nil {
			r.rolloutWorkQueue.Add(key)
		}
	}
}
```
