### ISSUE TITLE
Istio integrated canary in multi-cluster setup

### ISSUE THREAD

**Issue by shakti-das** [argoproj/argo-rollouts#1191]
# Summary
We (Salesforce) are using [Istio multicluster setup primary-remote](https://istio.io/latest/docs/setup/install/multicluster/primary-remote/). Argo Rollouts current Istio integration patches VirtualService (VS) and DestinationRule (DR) in the cluster where the Rollout operator is running. This setup won't work in a multicluster setup because all the VS/DR will reside in the primary/config cluster, even the VS/DR for the remote cluster services. This would mean that the Rollout CRD will exist in a remote cluster but its corresponding VS/DR in the primary cluster. This enhancement request is to enable argo rollouts to handle this scenario. 

# Use Cases
This will enable Argo Rollout for Istio multi-cluster setup.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
This seems doable and not terribly difficult to implement.

For this to work:
1. We would introduce controller configuration to have credentials (e.g a kubeconfig) to external istio primary cluster
2. When configured with external primary clusters, the rollout controller would start additional watches on VirtualServices and DestinationRules in these primary clusters
3.  The rollout spec would introduce a new cluster field which references the configured cluster where the VS/DR reside:

```yaml
spec:
  strategy:
    canary:
      trafficRouting:
        istio:
          cluster: istio-primary.cluster.local
```

4. When modifications of the VS and DRs are needed, the controller will use the credentials of the remote to perform the modifications.

**Comment by shakti-das** [comment]
@jessesuen I would like to pick this up and start on a PR as we would need this pretty soon.

**Comment by jessesuen** [comment]
That would be great!

**Comment by jskrzypek** [comment]
Would this change lead to a rollouts installation having the same sort of behavior as argocd where it can manage multiple clusters with a single installation? Or would that make the controller too overburdened and it's anyhow better to install a single rollouts controller per cluster?

**Comment by shakti-das** [comment]
This won't enable the rollout controller to manage multiple clusters, only the IstioController will be configured to always read/watch from the Istio primary cluster (which may be different from the cluster where the rollout controller is running). The Istio primary cluster will contain the VS/DR that is specified in the `trafficRouting.istio` spec.

**Comment by Eslam-mohammed-anwar** [comment]
@jessesuen @shakti-das Great work, Can this solution help in case of Istio multi-cluster (replicated control plane), Thank you

**Comment by bq-arpit-20** [comment]
Can this solution work in Gloo mesh as well?
