### ISSUE TITLE
genenerate x-kubernetes-patch-merge-key and x-kubernetes-patch-strategy

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#1210]
# Summary

Kustomize 4 has finally has a mechanism to teach it how to SMP custom resources. See:

* https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/openapi/
* https://github.com/kubernetes-sigs/kustomize/issues/2825
* https://github.com/kubernetes-sigs/kustomize/issues/2339
* https://github.com/kubernetes-sigs/kustomize/blob/master/examples/customOpenAPIschema.md

 In order for kustomize to patch CRDs properly, we need to publish openAPI schema containing the following metadata in the Rollout CRD definitions.
* x-kubernetes-patch-merge-key
* x-kubernetes-patch-strategy

This will lower the barrier of entry to Rollouts and cause less surprising behavior.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by huikang** [comment]
@jessesuen , I can pick this up. Thanks.

**Comment by jessesuen** [comment]
Thanks @huikang !
