### ISSUE TITLE
Doc.: a "pod template" should be "replica-set template"?

### ISSUE THREAD

**Issue by dsbos** [argoproj/argo-rollouts#1221]
## Summary 

In the page section at https://argoproj.github.io/argo-rollouts/features/experiment/#experiment-spec, in the YAML, the comment before the `templates` member says "List of pod template specs ..."

Isn't it the case that:
- it is the nested `template` members that are actually the templates for _pods_, and
- what `templates` lists is really templates for _replica sets_ (since those list elements include `replicas` and `selector` (and then the pod-level `template`), which are part of ReplicaSets, right?)?

It seems that the comment on `templates` should begin more like "List of replica-set template specs" (with the remaining wording probably adjusted too).

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by rbreeze** [comment]
I think the verbiage as-is is clear enough. Even though the pod templates are nested in the list, it is still fundamentally a list of pod template specs, and the `to run in the experiment as ReplicaSets` part makes it even clearer. Closing but feel free to reopen if you disagree.
