### ISSUE TITLE
losing control on argo rollouts objects on upgrade to v.1.0.0

### ISSUE THREAD

**Issue by eilonmonday** [argoproj/argo-rollouts#1223]
Hey argo team,
We planned to upgrade all our clusters to use Argo v1.0.0, our current version is v.0.8.2.
Of course we started in staging env, when we upgraded the version, the deployment behind the Fargo object was still working, but when we tried to create new version of the deployment, nothing has happened, it felt like the new version can not handle the old argo object.
after we downgraded the version back to v0.8.2, we were able to manage deployments again..
Thanks,
Eilon

**Comment by jessesuen** [comment]
@eilonmonday to be on the safe side, I recommending not skipping releases. We generally do not recommend jumping any further than n+2 releases. Can you first upgrade to v0.10, allow rollouts to reconcile and any migration to logic to happen, and then upgrade to v1.0?

**Comment by eilonmonday** [comment]
@jessesuen Thanks for answering,
I tried to do so, yet I have the same issue.
Tried to look for logs of argo-rollouts:

E0530 07:59:47.806691       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 07:59:52.656894       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:00:04.266083       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:00:19.810706       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:00:55.157297       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:01:34.700781       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:02:18.769301       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:02:57.262060       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:03:36.056912       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:04:26.431430       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:05:02.989857       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:05:39.087146       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:06:17.882175       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:07:10.461211       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:07:46.660364       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:08:37.563999       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:09:12.315775       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:10:00.535464       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:10:32.920987       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:11:20.767227       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:11:52.542668       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:12:31.590161       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:13:06.790230       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:13:45.147097       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:14:31.066456       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:15:08.674474       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:16:02.334433       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:16:58.752535       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:17:37.667777       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:18:10.593242       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:19:09.902888       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:19:42.133422       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:20:32.567437       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:21:24.824708       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:22:00.314329       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:22:43.167055       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:23:33.648529       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:24:33.018164       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:25:30.686067       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:26:15.482025       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:27:13.293613       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:28:04.622672       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:28:51.537761       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:29:41.024226       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:30:27.578873       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:31:27.159672       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:32:06.823790       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:32:56.162035       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:33:28.729474       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:34:17.413236       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:34:58.505780       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:35:35.612441       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:36:11.231610       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:37:00.076197       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:37:42.387784       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:38:25.436968       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:39:14.191619       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:40:02.901626       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:40:54.778776       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:41:46.862595       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:42:31.800685       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:43:02.692672       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:43:32.751838       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:44:20.448735       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:45:07.237189       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:46:01.702671       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:46:45.457974       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:47:16.247680       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
E0530 08:48:11.624405       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *unstructured.Unstructured: clusteranalysistemplates.argoproj.io is forbidden: User "system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope

**Comment by jessesuen** [comment]
```
system:serviceaccount:argo-rollouts:argo-rollouts" cannot list resource "clusteranalysistemplates" in API group "argoproj.io" at the cluster scope
```

This is clear indication that your RBAC is not correct. The controller needs permission to list ClusterAnalysisTemplates. How did you install rollouts?

**Comment by eilonmonday** [comment]
@jessesuen I managed to resolve it, thank you so much! that was my fault while updating.
We are heavy users of Fargo rollouts, and we upgraded to the newest version. 
is there any other pipe that we can give feedback/report on bug issues?

**Comment by jessesuen** [comment]
OK glad you got it to work! In terms of feedback, issues and GitHub discussions are the most canonical way to report back so that community can also express their viewpoints.
