### ISSUE TITLE
status command exits before timout

### ISSUE THREAD

**Issue by DanTulovsky** [argoproj/argo-rollouts#1225]
## Summary 

I have a rollout that was being watched via `status` with a `--timeout=3h` flag.  It exited with a `degraded` after 20 minutes.

## Diagnostics

What version of Argo Rollouts are you running?  v1.0.1 (kubectl-argo-rollouts = v1.0.0)

```
2021-05-27 14:13:33 EDT Status: Downloaded newer image for gcr.io/helpful-cat-109717/kubectl-argo-rollouts:v1.0.0
2021-05-27 14:13:34 EDT Executing command: kubectl get deployment -l "app.kubernetes.io/name=managed-satellite-envoy" -o name | cut -d '/' -f 2 | xargs -n 1 kubectl-argo-rollouts status --timeout=3h
2021-05-27 14:33:51 EDT Error: The rollout is in a degraded state with message: ProgressDeadlineExceeded: ReplicaSet "public-satellite-pools-managed-satellite-envoy-v2-6f9df7c4bf" has timed out progressing.
```

14:13 is when helm pushed the change.
14:33 is when the command failed.

The rollout itself completed successfully shortly thereafter. 

(there is only one rollout returned by the first kubectl, and I've omitted the extra flags to kubectl for brevity)

```
# Paste the logs from the rollout controller

Logs attached. The server doesn't show any errors.  Possibly this is a client bug. I've seen this happen twice now.  Is there anything else I can provide to help here?

# Logs for the entire controller:
kubectl logs -n argo-rollouts depl
[filtered2.csv](https://github.com/argoproj/argo-rollouts/files/6556579/filtered2.csv)
oyment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by DanTulovsky** [comment]
This was the output from `status` itself:

```
Executing command: kubectl  get deployment -l "app.kubernetes.io/name=managed-satellite-envoy" -o name | cut -d '/' -f 2 | xargs -n 1 kubectl-argo-rollouts status --timeout=3h
Progressing - more replicas need to be updated
Progressing - more replicas need to be updated
Paused - CanaryPauseStep
Progressing - waiting for rollout spec update to be observed
Paused - CanaryPauseStep
Paused - CanaryPauseStep
Paused - CanaryPauseStep
Progressing - waiting for rollout spec update to be observed
Paused - CanaryPauseStep
Paused - CanaryPauseStep
Paused - CanaryPauseStep
Paused - CanaryPauseStep
Paused - CanaryPauseStep
Progressing - more replicas need to be updated
Progressing - more replicas need to be updated
Paused - CanaryPauseStep
Progressing - waiting for rollout spec update to be observed
Paused - CanaryPauseStep
Paused - CanaryPauseStep
Paused - CanaryPauseStep
Progressing - waiting for rollout spec update to be observed
Paused - CanaryPauseStep
Paused - CanaryPauseStep
Progressing - more replicas need to be updated
Degraded
Error: The rollout is in a degraded state with message: ProgressDeadlineExceeded: ReplicaSet "public-satellite-pools-managed-satellite-envoy-v2-6f9df7c4bf" has timed out progressing.
```

**Comment by jessesuen** [comment]
I think this was done by design. If your rollout degrades, do you still want to wait 3 hours?

**Comment by DanTulovsky** [comment]
Sorry, I must misunderstand something... the rollout is proceeding just fine.  it's:

1%
wait 600s
10%
wait 600s
30%
wait 600s
60%

I just tried again (with v1.0.1 kubectl-argo-rollouts) and it again failed after 20 minutes.  What exactly is progressDeadlineSeconds measuring (which seems to be set to 600 seconds)?

So I don't understand what's failing here. This is a rollout with 10 replicas. Is the issue here that there is no "progress" between 1% and 10% and that's why it fails?

**Comment by jessesuen** [comment]
`spec.progressDeadlineSeconds` is a time in seconds that a rollout must make progress during an update. Note that this should be simply continue making progress and it is not a whole deadline for the whole upgrade process.

It is supposed to act the same as the Deployment, which you can read about here: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#progress-deadline-seconds. By default it is set to 20 minutes.

Based on your observation, it's possible that there is a bug causing it to act as a deadline for the **entire update**, which was not the intent. We will need to investigate this as a bug

**Comment by DanTulovsky** [comment]
Just to be clear, the update continues and finishes normally. It's the cli that thinks it failed...

**Comment by DanTulovsky** [comment]
Is there anything more I can provide here to help?  We are hitting this fairly consistently and it's breaking our automated workflows...

**Comment by jessesuen** [comment]
@khhirani will be looking into this

**Comment by jessesuen** [comment]
@DanTulovsky could you give some insight on the rollout spec (e.g. canary steps) so we can try to reproduce?

**Comment by DanTulovsky** [comment]
canarySteps:
    - setWeight: 1
    - pause: {duration: 600s}
    - setWeight: 10
    - pause: {duration: 600s}
    - setWeight: 30
    - pause: {duration: 600s}
    - setWeight: 60
    - pause: {duration: 600s}

I would also try this with few replicas (~10 or so).

**Comment by khhirani** [comment]
> Based on your observation, it's possible that there is a bug causing it to act as a deadline for the **entire update**, which was not the intent. We will need to investigate this as a bug

@jessesuen I think this hypothesis is incorrect. I tested an example with the `progressDeadlineSeconds`=600s and these canary steps:
```
    - setWeight: 1
    - pause: {duration: 599s}
    - setWeight: 10
    - pause: {duration: 599s}
    - setWeight: 30
    - pause: {duration: 599s}
    - setWeight: 60
    - pause: {duration: 599s}
```
and the command `kar status --timeout 3h rollout-canary` did not time out.

**Comment by DanTulovsky** [comment]
@khhirani I will try setting progressDeadlineSeconds higher.  You are saying it just has to be higher than the pauseDuration?  You probably already know this, but the docs say that pause time is explicitly not accounted here:

```
  # The maximum time in seconds in which a rollout must make progress during
  # an update, before it is considered to be failed. Argo Rollouts will
  # continue to process failed rollouts and a condition with a
  # ProgressDeadlineExceeded reason will be surfaced in the rollout status.
  # Note that progress will not be estimated during the time a rollout is
  # paused.
```

It would be nice if that was true, since I expect to have large pauses (e.g. hours).

Thank you
Dan

**Comment by khhirani** [comment]
@DanTulovsky I think increasing the `progressDeadlineSeconds` should hopefully fix your issue for now. We still may need to make changes on our end - I'm currently running tests.

**Comment by DanTulovsky** [comment]
@khhirani thank you. Sorry, to answer your other questions, I only started using this with 1.0.1, so I don't know if this is a regression or not.

**Comment by DanTulovsky** [comment]
I can confirm that setting `progressDeadlineSeconds` to `1200` fixed my issue.

**Comment by jessesuen** [comment]
> I can confirm that setting progressDeadlineSeconds to 1200 fixed my issue.

This is a workaround. We identified the underlying issue and are producing a fix.
