### ISSUE TITLE
Create manifests that installs a specific CRD

### ISSUE THREAD

**Issue by dthomson25** [argoproj/argo-rollouts#123]
Users shouldn't have to install all 3 CRDS in order to use Argo Rollouts. Instead, users should be able to select which CRDS they would like to use.

**Comment by jessesuen** [comment]
Don't think we really need or should do this.

1) How would you accomplish this? Isn't the controller still going to want to generate informers for the other CRDs? The rollout controller is still going to still want to deal with the other types in the spec regardless if the CRD is installed or no.

2) I also don't think we want to deal with the corner cases for the different installation options, just to save on installing 2-3 additional lightweight CRD objects. E.g. we'll have to gracefully error when dealing with a spec which mentions experiments, but experiments is not installed.
