### ISSUE TITLE
Doc.: Add link/pointer to examples directory.

### ISSUE THREAD

**Issue by dsbos** [argoproj/argo-rollouts#1233]
# Summary

The documentation rooted at https://argoproj.github.io/argo-rollouts/ doesn't currently seem to have any link or other pointer/reference to the `examples/` directory at https://github.com/argoproj/argo-rollouts/tree/master/examples.

The documentation should somehow alert the reader to the presence of those examples, especially given that they seem to contain information that has not been put into the documentation tree yet.

(If it's appropriate, also link/point to https://github.com/argoproj/rollouts-demo.)

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by kostis-codefresh** [comment]
@dsbos the examples are already linked from the home page. Each paragraph in the Use Cases sections links to an example https://argoproj.github.io/argo-rollouts/#use-cases-of-argo-rollouts

But ok, we will try to make it more clear to readers, that an example directory exists.
