### ISSUE TITLE
Istio DestinationRule subset trafficPolicy lost

### ISSUE THREAD

**Issue by ryantse** [argoproj/argo-rollouts#1238]
## Summary 

When using Argo Rollouts' new Istio DestinationRule subset support, the subset's trafficPolicy is lost during the update.

I believe this is due to an incomplete copy of the structure of Istio's DestinationRule Subset struct. The problematic code is: https://github.com/argoproj/argo-rollouts/blob/master/rollout/trafficrouting/istio/istio_types.go#L47-L50

## Diagnostics

Argo Rollouts 1.0.1

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by huikang** [comment]
Hi, @jessesuen , I am able to reproduce this error. Please assign this to me if @ryantse has not started fixing it.

**Comment by ryantse** [comment]
@huikang: I haven't done anything significant towards fixing this issue. I had a quick conversation with @jessesuen about the issue here: https://cloud-native.slack.com/archives/C01U781DW2E/p1622568650056300

I believe the goal was to make it so that future fields that may be added to the Istio DestinationRule, potentially in later versions, would be supported automatically and not require an additional code change.

In the meantime while waiting for a more comprehensive fix for this issue, I have patched it extremely narrowly to fix trafficPolicy for my own use, as follows:
```
diff --git a/rollout/trafficrouting/istio/istio_types.go b/rollout/trafficrouting/istio/istio_types.go
index d8e605cf..00d26225 100644
--- a/rollout/trafficrouting/istio/istio_types.go
+++ b/rollout/trafficrouting/istio/istio_types.go
@@ -1,6 +1,7 @@
 package istio
 import (
+       "encoding/json"
        metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
 )
@@ -47,4 +48,5 @@ type DestinationRuleSpec struct {
 type Subset struct {
        Name   string            `json:"name,omitempty"`
        Labels map[string]string `json:"labels,omitempty"`
+       TrafficPolicy *json.RawMessage `json:"trafficPolicy,omitempty"`
 }
```

**Comment by huikang** [comment]
@ryantse , thanks for the information.

@jessesuen , after reading your slack chat, my understanding is that instead of using the internal structure of Subset, a more general struct like https://github.com/argoproj/argo-rollouts/blob/ccff157410d2c86c7e608444c4d410b9218c82fa/utils/unstructured/unstructured.go#L24 is preferred for solving the issue. Is this correct?

Another alternative is to import istio's definition of Subset (https://github.com/istio/api/blob/9a4239731e79ca441e6277e1ac8b38be48f31224/networking/v1beta1/destination_rule.pb.go#L655). Is the con of this approach lack of automatic support in case istio change the fields?

**Comment by jessesuen** [comment]
> I believe the goal was to make it so that future fields that may be added to the Istio DestinationRule, potentially in later versions, would be supported automatically and not require an additional code change.

Exactly.

> Is the con of this approach lack of automatic support in case istio change the fields?

Correct. We try as much as possible not to have dependencies on other codebases or API definitions that may change. So the goal is to have an implementation that only mutates the fields which we care about, while leaving everything else intact.

> a more general struct like is preferred for solving the issue. Is this correct?

Yes, we cannot drop fields. The best way I know how to do that is by using the Unstructured object.

**Comment by huikang** [comment]
@jessesuen @ryantse , thanks for the info. I will try submitting a fix.
