### ISSUE TITLE
Problem serving controller metrics when collecting "analysis_template_metric_info"

### ISSUE THREAD

**Issue by zombispormedio** [argoproj/argo-rollouts#1239]
## Summary 

When I updated to the latest version, controller metrics stopped working and started to return the following error:

```An error has occurred while serving metrics:
1 error(s) occurred:
[from Gatherer #1] collected metric "analysis_template_metric_info" { label:<name:"name" value:"my-template" > label:<name:"namespace" value:"my-namespace" > label:<name:"type" value:"Web" > gauge:<value:1 > } was collected before with the same name and label values
```

## Diagnostics
After doing some investigation, controller metrics are failing where there are AnalysisTemplate resources with more than 1 metric. 
For example:
```apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: my-tests
spec:
  metrics:
    - name: test-1
      successCondition: result == 'true'
      provider:
        web:
          url: "http://my-test-1.com"
          jsonPath: "{$.ok}"
    - name: test-2
      successCondition: result == 'true'
      provider:
        web:
          url: "http://my-test-2.com"
          jsonPath: "{$.ok}"
```

What version of Argo Rollouts are you running?

Argo Rollouts 1.0.1

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
> After doing some investigation, controller metrics are failing where there are AnalysisTemplate resources with more than 1 metric.

Thanks for the investigation. Will include this in a v1.0.2 patch

**Comment by harikrongali** [comment]
will work on this issue

**Comment by jessesuen** [comment]
Fixed in https://github.com/argoproj/argo-rollouts/pull/1261
