### ISSUE TITLE
First-class support for configuration changes

### ISSUE THREAD

**Issue by rbaybutt** [argoproj/argo-rollouts#1244]
# Summary

When using Rollouts for canary deploys the current common practice for dealing with changes to ConfigMaps that define config for an application is to hash the contents. They're hashed such that the canary config and current stable config are two distinct ConfigMaps used by each version of the application. The issue with this is when deploying a Rollout with a tool like Argo CD the config diffs are unusable. The diffs appear as two distinct ConfigMaps that are not inlined for comparison. The ask is to find a way to treat the config as a first class citizen such that configuration need not be hashed (or similar approach) and Rollouts is aware of changes to a ConfigMap. If a simplified approach could be implemented so that diffs would be usable that would also suffice. 
This issue is a follow on from this comment: https://github.com/argoproj/argo-rollouts/issues/958#issuecomment-818248263 

# Use Cases

Any deployment of a Rollout with a modification to a ConfigMap where the deployment of said Rollout is managed by Argo CD or similar tool. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
I'm having trouble understanding how this would be different from https://github.com/argoproj/argo-rollouts/issues/958. Can you explain?

**Comment by rbaybutt** [comment]
Based on further comments in https://github.com/argoproj/argo-rollouts/issues/958 and direction with Reloader I think the principal issue I wanted to address with Argo CD diffs will also be addressed so I'll close this issue.
