### ISSUE TITLE
Rollout Dashboard should allow user select namespace

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-rollouts#1255]
# Summary

It should be possible to start Dashboard in full cluster mode and allow user to switch between namespaces in the UI.

# Use Cases

The full cluster mode should be useful when the Rollout Dashboard runs as a deployment. Following changes should be implemented:

* add `--namespace` flag to `kubectl argo rollout dashboard`  command:
    * if the flag is not specified then the dashboard shows rollouts from the current namespace (same as now)
    * if flag is set to an empty string then dashboard switch into full cluster mode and allow user to select namespace in UI
    * if flag is set to non empty string then dashboard shows rollout from the specified namespace

* if rollout is working in full cluster mode then the UI should allow selecting namespace. The readonly namespace input should be replaced with the autocomplete component. The autocomplete list should contains namespaces of all rollouts found in the cluster.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by perenesenko** [comment]
I will work on this one

**Comment by perenesenko** [comment]
#1291

**Comment by perenesenko** [comment]
Was desided to implement it in a different way.
We're not going to use the namespace parameter. Instead we're going to provide ability for the customer to pick the desired namespace from the dropdown list. It will be prepopulated with the namespace list that has at least one rollout object.

![image](https://user-images.githubusercontent.com/14903681/122822876-85b21c80-d293-11eb-992b-de592c40a1d7.png)

So the user can pick any from a list or type a custom namespace

**Comment by DanTulovsky** [comment]
I have two requests if you don't mind.

1. Have an 'All' option that includes rollouts from all namespaces
2. Make the Rollouts themselves take up less space in the UI (perhaps a line per rollout, rather than a box). It looks nice with 2 - 4 Rollouts, but becomes unmanagable with many more.

Thank you!

**Comment by perenesenko** [comment]
We discussed previously about pulling rollouts from the all namespaces. It could be performance issues during watch. @alexmt could you confirm?

What about the formatting UI I think we can have dedicated task for that

**Comment by perenesenko** [comment]
@DanTulovsky 
Regarding #2. We need more discussion here. Can we shrink it to 1 line, or maybe 2. Can we remove the labels "strategy", "weight" and keep only the value with icons. Can we remove the buttons, etc.  Or maybe we can have 2 versions of the view.

It's better to have it on a separate task and all the discussion there.

**Comment by alexmt** [comment]
>  It could be performance issues during watch.

Correct. In addition to rollouts Dashboard watches all replicaset and pods. Number of replicasets and pods might be several times more than Rollout objects. So we have to ask users to view one namespace at a time.

**Comment by jessesuen** [comment]
Fixed in https://github.com/argoproj/argo-rollouts/pull/1291
