### ISSUE TITLE
Fast rollback in BlueGreen during scale down period

### ISSUE THREAD

**Issue by dthomson25** [argoproj/argo-rollouts#127]
If a rollout is reverted to the previous replicaset during the scale down wait period of a bluegreen deployment, the rollout should do a fast roll back to the previous version. Currently, the rollout will pause instead of doing a fast rollback.

**Comment by jessesuen** [comment]
Given that we are attaching independent scale down delays to replicasets as part of https://github.com/argoproj/argo-rollouts/issues/128, the behavior should be that if we move to ANY existing replicaset which is within it's scaleDownDelay, then we consider that a fast-tracked rollback and skip the pause.

**Comment by carlosdoordash** [comment]
@dthomson25 How do you `revert a rollout to the previous replicaset`?

Steps...
1.  Set the blueGreen strategy `scaleDownDelaySeconds: 600` to keep the old pods around for 10 minutes
2. Patch the rollout with `kubectl rollout servicename --type merge -p {"spec": {"paused": false}}`
3. Now I have 10 minutes to monitor with 100% traffic going to the new pods.
4. If I see errors, how do I rollback traffic to the old pods (aka `revert a rollout to the previous replicaset`)?

**Comment by jessesuen** [comment]
You need to re apply the old manifest. If the pod template hash matches the old replica set which has not yet been scaled down, then this will be fast tracked.
