### ISSUE TITLE
Docs: inconsistent urls and broken links

### ISSUE THREAD

**Issue by kostis-codefresh** [argoproj/argo-rollouts#1278]
(Reported by Bryan Taylor in the CNCF slack channel)

The documentation pages have mixed rendering results where sometimes the extension .html works and sometimes it doesn't

https://argoproj.github.io/argo-rollouts/features/traffic-management/istio/ -> renders a broken page
https://argoproj.github.io/argo-rollouts/features/traffic-management/istio.html -> works ok

But on the other hand

https://argoproj.github.io/argo-rollouts/getting-started/istio/ -> works ok
https://argoproj.github.io/argo-rollouts/getting-started/istio.html -> renders a broken page.

The issue here (apart from the inconsistency) is that the broken links are indexed by Google confusing users.

We should either fix all links to have a consistent rendering or make the wrong ones return 404 instead of broken renderings

![problematic-urls](https://user-images.githubusercontent.com/39800303/122034515-476fb580-cdda-11eb-9f26-e4c3c9c405db.png)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
Fixed in https://github.com/argoproj/argo-rollouts/pull/1321
