### ISSUE TITLE
Support to add annotations to AnalysisRuns that are created from Templates

### ISSUE THREAD

**Issue by btlyken** [argoproj/argo-rollouts#1282]
# Summary

As someone who wants to use `ClusterAnalysisTemplate`s to test our deployed microservices during and after a canary deployment, it would be useful to be able to add annotations to the `AnalysisRun`s that get created from these templates. Instead of using a template, we have to create individual runs for each microservice we're testing with the annotations we want.

# Use Cases

My main use case in mind is to be able to add a `helm.sh/hook: test` annotation so that we can use `helm test` to use these `AnalysisRun`s to validate the deployed microservices are functioning correctly. We'd also like to include add a `helm.sh/hook-delete-policy` annotation to clean up these runs during the next deployment or after the run succeeds.

Two ways I could see implementing this would be:
- For the `AnalysisRun` to inherit the annotations of the template resource
  - One potential issue with this route is that it would inherit Helm deployment annotations and labels which may not match the microservice's Helm deployment info
- For there to be a `metadata` section, such as `spec.template.metadata`, that would support adding annotations and labels to these runs

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by shaoye** [comment]
already fixed by https://github.com/argoproj/argo-rollouts/pull/2743

**Comment by zachaller** [comment]
fixed by #2743, thanks for linking them
