### ISSUE TITLE
Option to prune argocd "Application" when a rollout is promoted

### ISSUE THREAD

**Issue by puru86** [argoproj/argo-rollouts#1284]
# Summary
When services have related configmaps and secrets, then the data objects can be (usually are) versioned as well. 

Doing a blue-green rollout or a canary rollout requires that old configmaps and secrets stay available through the transition.

However once the promotion is complete, only the pods are cleaned up. We need a way to provide configmaps and secrets that can be cleaned up when a promotion is completed.

When argocd is being used, then a prune being called on the application is also sufficient.

# Use Cases

For example:
A deployment called spring-boot-app is using a ConfigMap called spring-boot-app-1-0-0-configs and a secret called spring-boot-app-1-0-0-secrets. These associations make sense when you consider version 1.0.0 of the spring-boot-app.

Now while deploying using argocd, our old configmaps and secrets remain, albeit as prunable resources. We rollout and promote the new build (which includes the new configmaps and secrets). Now our ArgoCD Application stays in out-of-sync mode because the old configmaps and secrets have not been pruned.

We end up with:
![image](https://user-images.githubusercontent.com/8615440/122209728-7a8d7400-cec2-11eb-8234-4e0bf5af56ba.png)

In the image:
1. spring-boot-example version 0.1.4 is live.
2. It is using 0-1-4 variants of the configmap and secrets.
3. However the older 0-1-3 variants have to be pruned manually.

It will be amazing if we can specify an argocd action for the rollout to execute post promotion.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by puru86** [comment]
So an update - i am able to currently get around this by setting syncOptions[PruneLast=true] for the Application being in argoCD.

In this case, since the Promotion is considered as a phase in the sync, it pauses for the promotion to complete before pruning.

Would like to have a definitive answer if this is the correct way to proceed or if this is an accidental quirk made possible through good design practices on your end!

**Comment by jessesuen** [comment]
Yep, PruneLast=true was implemented for exactly your use case (e.g. deleting configmaps randomly suffixed by kustomize configmap generators), so it is the correct way to handle your use case.
