### ISSUE TITLE
Rollout incorrectly manages 3 replicasets

### ISSUE THREAD

**Issue by gavin-db** [argoproj/argo-rollouts#1295]
## Summary 

What happened/what you expected to happen?

In a dev region, we saw that one Rollout (graphql) was managing 3 replicasets for an extended period of time:

```
$kubectl get pods -n graphql
graphql-6c7865774c-h8mkl            2/2     Running   0          21h
graphql-6c7865774c-wbl78            2/2     Running   0          21h
graphql-6d588fb886-mpjtw            2/2     Running   0          3h22m
graphql-8547b7bb9c-zqc7f            2/2     Running   0          6h12m
```

```
$ kubectl get rollout -n graphql
NAME   DESIRED  CURRENT  UP-TO-DATE  AVAILABLE
graphql  2     4           4
$ kubectl get rollout -n graphql
...
Status:
  HPA Replicas:        4
  Available Replicas:  4
  Blue Green:
  Canary:
  Conditions:
    Last Transition Time:  2021-05-25T19:17:48Z
    Last Update Time:      2021-05-25T19:17:48Z
    Message:               Rollout has minimum availability
    Reason:                AvailableReason
    Status:                True
    Type:                  Available
    Last Transition Time:  2021-06-08T00:21:23Z
    Last Update Time:      2021-06-08T00:21:23Z
    Message:               RolloutCompleted
    Reason:                RolloutCompleted
    Status:                False
    Type:                  Completed
    Last Transition Time:  2021-06-08T00:43:50Z
    Last Update Time:      2021-06-08T00:43:50Z
    Message:               Rollout is paused
    Reason:                RolloutPaused
    Status:                False
    Type:                  Paused
    Last Transition Time:  2021-06-08T00:43:50Z
    Last Update Time:      2021-06-08T21:19:03Z
    Message:               Created new replica set "graphql-59495b85d4"
    Reason:                NewReplicaSetCreated
    Status:                True
    Type:                  Progressing
  Current Pod Hash:        59495b85d4
  Current Step Hash:       8cdbf64bf
  Current Step Index:      0
  Message:                 more replicas need to be updated
  Observed Generation:     46
  Phase:                   Progressing
  Ready Replicas:          4
  Replicas:                4
  Selector:                app=graphql
  Stable RS:               6c7865774c
Events:
  Type    Reason          Age   From                 Message
  ----    ------          ----  ----                 -------
  Normal  RolloutUpdated  27m   rollouts-controller  Rollout updated to revision 43
```

![Screen Shot 2021-06-08 at 6 16 59 PM](https://user-images.githubusercontent.com/65616577/122965557-2c9ec300-d33d-11eb-96d4-28a334059f34.png)

Although Revision 40 shows healthy, it looks like something weird happened for revisions 41 and 42. They appear to have created new Replicasets without scaling down the existing replicasets. Also, neither of them were marked as healthy by Argo.
Additionally, there is no `AnalysisRun` step for revision 41 and 42. Instead I see `Pod`. Lastly, it appears that the Rollout may have temporarily lost its `status` field from our service logs, although it was present when I looked at the resource.

There were no Yaml changes to the underlying AnalysisTemplate or strategy used over the duration of the releases. There were several errors in the controller logs that may be related; it is possible that improper error handling led to this unhealthy state.

To recover the error, we released a Deployment in parallel to the Rollout and then deleted and recreated the Rollout.

## Diagnostics

What version of Argo Rollouts are you running?
`argoproj/argo-rollouts:v1.0.0`

# Paste the logs from the rollout controller
Two errors appeared repeatedly in the logs:

```
time="2021-06-01T21:40:27Z" level=error msg="rollout syncHandler error: Operation cannot be fulfilled on replicasets.apps \"graphql-7f58886b55\": the object has been modified; please apply your changes to the latest version and try again" namespace=graphql rollout=graphql
time="2021-06-01T22:21:11Z" level=error msg="rollout syncHandler error: Operation cannot be fulfilled on replicasets.apps \"cmapiserver-757dbfcb6b\": the object has been modified; please apply your changes to the latest version and try again" namespace=cmapiserver rollout=cmapiserver
time="2021-06-02T00:39:59Z" level=error msg="rollout syncHandler error: Operation cannot be fulfilled on replicasets.apps \"graphql-5f49f44d77\": the object has been modified; please apply your changes to the latest version and try again" namespace=graphql rollout=graphql
time="2021-06-02T18:02:08Z" level=warning msg="measurement had error: Post \"http://m3coord-read-regional-internal-svc.m3.svc.cluster.local:7201/api/v1/query\": context deadline exceeded" analysisrun=graphql-7d64575948-21 metric=readiness-check namespace=graphql
time="2021-06-02T18:02:38Z" level=warning msg="measurement had error: Post \"http://m3coord-read-regional-internal-svc.m3.svc.cluster.local:7201/api/v1/query\": context deadline exceeded" analysisrun=graphql-7d64575948-21 metric=liveness-check namespace=graphql
```

```
E0608 21:46:38.130958       1 controller.go:172] pods "graphql-6c7865774c-h8mkl" is forbidden: unable to validate against any pod security policy: [pod.spec.securityContext.sysctls[0]: Forbidden: unsafe sysctl "net.ipv4.tcp_keepalive_time" is not allowed pod.spec.securityContext.sysctls[1]: Forbidden: unsafe sysctl "net.ipv4.tcp_keepalive_probes" is not allowed pod.spec.securityContext.sysctls[2]: Forbidden: unsafe sysctl "net.ipv4.tcp_keepalive_intvl" is not allowed spec.initContainers[0].securityContext.capabilities.add: Invalid value: "NET_ADMIN": capability may not be added spec.initContainers[0].securityContext.capabilities.add: Invalid value: "NET_RAW": capability may not be added]
time="2021-06-08T21:53:18Z" level=warning msg="primary ingress has been deleted" ingress=test-shard-runbot-master-aws-4-997/test-shard-ingress
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
The following errors are benign:
```
time="2021-06-01T21:40:27Z" level=error msg="rollout syncHandler error: Operation cannot be fulfilled on replicasets.apps \"graphql-7f58886b55\": the object has been modified; please apply your changes to the latest version and try again" namespace=graphql rollout=graphql
time="2021-06-01T22:21:11Z" level=error msg="rollout syncHandler error: Operation cannot be fulfilled on replicasets.apps \"cmapiserver-757dbfcb6b\": the object has been modified; please apply your changes to the latest version and try again" namespace=cmapiserver rollout=cmapiserver
time="2021-06-02T00:39:59Z" level=error msg="rollout syncHandler error: Operation cannot be fulfilled on replicasets.apps \"graphql-5f49f44d77\": the object has been modified; please apply your changes to the latest version and try again" namespace=graphql rollout=graphql
time="2021-06-02T18:02:08Z" level=warning msg="measurement had error: Post \"http://m3coord-read-regional-internal-svc.m3.svc.cluster.local:7201/api/v1/query\": context deadline exceeded" analysisrun=graphql-7d64575948-21 metric=readiness-check namespace=graphql
time="2021-06-02T18:02:38Z" level=warning msg="measurement had error: Post \"http://m3coord-read-regional-internal-svc.m3.svc.cluster.local:7201/api/v1/query\": context deadline exceeded" analysisrun=graphql-7d64575948-21 metric=liveness-check namespace=graphql
```


However, this error seems suspicious. Do you have any idea what caused this? It's also strange that the `graphql-6c7865774c` pod is the one affected as it is already running.

```
E0608 21:46:38.130958       1 controller.go:172] pods "graphql-6c7865774c-h8mkl" is forbidden: unable to validate against any pod security policy: [pod.spec.securityContext.sysctls[0]: Forbidden: unsafe sysctl "net.ipv4.tcp_keepalive_time" is not allowed pod.spec.securityContext.sysctls[1]: Forbidden: unsafe sysctl "net.ipv4.tcp_keepalive_probes" is not allowed pod.spec.securityContext.sysctls[2]: Forbidden: unsafe sysctl "net.ipv4.tcp_keepalive_intvl" is not allowed spec.initContainers[0].securityContext.capabilities.add: Invalid value: "NET_ADMIN": capability may not be added spec.initContainers[0].securityContext.capabilities.add: Invalid value: "NET_RAW": capability may not be added]
```


Are you able to provide any of the following?
* logs grepped for `rollout=graphql` during the time period
* kubectl get events during the time period

**Comment by gavin-db** [comment]
> However, the following error seems suspicious. Do you have any idea what caused this? It's also strange that the graphql-6c7865774c pod is the one affected as it is already running.

The full error that you mentioned as suspicious was: 
```
E0608 21:46:38.130958       1 controller.go:172] pods "graphql-6c7865774c-h8mkl" is forbidden: unable to validate against any pod security policy: [pod.spec.securityContext.sysctls[0]: Forbidden: unsafe sysctl "net.ipv4.tcp_keepalive_time" is not allowed pod.spec.securityContext.sysctls[1]: Forbidden: unsafe sysctl "net.ipv4.tcp_keepalive_probes" is not allowed pod.spec.securityContext.sysctls[2]: Forbidden: unsafe sysctl "net.ipv4.tcp_keepalive_intvl" is not allowed spec.initContainers[0].securityContext.capabilities.add: Invalid value: "NET_ADMIN": capability may not be added spec.initContainers[0].securityContext.capabilities.add: Invalid value: "NET_RAW": capability may not be added]
time="2021-06-08T21:53:18Z" level=warning msg="primary ingress has been deleted" ingress=test-shard-runbot-master-aws-4-997/test-shard-ingress
```
Note the `primary ingress has been deleted` line; I forgot to include that in the above report and it is probably relevant to the failure.

> Are you able to provide any of the following?
> 
> logs grepped for rollout=graphql during the time period
> kubectl get events during the time period

Unfortunately this happened while I was on vacation and the logs do not go back that far, so we only have what I happened to store. 

This appears to be a bug related to Istio work our service infrastructure team was doing in dev - I will ping one of them to comment on this thread with any additional details.

> Lastly, it appears that the Rollout may have temporarily lost its status field from our service logs, although it was present when I looked at the resource.
> 
> Could you elaborate on what leads you to believe this? This would definitely be a problem.
Our internal deployment tool is fairly sophisticated and tracks the progress of releases. When we deleted the malfunctioning Rollout and redeployed it our deploy tool logged the following:

```
rollout.argoproj.io/graphql created
...
2021/06/09 01:25:20 ERROR kubecfg.py:306: ('Cannot find status field in rollout %s with namespace %s', (u'graphql', u'graphql'))
```
This means that 
1. Kubectl reported the Rollout resource as created
2. Our Deploy tool successfully pulled the manifest for the running Rollout out of the cluster
3. When trying to access the status field in the Rollout manifest, the status key did not exist

It is unclear if that was an effect of whatever error was ongoing at the time. It only occurred once. I think the root cause of this issue has to do with the `primary ingress has been deleted` error and it's handling.

**Comment by gavin-db** [comment]
@jessesuen I talked with service infra to determine what caused the suspicious error. 

At the time of the error the graphql pod was running with an Istio sidecar container. Istio requires admin level privileges to modify pods but our Pod Security Policy prevented this. When we inject the Istio sidecar, the PSP won't let the pod come up and produces the above error because Istio won't be able to add new IP Table rules. 

The running theory is that Argo started rolling out the new version but the pod never got scheduled by k8s due to this PSP. And then k8s eventually scheduled the pod when we disabled Istio injection/manually applied the PSP change.

**Comment by agrawroh** [comment]
@gavin-db ^ This sums it up very nicely! 

@jessesuen Any thoughts on what should be the correct behavior from Argo side in case k8s fails to schedule pods or something else happens preventing the pods to come up? Should Argo scale down this ReplicaSet in addition to marking the old (running) version as stable again?

**Comment by jessesuen** [comment]
> @jessesuen Any thoughts on what should be the correct behavior from Argo side in case k8s fails to schedule pods or something else happens preventing the pods to come up?

I expect Rollouts to already handle the following situation gracefully, where:
1. the Rollout cannot create the ReplicaSet
2. the Rollout can create the ReplicaSet, but the ReplicaSet cannot create pods (e.g. due to pod admission webhook)

Admittedly we don't have good e2e testing on these scenarios, so perhaps something could have regressed.

>  Should Argo scale down this ReplicaSet in addition to marking the old (running) version as stable again?

We don't have an option ATM to abort an update and go back to stable when we exceed progressDeadlineSeconds. But it's been asked for. Right now it behaves just like Rolling Update.
