### ISSUE TITLE
Canary becomes stuck when the new rollout fails and it involves a change in ConfigMap

### ISSUE THREAD

**Issue by sarialem** [argoproj/argo-rollouts#1297]
## Summary 
When a new rollout is deployed that involves a change in the ConfigMap, and the canary rollout degrades, it's unable to upscale the stable replicaset back to normal, since the change in the ConfigMap is not rolled back and causes the stable pods to fail to start (stable code needs).

What happened/what you expected to happen?
The config map was not rolled back when the canary degraded, and it should be changed back to the same state it was before deploying the new rollout.

## Diagnostics

What version of Argo Rollouts are you running?
0.9

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
> The config map was not rolled back when the canary degraded, and it should be changed back to the same state it was before deploying the new rollout.

This is a problem not specific to rollouts, and it's also not something Rollouts can solve, as it only performs rollbacks to previous replicasets. It does not deal with any other configuration objects (ConfigMaps, Secrets) as part of rollback. Even if it wanted to, the previous configmap contents are lost (replaced by the new contents) and not accessible by the Rollout.

For your use case, you should consider something like Kustomize [configmap generators](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/configGeneration.md) which uses new configmaps for every change in the content.

**Comment by jessesuen** [comment]
When rollback needs to involve multiple objects (e.g. Rollout + ConfigMap + Secret + other random custom resources), this should be happening at a higher level, for example, an Argo CD rollback. Doing this at a higher level allows you to roll back multiple objects as a unit. 

In Rollouts v1.1, which will have support for notification webhooks, a webhook could theoretically be invoked to signal Argo CD that it should perform a rollback when the Rollout degrades.
