### ISSUE TITLE
Invalid log level when notificaiton is not set

### ISSUE THREAD

**Issue by huikang** [argoproj/argo-rollouts#1303]
## Summary 

What happened/what you expected to happen?

## Diagnostics

When a rollout is created without setting up notification, users don't need to worry about the irrelevant message about notification. However, the current implementation emits ERROR log message. 

We could change the log level to `WARN`.

What version of Argo Rollouts are you running?
1.1 (master)

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

NFO[2021-06-24T10:57:57-04:00] Start processing                              resource=default/rollouts-demo-canary
ERRO[2021-06-24T10:57:57-04:00] Failed to process: secret "argo-rollouts-notification-secret" not found  resource=default/rollouts-demo-canary
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
> What version of Argo Rollouts are you running?
> 1.0.2

Did you mistype this and meant to say 1.1? Notification is only in v1.1 (master)

**Comment by huikang** [comment]
> 
> Did you mistype this and meant to say 1.1? Notification is only in v1.1 (master)

Yes, updated the problem description.

**Comment by huikang** [comment]
@jessesuen I found that if the error message disappears if the notification controller is commented at https://github.com/argoproj/argo-rollouts/blob/255ce28d303bc3a6d94a9df9b6c727f57491a8d1/controller/controller.go#L304

So how about add a command line option to control if the notification controller is need, i.e., `--enable-notification bool` (default is true). If the option is disabled, we don't need to start the notification controller.

Also it looks like we can not control the log level in the argo notification package.
