### ISSUE TITLE
Dashboard UI with namespace picker doesn't show individual rollout in other namespace

### ISSUE THREAD

**Issue by gempesaw** [argoproj/argo-rollouts#1334]
## Summary 

After #1291, it's possible to install the dashboard in one namespace and view Rollouts in another namespace. The main page which watches multiple Rollouts works fine and displays Rollouts in other namespaces. However, accessing the individual page for a Rollout in a different namespace shows an empty page. 

The logs mention that the Rollout resource wasn't found. If I `kubectl argo rollouts dashboard` in the appropriate namespace, the "individual rollout page" works as expected.

From the UI, the namespace looks to be correct in the `/watch` request
![image](https://user-images.githubusercontent.com/1437272/125096257-7ff66c80-e0c4-11eb-8399-56d02c14c906.png)
but I notice in #1291 that `WatchRolloutInfos` was updated to get the context from the `ws`:

https://github.com/argoproj/argo-rollouts/blob/ba21c6cacaba5cc327a725b6546ff7173f426bc1/server/server.go#L295

whereas `WatchRolloutInfo` is not accordingly updated, and still uses `context.Background()`

https://github.com/argoproj/argo-rollouts/blob/ba21c6cacaba5cc327a725b6546ff7173f426bc1/server/server.go#L213-L214

## Diagnostics

I'm running dashboard docker image `quay.io/argoproj/kubectl-argo-rollouts@sha256:c9d6c70161fa86aac4f9c0747049809c92e5b1d1356c0e62f3299d407f76c4ad`, which was the SHA of "latest" from last week. 

```
kubectl logs argo-rollouts-dashboard-b6dbf8898-c79zr --namespace=argo-rollouts --namespace=argo-rollouts

time="2021-07-09T04:12:47Z" level=info msg="Argo Rollouts Dashboard is now available at localhost 3100"
time="2021-07-09T04:30:21Z" level=warning msg="rollout.argoproj.io \"hello-pagey-argo-canary\" not found"
time="2021-07-09T04:30:27Z" level=warning msg="rollout.argoproj.io \"hello-pagey-argo-canary\" not found"
time="2021-07-09T04:30:37Z" level=warning msg="rollout.argoproj.io \"hello-pagey-argo-canary\" not found"
time="2021-07-09T04:36:05Z" level=warning msg="rollout.argoproj.io \"hello-pagey-argo-canary\" not found"
time="2021-07-09T13:28:40Z" level=warning msg="rollout.argoproj.io \"hello-pagey-argo-canary\" not found"
time="2021-07-09T13:28:45Z" level=warning msg="rollout.argoproj.io \"hello-pagey-argo-canary\" not found"
time="2021-07-09T13:48:52Z" level=warning msg="rollout.argoproj.io \"hello-pagey-argo-canary\" not found"
time="2021-07-09T13:48:59Z" level=warning msg="rollout.argoproj.io \"hello-pagey-argo-canary\" not found"
time="2021-07-09T13:50:52Z" level=warning msg="rollout.argoproj.io \"hello-pagey-argo-canary\" not found"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by marcportabellaclotet-mt** [comment]
I am having the same issue.
```
level=warning msg="rollout.argoproj.io \"rollouts-demo\" not found"
```
I am able to browse namespaces where there are rollouts, but when clicking into it, it returns an empty page.

By the way, argo rollouts is an awesome product!!!

**Comment by jessesuen** [comment]
@perenesenko could you look into this?

**Comment by perenesenko** [comment]
Yes. I will look on it

**Comment by perenesenko** [comment]
PR https://github.com/argoproj/argo-rollouts/pull/1344
