### ISSUE TITLE
A single rollout should support multiple Istio VirtualServices

### ISSUE THREAD

**Issue by aweis89** [argoproj/argo-rollouts#1349]
# Summary

Currently the Argo Rollouts spec only supports a single VirtualService. This forces folks with multiple VirtualService's with the same destinations to chose which one to use for the canary rollout.

# Use Cases

It's very common to have multiple VirtualService's pointing to a single backend service. One example where this is commonly needed is when associating a VirtualService with a Gateway. You often want separate URLs/hosts/rewrites for the Gateway VirtualService vs the VirtualService being used internally.

One of the nice things about using Istio for canary rollouts is that it enables canary for either internal or external traffic since the same VirtualService API can be used for either. While either type of virtual service currently works with Argo Rollouts, it would be ideal if there was an option to specify both the gateway virtual service and the internal one, even when they're separate resources. This would enable the canary rollout to apply to all traffic in such instances instead of forcing folks to chose.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
Agree, but is auplicate of https://github.com/argoproj/argo-rollouts/issues/1100
