### ISSUE TITLE
Argo Rollouts AnalysisTemplates of Job type set an auto-generated label longer than 63 characters

### ISSUE THREAD

**Issue by jstewart612** [argoproj/argo-rollouts#1350]
## Summary 

What happened/what you expected to happen?

Argo Rollouts AnalysisTemplates of Job type set an auto-generated label longer than 63 characters.  If you're going to auto-generate a name, and my input did not exceed 63 characters, you should be doing so in a manner that does not make a resulting auto-generated label only you use longer than 63 characters and thus cause the Job the AnalysisTemplate wants to create not to be unable to be created and thus fail.

## Diagnostics

What version of Argo Rollouts are you running?

1.0.4

```
RolloutAborted
Rollout aborted update to revision 10: metric "location-review-service-job" assessed Error due to consecutiveErrors (5) ] consecutiveErrorLimit (4): "Error Message: Job.batch "7253752d-9f4c-43f2-8605-6e140d720610.location-review-service-job.5" is invalid: spec.template.labels: Invalid value: "7253752d-9f4c-43f2-8605-6e140d720610.location-review-service-job.5": must be no more than 63 characters"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
Duping to https://github.com/argoproj/argo-rollouts/issues/795
