### ISSUE TITLE
Dashboard: display the scaledown delay second if a replicaset is scheduled to be scaled down

### ISSUE THREAD

**Issue by huikang** [argoproj/argo-rollouts#1355]
# Summary

What change needs making?

The argo-rollouts UI displays the scaledown delay second if a replicaset is scheduled to be scaled down.

# Use Cases

When would you use this?

Some useful information for user to understand the replicaset status.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by schakrad** [comment]
The delay button is added on the dashboard to display the scaleDownDelay associated with the scaled down revision.
