### ISSUE TITLE
Create Experiments Healthcheck in Argo CD

### ISSUE THREAD

**Issue by dthomson25** [argoproj/argo-rollouts#136]
In order to integrate with Argo CD, the experiment CRD needs to have a Lua health check in Argo CD. The experiment should have these health statuses in the following situations:

Degraded:
- When the experiment has pasted the progessingDeadlineSeconds
Processing:
- The status.AvailableAt field is nil
Healthy:
- The status.AvailableAt field is not nil

**Comment by jessesuen** [comment]
Probably should move this bug into Argo CD

**Comment by dthomson25** [comment]
Fixed by https://github.com/argoproj/argo-cd/pull/2579
