### ISSUE TITLE
Option to abort when exceeding progressDeadlineSeconds

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#1376]
# Summary

Currently, we only automatically abort an update if analysis fails. But if analysis is not used and a rollout exceeds progressDeadlineSeconds (e.g. because the new pods don't become ready/available or CrashLoopBackoff), the user should have an option to also automatically abort and rollback in this scenario.

# Use Cases

I want automated aborts but do not use analysis, or I want automated abort to complement analysis.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by huikang** [comment]
Hi, @jessesuen , I can work on this. Please assign it to me. Thanks.
