### ISSUE TITLE
Experiment CRD documentation

### ISSUE THREAD

**Issue by dthomson25** [argoproj/argo-rollouts#138]
The documentation needs to be updated in order to include information on Experiments.
Docs should include:
- What is the experiment CRD?
- What is its use case?
- Why create another CRD for experiments?
- How to use experiments? All the different configuration options
- Rollouts and Experiments integration

**Comment by kishorenc** [comment]
@dthomson25 I've been exploring the Experiment CRD, and had a question which the [existing documentation](https://argoproj.github.io/argo-rollouts/experiments/) is not very clear about: 

Do we need to have the entire deployment spec (e.g. container image, environment variables, etc.) in the experiment manifest file or just the fields that we want to be changed in the experiment?

It would be really cool if we can define just the changes that we need on an existing deployment on the experiment YAML manifest (e.g. using a new container image) and let the CRD fetch+clone the other fields from an existing deployment referenced by `selector.matchLabels`.
