### ISSUE TITLE
Status command returns incorrect output with --watch=true flag once the status changes

### ISSUE THREAD

**Issue by tsurankov** [argoproj/argo-rollouts#1390]
## Summary 

The main problem is that the status command used with --watch=true or --timeout flags (which is default behaviour) returns the result 'Progressing - active service cutover pending' even if the status has changed to Paused - BlueGreenPause. If I run it for the second time just after and the status is already Pause, I am getting the correct response.

In the following example, the preview replica set becomes healthy after 1.5 minutes. If I run the command in another terminal window with the flag --watch=false, I see that the status is 'Pause', however, the main process reaches timeout and fails. 
I have also noticed that there are always no more that 3-4 status updates. Does this mean that in the following example there were only 3 checks within 6 minutes interval? The behaviour is very confusing. How frequent it checks the status and why it doesn't change?
Current behaviour:
```
kubectl-argo-rollouts status example-spring-boot-prod-01 --timeout 6m --namespace test-argo-prod --watch=true
Progressing - active service cutover pending
Progressing - active service cutover pending
Progressing - active service cutover pending
Error: Rollout progress exceeded timeout  #after 6 minutes

kubectl-argo-rollouts status example-spring-boot-prod-01 --timeout 6m --namespace test-argo-prod --watch=true
Paused - BlueGreenPause
```
Expected behaviour:
```
kubectl-argo-rollouts status example-spring-boot-prod-01 --timeout 6m --namespace test-argo-prod --watch=true
Progressing - active service cutover pending
Paused - BlueGreenPause                   #as soon as the status changes
```

## Diagnostics

What version of Argo Rollouts are you running?
1.0.4

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by huikang** [comment]
@tsurankov , could you try this PR https://github.com/argoproj/argo-rollouts/pull/1433; it might resolve this issue? Also I think the reason you see 3-4 status updates is due to duplicated events being filtered. Thanks.

**Comment by jessesuen** [comment]
Closing as possibly addressed in https://github.com/argoproj/argo-rollouts/pull/1433
