### ISSUE TITLE
Status command output differs depending on the flag is set as --watch=true or --watch=false

### ISSUE THREAD

**Issue by tsurankov** [argoproj/argo-rollouts#1391]
## Summary 

The output of the status command is different if we run status with the --watch flag set to true or false. I am not sure if it was designed in that way, but for me, it is a bit confusing. Let's compare:
```
kubectl-argo-rollouts status example-spring-boot-prod-01 --namespace test-argo-prod --watch=true
Paused - BlueGreenPause
kubectl-argo-rollouts status example-spring-boot-prod-01 --namespace test-argo-prod --watch=false
Paused

kubectl-argo-rollouts status example-spring-boot-prod-01 --namespace test-argo-prod --watch=true
Progressing - active service cutover pending
kubectl-argo-rollouts status example-spring-boot-prod-01 --namespace test-argo-prod --watch=false
Progressing
```
## Diagnostics

What version of Argo Rollouts are you running?
1.0.4

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by huikang** [comment]
Hi, @tsurankov , the [PR](https://github.com/argoproj/argo-rollouts/pull/1433) should resolve this bug; here is some sample output: https://github.com/argoproj/argo-rollouts/pull/1433#issuecomment-918724760
