### ISSUE TITLE
metadata.generation not been updated to match status.observedGeneration

### ISSUE THREAD

**Issue by semoac** [argoproj/argo-rollouts#140]
When a change is made to the Rollout resource, metadata.generation is not updated and always set to `1`.

Ex:
```
kubectl -n argo-test get rollouts example-rollout -o=jsonpath='{"Generation: "} {.metadata.generation}{"\t"}{"observedGeneration: "}{.status.observedGeneration}'
Generation:  1	observedGeneration: 6c98b8764
```

This make difficult to check (with other tools like `kubernetes-deploy`) the state of the object.

**Comment by 16yuki0702** [comment]
Is this already fixed?
When I did the same command, I got different result.
```
$ kubectl get rollouts example-rollout -o=jsonpath='{"Generation: "} {.metadata.generation}{"\t"}{"observedGeneration: "}{.status.observedGeneration}'
Generation:  1702	observedGeneration: b4f665db8
```

Maybe this is the code.
https://github.com/argoproj/argo-rollouts/blob/master/rollout/sync.go#L469

**Comment by jessesuen** [comment]
metadata.generation is controlled by kubernetes API server (and not controllers). I recall that it was updated properly in CRDs for all k8s versions. I think this can be closed as a k8s problem with older versions.
