### ISSUE TITLE
AWS AppMesh support

### ISSUE THREAD

**Issue by AhmadMS1988** [argoproj/argo-rollouts#1401]
Hi
Just wanted to ask if I can achieve progressive deployments on App Mesh with Argo rollouts, and if yes, is there any guide for that?
If it is still not supported, is it possible and safe to use Argo ecosystem with Flagger instead?
Thanks a lot.

**Comment by jessesuen** [comment]
Argo Rollouts does not currently have App Mesh support, but it's definitely something we'd like to support. Introducing support for new mesh/ingress controllers has been fairly straight forward, if you understand how to develop using the K8s golang client and API's. In fact, most of our ingress/mesh support has been contributed by our community.

Yes, it is perfectly safe to use Argo CD with Flagger Canary objects. But unlike Rollouts, there is not same level of integration between the products. For example, Rollout health is assessed by Argo CD, Rollouts can be promoted from Argo CD UI and CLI, and we are also working on Argo CD UI extensions to visualize rollouts better in the UI.

**Comment by jessesuen** [comment]
Fixed in https://github.com/argoproj/argo-rollouts/pull/1606 (Rollouts v1.2.0)
