### ISSUE TITLE
Missing docker image tags corresponding to github tags for argo rollouts controller

### ISSUE THREAD

**Issue by aajimal** [argoproj/argo-rollouts#1408]
# Summary

There are a number of release tags that have been pushed in github since v0.10.2 (currently v1.0.4 is the latest). However, there are no docker tags on DockerHub which correspond to these releases. There should be a docker image of the controller for all git tags.

# Use Cases

When someone wants to track a specific version release of argo rollouts that specific version of the controller is also what the user intends and expects to track.

**Comment by alexmt** [comment]
Hello @aajimal ,

Argoproj has switched to https://quay.io due to rate limits introduced to Dockerhub. You can find new rollout image tags here:  https://quay.io/repository/argoproj/argo-rollouts?tab=tags
