### ISSUE TITLE
skip canary steps and auto promote incase stable pods are in failed state

### ISSUE THREAD

**Issue by harikrongali** [argoproj/argo-rollouts#1416]
# Summary

In a scenario where stable pods are in the failed state due to config changes or dependency failures. Then canary deployment should have an option to skip steps and deploy a new version.
 or either treat canary deployment as a new deployment and should skip steps.

```
strategy:
  canary:
     promoteIfStableUnhealthy: boolean
```
# Use Cases

When would you use this?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by huikang** [comment]
In this case, what if the canary version still fails. Will the controller abort and rollback to the stable version. There seems a loop between the bad stable version and canary version.

**Comment by asimhon** [comment]
> In this case, what if the canary version still fails. Will the controller abort and rollback to the stable version. There seems a loop between the bad stable version and canary version.

This is not what happen today?
In any case for such scenario it requires a user action.
It doesn’t change the fact rollouts should give the option to promote assuming canary is healthy no matter if stable version is bad (think also on analysis - you analyze only canary version and not stable version)

**Comment by huikang** [comment]
> > In this case, what if the canary version still fails. Will the controller abort and rollback to the stable version. There seems a loop between the bad stable version and canary version.
> 
> This is not what happen today?

No, I think in current implementation, if the canary fails and rolls back to the stable, meanwhile some configuration changes, the argo-rollouts controller will leave the stable version in `degraded ` state.

**Comment by jessesuen** [comment]
This is a duplicate request to https://github.com/argoproj/argo-rollouts/issues/1377 so marking it as duplicate there

This is a tricky request, because I don't think it is safe or proper to infer the intention of the user to go straight to canary, when stable ReplicaSet is somehow failed (perhaps only temporarily).
