### ISSUE TITLE
Support for a hook when rollout fails or aborts

### ISSUE THREAD

**Issue by geowalrus4gh** [argoproj/argo-rollouts#1422]
# Summary

Thanks for the great tool Argo Rollouts Rocks. 
Currently, Argo rollouts roll back a version of deployment from new to old when there is an analysis failure or an error. Is it possible to add some hook to run a job when there is such rollback specific to the rollout itself ? . Argo CD hooks and Helm hooks etc are not helpful in this case since those hooks will get applied in any resource error ( sync error). We need to run job only where rollout is aborted or failed.

# Use Cases

Looking for a solution to include a database migration rollback when there is a rollout failure happens. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
Yes, you will be able to configure a hook via the notification feature coming in v1.1 using the web notification.

**Comment by alexmt** [comment]
Adding to v1.2 to document how to configure it.

**Comment by geowalrus4gh** [comment]
Hi, is it possible to trigger a k8s job in the same deployment?

**Comment by yq314** [comment]
Hi guys, it looks like the newly added notification feature only comes with triggers for a successful rollout, any idea on how to configure it for failures (which is more useful in most of cases)

**Comment by jessesuen** [comment]
PR https://github.com/argoproj/argo-rollouts/pull/1753/files adds support for `RolloutAborted` event (requested in this issue). The PR can be examined as an example for adding your own templates and notification for events.

**Comment by real-zony** [comment]
As @yq314  mentioned, we also encountered a similar issue and would like to execute a specific kubernetes job when Rollouts fail or have it execute like `postPromotionAnalysis` in case of a failure.
