### ISSUE TITLE
Bluegreen Rollout stuck in status: Progressing with message: more replicas need to be updated

### ISSUE THREAD

**Issue by shrey-183** [argoproj/argo-rollouts#1431]
## Summary 

What happened/what you expected to happen?

I am testing out an example of blue-green rollout from the docs. Here is the manifest:
https://github.com/argoproj/argo-rollouts/blob/master/examples/rollout-bluegreen.yaml

I expect to replicas being created, however nothing seems to be working here. 

## Diagnostics

What version of Argo Rollouts are you running?

kubectl-argo-rollouts: v1.0.4+c63b6c1
  BuildDate: 2021-08-03T02:45:09Z
  GitCommit: c63b6c1f5134a9f19caae37765f1a8a145f62d7d
  GitTreeState: clean
  GoVersion: go1.16.3
  Compiler: gc
  Platform: linux/amd64

# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

This is the output I get after running the above command:

Error from server (NotFound): deployments.apps "argo-rollouts" not found

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>

This is the output I get after running the above command:

Error from server (NotFound): deployments.apps "argo-rollouts" not found

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by harikrongali** [comment]
@shrey-183 you need to run argo rollouts  on your minikube/k3d if it is local or in your cluster. Please follow the steps in https://argoproj.github.io/argo-rollouts/installation/

**Comment by shrey-183** [comment]
@harikrongali thanks for your reply, I am currently running argo-rollouts on openshift 4 cluster. I have tried following the installation steps, however when I run the command `kubectl apply -n argo-rollouts -f https://github.com/argoproj/argo-rollouts/releases/latest/download/install.yaml`, nothing happens, the terminal just freezes for me. Don't really know why this is happening though?

**Comment by jessesuen** [comment]
The following error indicates that rollouts is not even installed in your cluster:

```
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=

Error from server (NotFound): deployments.apps "argo-rollouts" not found
```

> I have tried following the installation steps, however when I run the command kubectl apply -n argo-rollouts -f https://github.com/argoproj/argo-rollouts/releases/latest/download/install.yaml, nothing happens, the terminal just freezes for me. Don't really know why this is happening though?

Seems like you have something more fundamentally wrong in your environment if you can't kubectl apply manifests without the command hanging. That would not be a rollout issue. Can you apply anything? Does this work?

```
kubectl apply -f https://k8s.io/examples/controllers/nginx-deployment.yaml
```

**Comment by shrey-183** [comment]
> Seems like you have something more fundamentally wrong in your environment if you can't kubectl apply manifests without the command hanging. That would not be a rollout issue. Can you apply anything? Does this work?
> 
> ```
> kubectl apply -f https://k8s.io/examples/controllers/nginx-deployment.yaml
> ```

I tried to run the above command and I get,
```
deployment.apps/nginx-deployment created
```
And here is what I get after running `kubectl get all` 
```
NAME                                    READY     STATUS             RESTARTS   AGE
pod/nginx-deployment-66b6c48dd5-678r9   0/1       CrashLoopBackOff   3          66s
pod/nginx-deployment-66b6c48dd5-ffhwb   0/1       CrashLoopBackOff   3          67s
pod/nginx-deployment-66b6c48dd5-h4tgc   0/1       CrashLoopBackOff   3          66s

NAME                                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
service/rollout-bluegreen-active    ClusterIP   172.30.238.216   <none>        80/TCP    44h
service/rollout-bluegreen-preview   ClusterIP   172.30.230.21    <none>        80/TCP    44h

NAME                               READY     UP-TO-DATE   AVAILABLE   AGE
deployment.apps/nginx-deployment   0/3       3            0           67s

NAME                                          DESIRED   CURRENT   READY     AGE
replicaset.apps/nginx-deployment-66b6c48dd5   3         3         0         67s
```

Not sure why the pod go into a crashloopbackoff state. Is this supposed to happen?

**Comment by huikang** [comment]
The CrashLoopBackOff is due to the failure of the nginx pod, which is beyond control of the argo-rollouts controller.
Does you template work with `kind: deployment`?

**Comment by jessesuen** [comment]
> Does you template work with kind: deployment?

It doesn't. I asked to run the basic Kubernetes nginx deployment in the tutorial, which fails with:

```
2021/08/21 09:09:02 [emerg] 1#1: mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
```


This is definitely an environmental issue since a basic nginx Deployment is unable to run, and the Rollout controller does not appear to be running.

**Comment by shrey-183** [comment]
I re-installed the controller and now everything works. Thanks for your comments!
