### ISSUE TITLE
Dashboard - Field overflow

### ISSUE THREAD

**Issue by lucaskenda** [argoproj/argo-rollouts#1434]
## Summary 

If the image name is too long i get an overflow:

![image](https://user-images.githubusercontent.com/4048688/130133602-96afa1af-16ba-42a1-b7c7-696bdfa51933.png)

## Diagnostics

I'm using kubectl-argos-rollout latest version (v1.1.0).
The problem is here, the class has a fixed width of 400px, It could be changed for min-width to avoid this bug.

```
.rollout__info {
    width: 400px;
    margin-right: 15px;
}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by rbreeze** [comment]
This was fixed in Argo UI in this commit: https://github.com/argoproj/argo-ui/commit/1743b4246c414ff397aca37f48ee7776a73f2f21

I'll open a PR to bump the Argo UI version in the Rollouts Dashboard
