### ISSUE TITLE
Gateway API support for Argo rollouts

### ISSUE THREAD

**Issue by mark-church** [argoproj/argo-rollouts#1438]
[Gateway API](https://gateway-api.sigs.k8s.io/) is a standard out of SIG-Network that evolves the ingress interface with more advanced capabilities such as weight-based load balancing. There are already many [Gateway API implementations](https://gateway-api.sigs.k8s.io/implementations/) that exist including Kong, Traefik, Istio, GKE, and more. This tutorial shows how [traffic splitting](https://gateway-api.sigs.k8s.io/v1alpha1/guides/traffic-splitting/) works in Gateway. 

This issue is to propose Gateway API-based support for Argo rollouts so that any Gateway API implementation can be used with Argo in the same way. 

cc @bowei @robscott

**Comment by jessesuen** [comment]
As with our support for SMI, this makes perfect sense to me, and would help to alleviate the many direct integration requests that we often get.

**Comment by PhilippPlotnikov** [comment]
I would like to implement it

**Comment by alexmt** [comment]
Thank you @PhilippPlotnikov

**Comment by mainey** [comment]
would it be possible to support KrakenD api gateway for argo rollouts as well?

**Comment by object88** [comment]
My apologies if "me too"s aren't appropriate for issues here, but we (Dexcare) are very interested in a Gateway API implementation in Argo Rollouts.  @PhilippPlotnikov , is there a way that we can track progress on this?  I may be able to contribute some testing time in our development environment.

**Comment by PhilippPlotnikov** [comment]
@object88 yes, of course https://github.com/argoproj/argo-rollouts/pull/2004. Here I have made the support but without tests and rbac permissions, Im in process. I tested locally it works.

**Comment by PhilippPlotnikov** [comment]
I have finished PR with Gateway API support, can someone review it please ?
https://github.com/argoproj/argo-rollouts/pull/2004

**Comment by PhilippPlotnikov** [comment]
Hi, I have implemented Gateway API plugin, you can try to test it
https://github.com/argoproj-labs/rollouts-gatewayapi-trafficrouter-plugin

**Comment by robscott** [comment]
This is great @PhilippPlotnikov, thanks! Would welcome a PR to reference this on Gateway API's documentation: https://gateway-api.sigs.k8s.io/implementations/#integration-status.

**Comment by PhilippPlotnikov** [comment]
@robscott hi! Sure, I will try to create PR on the next week

**Comment by kostis-codefresh** [comment]
@robscott PR is here https://github.com/kubernetes-sigs/gateway-api/pull/1836

**Comment by kostis-codefresh** [comment]
@zachaller 

We have now tested three independent implementations for Gateway API and they all work just fine with the plugin

* [Traefik](https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/tree/main/examples/traefik)
* [Google Cloud](https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/tree/main/examples/google-cloud)
* [Kong](https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/tree/main/examples/kong)

I suggest we mark this issue as closed.

**Comment by zachaller** [comment]
Closing because it is implemented as a plugin
