### ISSUE TITLE
Ability to restart pods while skipping pause/steps

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#144]
Similar to deployment's ability to restart pods using an annotation (https://github.com/kubernetes/kubernetes/pull/76062), Rollouts needs to support this as well.

Technically, Rollouts already supports this, as long as:
* there is no pause before blue-green (`spec.strategy.blueGreen.autoPromotionEnabled: false`)
* there are no canary steps (`spec.strategy.canary.steps`)

But because Rollouts has the ability/concept to pause & run steps, which the Deployment resource does not have, it has a problem where users want to trigger a pod restart but without going through the pause/steps.

**Comment by jessesuen** [comment]
I think the solution to this may be the following: in order to signal to the controller that pods should be restarted while skipping canary steps & blue-green pause, the user action should be to set a timestamp annotation at both the template level and at the rollout level. i.e.

```yaml
metadata:
  annotations:
    rollout.argoproj.io/restartedAt: 2019-10-11T01:02:03
 spec:
  template:
    metadata:
      annotations:
        rollout.argoproj.io/restartedAt: 2019-10-11T01:02:03
```

The logic in the controller would be:
1. if current pod template hash is ever different than the replicaset's pod template hash, we know we need to redeploy (no change to current logic)
2. when deciding whether or not to skip canary steps and the blue-green pause, first examine `rollout.argoproj.io/restartedAt` at both `metadata.annotations` and `spec.template.metadata.annotations`
3. if the values of those two are identical, then this is detected as a pod restart event and we will decide to skip steps or the blue-green pause.
4. when creating the new replicaset for the pod restart, inject a permanent indicator `rollout.argoproj.io/autopromote: "true"` into the replicaset annotations.
5. for every reconcile going forward, if we see ever see `rollout.argoproj.io/autopromote: "true"` in the annotations of a replicaset, we will always skip steps and the blue-green pause

**Comment by carlosdoordash** [comment]
Using this solution means modifying the rollout spec. Doesn't that mean that we lose the ability to quickly rollback to a non-scaled-down replicaset by just patching the container image?

**Comment by jessesuen** [comment]
If we are going back to a blue-green replicaset within its scale-down delay, or back to the "stable" hash of a canary replicaset, this is considered a fast-tracked rollback and the steps are skipped. This ability will not be lost with this feature.

**Comment by jessesuen** [comment]
I'm not really happy with any of my proposed solutions. I think this needs to be treated more first class, instead restarting Rollouts by using an annotations in `spec.template.metadata.annotations`, my current thought is to introduce a `restartAt` timestamp in the rollout spec:

```yaml
spec:
  restartAt: 2020-01-28T02:23:27Z
```

A request to restart a rollout would not involve modifying `spec.template.metadata` at all. Instead, the action to restart a rollout would be to set `spec.restartedAt` to be the current timestamp. The logic would then be:

1. look at all active rollout replicasets which are scaled up
2. verify that all active replicasets have a creationTimestamp **after** this timestamp
3. if an active replicaset is older than the `restartedAt` timestamp, it needs to be restarted
4. to facilitate the restart, we would create a new replicaset but leverage the collision counter when calculating the pod template hash
5. somehow ensure we do a rolling update (and not a canary or blue-green) to perform the restart

A corner case is how to handle the following:
1. Deploy A
2. Deploy B
3. Restart rollout
4. Deploy A (not rollback)

The above would cause us to create a new ReplicaSet which is identical to A (but different in pod-template-hash), as opposed to re-using the existing replicaset. I think is OK, but will need to think this through.

Another corner case is how to handle the case where a rollout is mid-upgrade (e.g. it is paused at a canary step with a 50% weight), and a restart is requested. I think we should somehow facilitate rolling updates of the canary and stable.


Note that this implementation/proposal would also enable an interesting use case where an Argo Rollout could be scheduled to be restarted at a time in the future.

**Comment by jessesuen** [comment]
Worked this through with @dthomson25 and introducing `spec.restartAt` seems like the best approach. However, we do not think it will be possible to do some of the requirements:

1. 
> somehow ensure we do a rolling update (and not a canary or blue-green), and skipping steps to the new replicasets to perform the restart

For the blue-green strategy, we will still need to restack a fully scaled-up replacement replicaset. This is because there will be a different rollout-pod-template-hash label that the active service needs to select on, and we can only update this once the new stack is fully scaled up. This is also the reason why the canary strategy used with trafficRouting also needs to fully scale up the replacement pods, because the new pod-hash values needs to be updated in the service mesh objects (e.g. VirtualService) and this can only be done when replacement pods are ready.

2. 
> handle the case where a rollout is mid-upgrade (e.g. it is paused at a canary step with a 50% weight), and a restart is requested. I think we should somehow facilitate rolling updates of both the canary and stable.

To simplify the implementation, we will be treating a "restart" of a rollout as equivalent to a pod spec change, but skipping pause/steps/analysis. This means that if a rollout was mid rollout, and `restartAt` was set, then it will fully rollout to the new desired version.

**Comment by carlosdoordash** [comment]
Could a restart be implemented to only replace the pods in the existing ReplicaSets maybe by additionally specifying a RollingRestart strategy with similar parameters to the Deployment RolingUpgrade strategy?

**Comment by dthomson25** [comment]
@carlosdoordash only replace the pods in the existing ReplicaSets would significantly increase the scope of this feature. While that in itself has its own implementation challenges, the real complications come when the pod spec is changed during a rolling restart. I'm concerns with all the different edges cases we would have to handle. If we reuse the existing strategies, we have a changing pod spec use case already handled.

**Comment by arkentos** [comment]
@jessesuen / @dthomson25 Is there an expected ETA on the fix?
