### ISSUE TITLE
Add support of centralized dashboard which will have access to all namespaces

### ISSUE THREAD

**Issue by gartemiev** [argoproj/argo-rollouts#1447]
Currenly argo-rollouts supports dashboard per namespace only. 
This is not convenient since We have applications in different namespaces. 
Is it possible to add a feature that will enable dashboard support for multiple namespaces from one single namespace like for example Grafana dashboards in Prometheus operator which have access to all namespaces in EKS cluster?

**Comment by gartemiev** [comment]
@jessesuen, could you please provide with any update on this and when it will be implemented?

**Comment by bpoland** [comment]
My previous comment was incorrect, it's working fine in master images.  It should be in 1.1 whenever that gets released.

**Comment by gartemiev** [comment]
@bpoland , when 1.1 be released?

**Comment by bpoland** [comment]
Good question, I'd like to know as well :)

**Comment by bpoland** [comment]
@cikupin I think something's off with your setup, my dashboard shows v1.1.0 and allows me to select the namespace
