### ISSUE TITLE
argo-rollouts uses :latest image tag for tagged versions

### ISSUE THREAD

**Issue by sigi4** [argoproj/argo-rollouts#1456]
## Summary 
I'm using kustomize to reference a specific argo-rollouts version like v1.0.2 and discovered that due to some image cache issue, that my argo-rollout broke.

I'm not sure but this looks wrong: https://github.com/argoproj/argo-rollouts/blob/v1.0.6/manifests/base/kustomization.yaml 

It would be great to pin the docker image when referencing argo-rollouts through kustomize. When the :latest image broke, i set the deployment image tag manually to v1.0.2 and it fixed my issue.

Tx,

Sigi

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by alexmt** [comment]
Project switched to another way of delivering installation manifests. Now each rollout release have install.yaml attached. E.g. https://github.com/argoproj/argo-rollouts/releases/download/v1.0.6/install.yaml

**Comment by jessesuen** [comment]
Correct. The argoproj projects should switch to install manifests as release artifacts. Events looks like the only one left to do and I filed an issue for it. https://github.com/argoproj/argo-events/issues/1326
