### ISSUE TITLE
Dashboard - no weight for Experiment step, unable to promote

### ISSUE THREAD

**Issue by khhirani** [argoproj/argo-rollouts#1463]
## Summary 

The Argo Rollouts Dashboard doesn't show the necessary information for the experiment step in canary strategy, like `weight`. It would also be nice to see whether the experiment references the `stable` or `canary` stack.

It's also not possible to promote the rollout during an experiment step. 

<img width="1440" alt="Screen Shot 2021-09-01 at 5 41 55 PM" src="https://user-images.githubusercontent.com/16888243/131764045-91671739-147e-43e2-8be3-a908f63a912d.png">

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by schakrad** [comment]
I would like to work on this task.
