### ISSUE TITLE
Analysis with Prometheus - reflect: slice index out of range

### ISSUE THREAD

**Issue by shahafy-ma** [argoproj/argo-rollouts#1466]
## Summary 

I am using AnalysisTemplate with Prometheus query, whenever the result is empty I am getting `"reflect: slice index out of range"` and the AnalysisRun is failing with RolloutAborted. I would expect to have the ability to deal with this result

## Diagnostics

What version of Argo Rollouts are you running?
`v1.0.0`

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
Yes this would be a bug

**Comment by huikang** [comment]
Hey, @jessesuen , I can pic this up if no one is on it. Thanks.

**Comment by alexmt** [comment]
@jessesuen , @huikang just want to clairify. Is rollout should not be aborted in this case or we need to improve error message?

**Comment by huikang** [comment]
@alexmt , shall we consider missing data as failed analysis run?

**Comment by shahafy-ma** [comment]
IMHO, we should
1. Improve the log
2. Having the ability to mark the rollout as fail/success, similar to the isNaN() function.

What do you think?

**Comment by huikang** [comment]
@shahafy-ma , agreed with your first point: we need to update the message in the analysisrun status, which shows `reflect: slice index out of range` currently.

```
status:
  message: 'metric "success-rate" assessed Error due to consecutiveErrors (5) > consecutiveErrorLimit
    (4): "Error Message: reflect: slice index out of range"'
  metricResults:
  - consecutiveError: 5
    error: 5
    measurements:
    - finishedAt: "2021-09-07T04:16:44Z"
      message: 'reflect: slice index out of range'
      phase: Error
      startedAt: "2021-09-07T04:16:44Z"

```

Regarding your second point, the current implementation marks the the update as failed and will rollout back to the stable version. Anything wrong with this behavior?

**Comment by huikang** [comment]
Hi, @jessesuen @alexmt , after some investigation, I found that the root cause is that the expr failed to resolve `result[0]` when the `resultValue ` is an empty array.

https://github.com/argoproj/argo-rollouts/blob/ba9af78cff78486f9a5fe775b78354c745b2d6d3/utils/evaluate/evaluate.go#L83

I couldn't find any error handler method from `github.com/antonmedv/expr`. Other than adding some logic to parse such error,  do you have any idea or suggestion? Thanks.

**Comment by jessesuen** [comment]
Can this be worked around by checking `result == null || result[0] > 1234` ? If so, perhaps this is not a bug and we should document this.

**Comment by huikang** [comment]
>Can this be worked around by checking result == null || result[0] > 1234 ? If so, perhaps this is not a bug and we should document this.

Hi, @jessesuen , setting `result == null || result[0] > 1234 ` in the analysis template results in the following error 

```
status:
  metricResults:
  - consecutiveError: 3
    error: 3
    measurements:
    - finishedAt: "2021-09-07T20:41:01Z"
      message: unknown name null
      phase: Error
      startedAt: "2021-09-07T20:41:01Z"
    - finishedAt: "2021-09-07T20:41:11Z"
      message: unknown name null
      phase: Error
      startedAt: "2021-09-07T20:41:11Z"
    - finishedAt: "2021-09-07T20:41:21Z"
      message: unknown name null
      phase: Error
      startedAt: "2021-09-07T20:41:21Z"

```

**Comment by jessesuen** [comment]
Sorry the correct literal is `nil` not `null`? Does `result == nil || result[0] > 1234` work?

**Comment by huikang** [comment]
> Sorry the correct literal is `nil` not `null`. Does `result == nil || result[0] > 1234` work?

No, same error. It looks the expr package can't interpret `result == nil`

```
status:
  metricResults:
  - consecutiveError: 2
    error: 2
    measurements:
    - finishedAt: "2021-09-08T19:09:29Z"
      message: 'reflect: slice index out of range'
      phase: Error
      startedAt: "2021-09-08T19:09:29Z"
```

**Comment by huikang** [comment]
Hi, @jessesuen , this one works
`len(result) == 0 || result[0] > 1234`. I will send a PR to update the doc. Thanks for your suggestions.

**Comment by shahafy-ma** [comment]
Amazing job guys.
Your doing is very appreciated.

**Comment by ju187** [comment]
I still getting this bug. Argo rollout version is 1.2

**Comment by Bunny15738** [comment]
Hi @huikang it works but not always kindly refer below

successCondition: 'len(result) == 0 || result[0] >= 0.9'
  terminate: true
status:
  dryRunSummary: {}
  message: Run Terminated
  metricResults:
    - count: 5
      failed: 1
      measurements:
        - finishedAt: '2024-01-15T08:58:41Z'
          phase: Successful
          startedAt: '2024-01-15T08:58:41Z'
          value: '[]'
        - finishedAt: '2024-01-15T08:59:41Z'
          phase: Successful
          startedAt: '2024-01-15T08:59:41Z'
          value: '[]'
        - finishedAt: '2024-01-15T09:00:41Z'
          phase: Successful
          startedAt: '2024-01-15T09:00:41Z'
          value: '[1]'
        - finishedAt: '2024-01-15T09:01:41Z'
          phase: Successful
          startedAt: '2024-01-15T09:01:41Z'
          value: '[1]'
        - finishedAt: '2024-01-15T09:02:41Z'
          phase: Failed
          startedAt: '2024-01-15T09:02:41Z'
          value: '[NaN]'
