### ISSUE TITLE
promote error

### ISSUE THREAD

**Issue by 13567436138** [argoproj/argo-rollouts#1487]
## Summary 

What happened/what you expected to happen?
[root@node01 ~]# kubectl argo rollouts promote reviews-v1 -n istio
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17bfbfd]

goroutine 1 [running]:
github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/cmd/promote.getPatches(0xc000b79200, 0x2000000, 0xc0000520c8, 0x7ffeaa3e9714, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/cmd/promote/promote.go:168 +0x37d
github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/cmd/promote.PromoteRollout(0x26ca978, 0xc00034b160, 0x7ffeaa3e9714, 0xa, 0xc000000000, 0xc000196400, 0xc00091fd38, 0x1c8071f)
        /go/src/github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/cmd/promote/promote.go:113 +0x11d
github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/cmd/promote.NewCmdPromote.func1(0xc000198840, 0xc000163260, 0x1, 0x3, 0x0, 0x0)
        /go/src/github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/cmd/promote/promote.go:68 +0x13b
github.com/spf13/cobra.(*Command).execute(0xc000198840, 0xc000163230, 0x3, 0x3, 0xc000198840, 0xc000163230)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc00013e840, 0xc00013e840, 0x2679840, 0xc00000e020)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main()
        /go/src/github.com/argoproj/argo-rollouts/cmd/kubectl-argo-rollouts/main.go:21 +0xc5
## Diagnostics

What version of Argo Rollouts are you running?
1.30
```
# Paste the logs from the rollout controller
istio
# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by harikrongali** [comment]
assigning to @leoluz

**Comment by leoluz** [comment]
@13567436138 Can you please confirm a few things?
 
 Which argo-rollouts version are you running? You answered 1.30 but it might be a mistake as the current stable version is 1.0.6

Can you please share your Rollouts yaml (removing sensitive information) so we can verify how it is configured to run?

**Comment by 13567436138** [comment]
[root@node01 ~]# kubectl argo rollouts version
kubectl-argo-rollouts: v1.0.6+5b332f6
  BuildDate: 2021-08-26T06:28:26Z
  GitCommit: 5b332f6bb76f6399bbc26067caa9a28c59f2bade
  GitTreeState: clean
  GoVersion: go1.16.3
  Compiler: gc
  Platform: linux/amd64
[root@node01 ~]#

**Comment by 13567436138** [comment]
I forget which yaml I used

**Comment by 13567436138** [comment]
and I can not reproduce it
