### ISSUE TITLE
docs: Getting Started is missing a link

### ISSUE THREAD

**Issue by oke-py** [argoproj/argo-rollouts#150]
There is a broken link in [Converting Deployment to Rollout](https://argoproj.github.io/argo-rollouts/getting-started/#converting-deployment-to-rollout) in Getting Started document.

> [Argo Rollouts section](spec/index.md

Only a closing bracket is needed? However, I couldn't find the target document.

**Comment by jessesuen** [comment]
Thanks for reporting. Fixed in https://github.com/argoproj/argo-rollouts/commit/89a98dcd5cf1a3fa6040b64be9164a0b348a710c
