### ISSUE TITLE
Visualize Analysis Measurements in Rollouts Dashboard

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-rollouts#1506]
# Summary

Dashboard visualizes analysis runs but there is no way to see measurements details.

![image](https://user-images.githubusercontent.com/426437/133140128-7ac72c05-0f62-4749-8f4a-5993008d4d57.png)

# Use Cases

Dashboard should get measurements visualization so that user can understand why analysis failed/succeded.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by rohitdumbre86** [comment]
@alexmt I would like to tackle this issue.

**Comment by alexmt** [comment]
Thank you @rohitdumbre86 ! 

Since it is a UI task I would suggest creating a mockup and discuss it in issue before implementing. @rbreeze might have a suggestion about how the visualization should look like

**Comment by schakrad** [comment]
I would like to work on this UI task.

**Comment by harikrongali** [comment]
https://github.com/argoproj/argo-rollouts/pull/1910 fixes the issue
