### ISSUE TITLE
Add age to `AnalysisRun` printer columns

### ISSUE THREAD

**Issue by yashmehrotra** [argoproj/argo-rollouts#1511]
# Summary

Add an `AGE` parameter to `AnalysisRun` printer columns for ease of viewing

# Use Cases

When debugging why a canary rolled back, doing a `kubectl get` of AnalysisRun returns just the name and status. While the name being composed of the replicaset makes things easier, I found that adding the Age parameter helps tremendously.

The only change we need to make is to add this to the `additonalPrinterColumns` in the CRD

```
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
```
 If you are interested in having this change, I'd love to contribute 😄 

I added this in my cluster's deployment and it helped the team a lot. This is how it looks:

![image](https://user-images.githubusercontent.com/5863972/133417144-e63304d2-d01b-440a-b408-caf642196bd1.png)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by huikang** [comment]
Sounds a good idea. @yashmehrotra , could you send a PR to enable this? Thanks.

**Comment by yashmehrotra** [comment]
@huikang Awesome, I'll create a PR for this, I hope it is fine if I do it for all the CRDs:

- analysisruns.argoproj.io
- analysistemplates.argoproj.io
- clusteranalysistemplates.argoproj.io
- experiments.argoproj.io
- rollouts.argoproj.io

**Comment by yashmehrotra** [comment]
@huikang Have created a PR: https://github.com/argoproj/argo-rollouts/pull/1527

Please take a look
