### ISSUE TITLE
Flaky e2e tests

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-rollouts#1516]
## Summary 

We've accumulated several flaky e2e tests that fail CI frequently. Creating a ticket to address it. The list below contains known flaky tests, more tests will be added during 

* TestAnalysisSuite/TestCanaryInlineMultipleAnalysis
* TestAnalysisSuite/TestBackgroundAnalysisWithArgs

**Comment by kostis-codefresh** [comment]
Already reported as https://github.com/argoproj/argo-rollouts/issues/1200

**Comment by alexmt** [comment]
Thank you @kostis-codefresh ! Closing duplicate
