### ISSUE TITLE
Publish the docs for the latest release instead of master

### ISSUE THREAD

**Issue by cooperbenson-qz** [argoproj/argo-rollouts#1518]
# Summary

The [project documentation](https://argoproj.github.io/argo-rollouts/) should be built from the most recent release instead of master or default to displaying the most recent release and allow users to switch to the master version.

# Use Cases

Right now the publically published documentation is built from the master branch, which means it contains documentation for unreleased features. This is extremely confusing for users who can spend hours attempting to use (and then subsequently debug) a missing feature (e.g. #1305). It's very surprising to have a stable project include documentation for unreleased features on its homepage. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
Agree 100%. We need to do what Argo CD did and use readthedocs to version the docs per branch https://github.com/argoproj/argo-cd/pull/5099

**Comment by kostis-codefresh** [comment]
I added a first PR https://github.com/argoproj/argo-rollouts/pull/1528 to implement readthedocs building (before actually adding the selector of the versions)

Current result is at https://argo-rollouts.readthedocs.io/en/readthedocs/

**Comment by kostis-codefresh** [comment]
I added another PR https://github.com/argoproj/argo-rollouts/pull/1671 for the selector of versions.

Here is how it looks https://argo-rollouts.readthedocs.io/en/doc-versioning/

![drop-down](https://user-images.githubusercontent.com/39800303/143446425-803978fe-5d28-4b81-a333-be20bdf5d6d7.png)

Currently it is pointing at my own github repo. But when this is merged I will point readthedocs to the Argoproj repo. 

The previous versions of Argo Rollouts did not have readthedocs support. The first "official" one that will appear on the repo will be 1.2

**Comment by kostis-codefresh** [comment]
@cooperbenson-qz This has been implemented. However since we just added the versioning, only "latest/master" is visible right now. All the next Rollout releases will appear on the drop-down as soon as we release them.
