### ISSUE TITLE
Add a health probe endpoint to the controller

### ISSUE THREAD

**Issue by huikang** [argoproj/argo-rollouts#1522]
# Summary

What change needs making?

Add a health checkpoint like `:8081/healthz` to the controller. Currently we rely on the metrics server for health probe.

https://github.com/argoproj/argo-rollouts/blob/01879e474d7973ced4b963fc19276a594e93bdfc/manifests/base/argo-rollouts-deployment.yaml#L26-L38

# Use Cases

When would you use this?

When HA is enabled, the non-lead instance should not start the metrics server due to incomplete data; only the lead node can report metrics. Therefore, we need to distinguish between metrics listen port and the health probe port.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by huikang** [comment]
After further thought, I think having multiple replicas serving the metrics port won't cause any conflict to the **rollout_info** metrics. Each controller replica, regardless of primary or backup, reads the measurement by reading from collecting rollouts
https://github.com/argoproj/argo-rollouts/blob/7c7774434f437f8706b953aadcfd45e435830510/controller/metrics/rollouts.go#L52-L61

so the measurement from each replica should be consistent.

However, the **rollout_reconcile** and *rollout_reconcile_error* will be different between the primary and the backup ones because the measurement depends the controller's reconciliation: the number of the primary's copy is greater than the backup ones.

So to ensure consistency across replicas, we allow only the primary instance to expose the metrics port, so having the health port is still necessary.

@jessesuen @harikrongali , what do you think?

**Comment by huikang** [comment]
After some further thought on this issue, I think the root cause is that the `reconciliation` metric depends on the pod: each pod of controller will have different measurement. 

So another option of making the deployment progress is to add  some label like `instance_id` to the `reconciliation` metric, as well as a new metric named `is_primary` (1 means it is a primary, 0 means non primary pod). 
Then in the query results we can distinguish between primary and backup pods.

@dbyron-sf , @jessesuen , @harikrongali what do you think?

**Comment by harikrongali** [comment]
1. All pods need to be ready even if secondary
2. Yes, adding instance_id will be good. One thing to add is the ability for metric providers to skip reading events from secondary pods. As load will increase based on the number of pods.
