### ISSUE TITLE
Rollouts Dashboard doesn't fully support using workloadRef

### ISSUE THREAD

**Issue by bpoland** [argoproj/argo-rollouts#1525]
## Summary 

When using a `Rollout` which uses `workloadRef`:
- the "Containers" section is not populated (it just says "Add more containers to fill this space")
- the "Rollback" buttons on previous revisions don't work -- clicking them doesn't do anything

I think either those features should be removed when using `workloadRef`, or they should be updated to work.

## Diagnostics

What version of Argo Rollouts are you running?

Recent master build

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
Ah yes, dashboard needs to be updated to handle workloadRef.

**Comment by derjust** [comment]
This seems to also affect `kubectl argo rollouts set image` as it doesn't find the container.
The only workaround seems to be to alter the deployment itself - Argo then picks it up as expected

**Comment by bpoland** [comment]
> This seems to also affect `kubectl argo rollouts set image` as it doesn't find the container.
> The only workaround seems to be to alter the deployment itself - Argo then picks it up as expected

That feels less surprising to me, although the kubectl plugin should probably provide a helpful error message saying that command isn't supported when using `workloadRef`?

**Comment by jessesuen** [comment]
I thought we [had fixed this already](https://github.com/argoproj/argo-rollouts/pull/1275) in the plugin CLI command, but it appears we only fixed the `undo` command for workloadRef and not the `set image` for workloadRefs.

If anyone wants to take a stab at this, the `undo` fix in  https://github.com/argoproj/argo-rollouts/pull/1275 is a good example of how it can be fixed in the same way for `set image`

**Comment by jessesuen** [comment]
Actually let me spawn a separate issue for plugin work so that it can be worked on independently from dashboard.

**Comment by jessesuen** [comment]
I think only the containers section needs to be fixed. Here is how it looks when using workloadRef.

![image](https://user-images.githubusercontent.com/12677113/150070837-048549cc-686e-4ad1-b0d0-9bd69a73a791.png)

However, the Rollback feature seems to be working for me when using workloadRef.

**Comment by bpoland** [comment]
> However, the Rollback feature seems to be working for me when using workloadRef.

Hmm alright, it's possible that has been fixed since I originally tried 🤷

**Comment by S0n98** [comment]
I'm suffering this problem when using workload ref:
`the "Rollback" buttons on previous revisions don't work -- clicking them doesn't do anything`
This function only works when I place pod template directly in Rollout spec.template

**Comment by S0n98** [comment]
I'm suffering this problem when using `workloadRef`:
 
> * the "Rollback" buttons on previous revisions don't work -- clicking them doesn't do anything
 
This function only works when I place pod template directly in Rollout spec.template
