### ISSUE TITLE
Re-enable pushes to ghcr.io 

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#1531]
## Summary 

I recently disabled pushes to ghcr.io because of unknown 403 failures:
https://github.com/argoproj/argo-rollouts/pull/1530

There may be some ongoing issue happening recently
https://github.community/t/403-error-on-container-registry-push-from-github-action/173071/38

This issue is to re-enable pushes to ghcr.io once it is all worked out.

Perhaps this is related to CDN issues that have been happening since yesterday:
https://github.com/k3s-io/k3s/issues/4054

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by perenesenko** [comment]
@jessesuen Do we need this?
Enabling image publishing to ghcr.io.

**Comment by perenesenko** [comment]
Talked with @jessesuen about this.
We decided not to enable it
