### ISSUE TITLE
Dashboard: allow direct links to a specific rollout

### ISSUE THREAD

**Issue by bpoland** [argoproj/argo-rollouts#1538]
# Summary

In the rollouts dashboard, you can send a link to `https://rollout.dash.url/rollout/rollout-name` but it seems like the namespace is set via a cookie or local browser storage, so the first time you go to the link it defaults to the namespace where the dashboard is running (I'm using the 1.1 RC so the dashboard has multi-namespace support).  Once the user picks the correct namespace in the dropdown then the above link works, but there doesn't seem to be a way to get them there on the first try.

It would be nice if the namespace could be set directly in the URL.  It would make the most sense to me for the namespace to be added in the path (e.g. something like `/rollout/namespace-name/rollout-name`) but a query parameter would work too (e.g. `/rollout/rollout-name?namespace=namespace-name`).

The main rollouts screen would also need the same functionality so that you could link directly to see all the rollouts in a particular namespace.

If possible, it would also be nice to link straight to a particular search phrase in the main screen -- so something like `/rollouts/namespace-name?q=foo` would take you to the main rollouts summary for the `namespace-name` namespace with `foo` pre-filled in the search box.

# Use Cases

- Linking from other deployment tools straight to the relevant rollout, without needing the user to select the right namespace
- Sharing ad-hoc links with others so they can see the same thing you're looking at

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by harikrongali** [comment]
@perenesenko

**Comment by Cylix** [comment]
Hey folks 👋 

Just to let you know that's something that'd be super useful. For example, being able to have some direct links to the argo-rollouts dashboards in our CI output.

I've crafted a PR (https://github.com/argoproj/argo-rollouts/pull/1902) to add support for this. I'm fairly new to React, so this might need to be reworked a bit, but I'd be happy to put the work to support this!
