### ISSUE TITLE
Dashboard doesn't send client update when a pod terminates

### ISSUE THREAD

**Issue by bpoland** [argoproj/argo-rollouts#1539]
## Summary 

When watching the rollouts dashboard during a canary rollout, the dashboard usually updates automatically as the rollout progresses through the steps.  When a pod starts terminating it updates to show a blue circle box, but when the pod finishes terminating there is no update sent to the client UI.

This is generally not an issue while the rollout is progressing since another update usually comes soon after a pod terminates (e.g. when another pod gets started).  But the last pod to terminate in the old ReplicaSet stays with the blue circle indefinitely, and there's no update when the rollout fully completes.  Refreshing the page manually shows the correct status, but that shouldn't be necessary -- the dashboard should send an update to the client when the pod terminates.

## Diagnostics

Controller + dashboard v1.1.0-rc1

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by perenesenko** [comment]
I will look on this one
