### ISSUE TITLE
Read-only dashboard

### ISSUE THREAD

**Issue by eilonmonday** [argoproj/argo-rollouts#1560]
# Summary

Add read-only permissions for the dashboard

# Use Cases

We would like to give the developers access to the dashboard only for visualization without the ability to click on retry, promote, etc.

Thanks!

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
You can just remove all the write permission from the service account associated with the dashboard.
