### ISSUE TITLE
migrate [apiextensions.k8s.io/v1beta1] to [apiextensions.k8s.io/v1] | unsupported from CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+

### ISSUE THREAD

**Issue by AAATechGuy** [argoproj/argo-rollouts#1565]
# Summary

What change needs making?

`Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition` 
Need to upgrade CRD version. 

![image](https://user-images.githubusercontent.com/3484074/136117322-906e90d9-f054-44e6-a0fd-9cbd411b8b3b.png)

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
We already migrated to v1. But you are installing the old version because you are referencing using the `stable` tag (which is deprecated). We now provide installation manifests attached to the release. See:

https://github.com/argoproj/argo-rollouts/releases/tag/v1.0.0
