### ISSUE TITLE
Dashboard should allow promote/promote-full at any time

### ISSUE THREAD

**Issue by bpoland** [argoproj/argo-rollouts#1581]
# Summary

Currently the rollout dashboard disables the promote and promote-full buttons at certain points (seems to be when scaling canary/setting weight requires pods to be started and become ready).  The CLI options do not have this restriction, so I think the dashboard should also allow promoting at any time.

# Use Cases

When I want to promote/promote-full while pods are starting

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
Yes, this seems reasonable. Promote and promote-full should be available anytime during an update (but not when fully rollouted out at a steady state).

For reference, here is when Argo CD presents them as options (resume is similar to promote in the UI).
https://github.com/argoproj/argo-cd/blob/master/resource_customizations/argoproj.io/Rollout/actions/discovery.lua
