### ISSUE TITLE
No rollout after 1.1.0 Upgrade

### ISSUE THREAD

**Issue by DanTulovsky** [argoproj/argo-rollouts#1587]
## Summary 

I upgraded to version 1.1.0 and now none of the Rollouts work.  They all show an error like:

```
time="2021-10-15T20:21:17Z" level=warning msg="Error updating rollout: rollouts.argoproj.io \"staging-space-station-spanmixer\" not found" generation=325 namespace=staging-space-station resourceVersion=997295647 rollout=staging-space-station-spanmixer
time="2021-10-15T20:21:17Z" level=error msg="roCtx.reconcile err rollouts.argoproj.io \"staging-space-station-spanmixer\" not found" generation=325 namespace=staging-space-station resourceVersion=997295647 rollout=staging-space-station-spanmixer
```
Do i need to clear some stuck state somewhere?

Thank you

## Diagnostics

1.1.0

```
# Paste the logs from the rollout controller

```
time="2021-10-15T20:21:17Z" level=info msg="Started syncing rollout" generation=325 namespace=staging-space-station resourceVersion=997295647 rollout=staging-space-station-spanmixer
time="2021-10-15T20:21:17Z" level=info msg="Pod template change detected (new: 5477bb6997, old: 76d7668b95)" namespace=staging-space-station rollout=staging-space-station-spanmixer
time="2021-10-15T20:21:17Z" level=info msg="Assuming 5477bb6997 for new replicaset pod hash" namespace=staging-space-station rollout=staging-space-station-spanmixer
time="2021-10-15T20:21:17Z" level=info msg="Pod template change detected (new: 5477bb6997, old: 76d7668b95)" namespace=staging-space-station rollout=staging-space-station-spanmixer
time="2021-10-15T20:21:17Z" level=warning msg="Error updating rollout: rollouts.argoproj.io \"staging-space-station-spanmixer\" not found" generation=325 namespace=staging-space-station resourceVersion=997295647 rollout=staging-space-station-spanmixer
time="2021-10-15T20:21:17Z" level=error msg="roCtx.reconcile err rollouts.argoproj.io \"staging-space-station-spanmixer\" not found" generation=325 namespace=staging-space-station resourceVersion=997295647 rollout=staging-space-station-spanmixer
```

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by DanTulovsky** [comment]
errr...

```
There is no support at this time for upgrading or deleting CRDs using Helm. This was an explicit decision after much community discussion due to the danger for unintentional data loss. Furthermore, there is currently no community consensus around how to handle CRDs and their lifecycle. As this evolves, Helm will add support for those use cases.
```

I guess that would be my problem... grrr...

**Comment by DanTulovsky** [comment]
Hmm, so I manually did a `kubectl apply` on the CRDs in the install.yaml file, but the error remains.

**Comment by harikrongali** [comment]
for rollouts 1.1.0 for helm is updated yesterday as per https://github.com/argoproj/argo-helm/pull/966 .. can you try using this?

**Comment by DanTulovsky** [comment]
So I rolled back to 1.0.7, which works. But, @harikrongali question for you.  Given the helm docs (https://helm.sh/docs/chart_best_practices/custom_resource_definitions/) that state helm doesn't upgrade CRD definitions, how does your chart manager to do it?  Or do I simply misunderstand what the helm docs are saying?
