### ISSUE TITLE
docs: spec documentation not found (broken link)

### ISSUE THREAD

**Issue by oke-py** [argoproj/argo-rollouts#159]
[spec documentation](https://argoproj.github.io/spec) is not found.
https://argoproj.github.io/argo-rollouts/getting-started/#going-forward

**Comment by dthomson25** [comment]
Hi @oke-py, thank you for pointing this issue out. I have changed the link to point to the feature overview page. Please let me know if you have any other issues.

**Comment by oke-py** [comment]
thanks!
