### ISSUE TITLE
Add resolved query to the status of analysisrun 

### ISSUE THREAD

**Issue by huikang** [argoproj/argo-rollouts#1591]
# Summary

In the current implementation, `analsysrun` doesn't display the query with resolved arguments as shown below, which makes it a bit harder to do some troubleshooting on the analysis template.

```
metrics:
  - initialDelay: 60s
    interval: 20s
    name: success-rate
    provider:
      prometheus:
        address: http://prometheus.istio-system:9090
        query: |
          sum(irate(istio_requests_total{

            reporter="source",
            destination_service=~"{{args.service}}.{{args.namespace}}.svc.cluster.local",
            response_code!~"5.*"}[40s])
          ) / sum(irate(istio_requests_total{

            reporter="source",
            destination_service=~"{{args.service}}.{{args.namespace}}.svc.cluster.local"}[40s])
          )
    successCondition: result[0] > 0.90
status:
  metricResults:
  - consecutiveError: 4
    error: 4
    measurements:
    - finishedAt: "2021-10-17T17:31:39Z"
      message: 'reflect: slice index out of range'
      phase: Error
      startedAt: "2021-10-17T17:31:39Z"

```

it would be nice if we can add the query with resolved arguments to the analysisrun status.

# Use Cases

When would you use this?

Users who want to troubleshoot some analysis run with arguments passed from rollout

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by agrawroh** [comment]
@huikang You can assign it to me. I'm working on a similar issue to Dry-Run mode to analysis anyways.
