### ISSUE TITLE
Notifications don't get container info when using WorkloadRef

### ISSUE THREAD

**Issue by yq314** [argoproj/argo-rollouts#1611]
## Summary 

When using WorkloadRef, the notifications will not render container information as per https://github.com/argoproj/argo-rollouts/blob/master/manifests/notifications/on-rollout-completed.yaml#L23

It's because there's no `template` section in the `rollout` object passed to the template, can we populate the template from WorkloadRef before passing it to the template?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by huikang** [comment]
> we could perhaps make pod template available as a second variable, which is populated with either the rollout.spec.template or the deployment.spec.template.

@jessesuen , could you elaborate the above proposal a bit? Do you mean to populate the object with template in the [sendnotification method ](https://github.com/argoproj/argo-rollouts/blob/47d59fa9855ab737e40e21ef5938b2b6723cb899/utils/record/record.go#L194)or some else? Thanks.

**Comment by jessesuen** [comment]
I was proposing something more complicated than necessary (having two objects accessible by the notification templates: `{{.rollout}}` and `{{.podTemplate}}`). In actuality, we can simply populate `spec.template` and `spec.selector` even if the rollout is using workloadRef. https://github.com/argoproj/argo-rollouts/pull/1786 will do that.

**Comment by yq314** [comment]
@jessesuen thanks for the work, however, I noticed the rollout extension stopped working since I moved to `WorkloadRef`, not sure if this is related? See https://github.com/argoproj-labs/argocd-extensions/issues/10 for details
