### ISSUE TITLE
Failed to watch *v1beta1.Ingress: failed to list *v1beta1.Ingress: the server could not find the requested resource

### ISSUE THREAD

**Issue by regiszanandrea** [argoproj/argo-rollouts#1619]
## Summary 
I'm receiving this log from argocd-rollout pod after the argo-rollout installation and my deploy keeps stucked on Health: Progressing. I also tried with version v1.0.6 but I'm getting the same error

What happened/what you expected to happen?
Should deploy normally without error.

## Diagnostics

What version of Argo Rollouts are you running?
Latest: v1.1.0
minikube: v1.23.2
k8s: v1.22.2
docker: 19.03.12

```
time="2021-11-01T00:57:40Z" level=info msg="Argo Rollouts starting" version=v1.0.0+unknown
time="2021-11-01T00:57:40Z" level=info msg="Creating event broadcaster"
time="2021-11-01T00:57:40Z" level=info msg="Setting up event handlers"
time="2021-11-01T00:57:40Z" level=info msg="Setting up experiments event handlers"
time="2021-11-01T00:57:40Z" level=info msg="Setting up analysis event handlers"
time="2021-11-01T00:57:40Z" level=info msg="Waiting for controller's informer caches to sync"
E1101 00:57:40.406070       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/reflector.go:167: Failed to watch *v1beta1.Ingress: failed to list *v1beta1.Ingress: the server could not find the requested resource (get ingresses.extensions)
E1101 00:57:41.691828       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/reflector.go:167: Failed to watch *v1beta1.Ingress: failed to list *v1beta1.Ingress: the server could not find the requested resource (get ingresses.extensions)
E1101 00:57:43.783015       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/reflector.go:167: Failed to watch *v1beta1.Ingress: failed to list *v1beta1.Ingress: the server could not find the requested resource (get ingresses.extensions)

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by perenesenko** [comment]
We have a fix for this one. It's in a master but not released yet

**Comment by perenesenko** [comment]
Fixed in a scope of https://github.com/argoproj/argo-rollouts/issues/1507

**Comment by jinstest1** [comment]
when we can expect the fix to be released ?

**Comment by diegoluisi** [comment]
Hi, same error

`Failed to watch *v1beta1.Ingress: failed to list *v1beta1.Ingress: the server could not find the requested resource (get ingresses.extensions)`

`Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by KimDoubleB** [comment]
argo rollouts `v1.1.1` does not work in `kubernetes 1.23`.
It worked normally in `kubernetes `1.21.5` (I haven't checked version 1.22 yet).
Please refer to this issue #1857
