### ISSUE TITLE
Pin image versions on manifests

### ISSUE THREAD

**Issue by chicocvenancio** [argoproj/argo-rollouts#1623]
# Summary

Manifests are using `latest` as image versions, this creates issues with backwards incompatible changes breaking existing installations. 

# Use Cases

To have a more stable installation. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by harikrongali** [comment]
Project switched to another way of delivering installation manifests. Now each rollout release have install.yaml attached. E.g. https://github.com/argoproj/argo-rollouts/releases/download/v1.1.0/install.yaml

**Comment by jessesuen** [comment]
I think we can close this since the manifests committed in git will always have `:latest`.
