### ISSUE TITLE
refactor to remove mpatch library from rollouts

### ISSUE THREAD

**Issue by harikrongali** [argoproj/argo-rollouts#1653]
With latest commit #1545, contributors are seeing failures in running unit tests locally on mac
Reason is with mpatch library. 
```
        	Error Trace:	list_test.go:182
        	Error:      	Received unexpected error:
        	            	permission denied
        	Test:       	TestListNamespaceAndTimestamp
```

**Comment by huikang** [comment]
This looks duplicate to  #1605

**Comment by jessesuen** [comment]
Duplicate of https://github.com/argoproj/argo-rollouts/issues/1605
