### ISSUE TITLE
Argo Rollout Notifications docs is not correct

### ISSUE THREAD

**Issue by faustodavid** [argoproj/argo-rollouts#1656]
## Summary 

What happened/what you expected to happen?

I was trying to follow the docs https://argoproj.github.io/argo-rollouts/generated/notification-services/webhook/ but failed to implement it. 

In the end, I managed to implement the notification webhook with the help of @jessesuen which points me out the following.

* The docs mention "**Register webhook in `argocd-notifications-cm ConfigMap`**" but it actually should be in `argo-rollouts-notification-configmap` in order to have access to the pre-defined argo-rollouts triggers.
* It is required to create the secret `argo-rollouts-notification-secret` even if your webhook does not require any secret.

## Diagnostics

What version of Argo Rollouts are you running?
1.1.0

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by Nishant-sehgal** [comment]
I can pick this up. Can you assign this to me ?

**Comment by Nishant-sehgal** [comment]
PR: https://github.com/argoproj/argo-rollouts/pull/2393

**Comment by Nishant-sehgal** [comment]
Have created a PR for this: https://github.com/argoproj/notifications-engine/pull/113

**Comment by Nishant-sehgal** [comment]
@zachaller can u check ?

**Comment by Nishant-sehgal** [comment]
@zachaller can you review this ?
