### ISSUE TITLE
Support TCP traffic splitting for Istio's VirtualService

### ISSUE THREAD

**Issue by imranismail** [argoproj/argo-rollouts#1660]
# Summary

An additional parser is needed to cater for TCP routes

# Use Cases

When argo rollouts is in used to expose TCP based services

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by agrawroh** [comment]
@imranismail I'm assigning this to you as you've already started working on it.
