### ISSUE TITLE
Restarting degraded rollout with traffic split starts a canary pod

### ISSUE THREAD

**Issue by bpoland** [argoproj/argo-rollouts#1665]
## Summary

Here's the sequence of events:
1. Rollout with traffic splitting is degraded due to an abort, no canary pods are running (all traffic is on stable version)
2. We trigger a restart of the rollout using the dashboard UI or CLI
3. The stable pods start to restart (good) but a single canary pod is also started (bad)
4. As soon as the canary pod is ready, it gets terminated and a replacement pod is started
5. This cycle continues until all of the stable pods are finished restarting, and then the canary pod scales down

Another strange thing is that even though the dashboard said that the set/actual weight was 0 during the restart, we did see a small amount of traffic get sent to the bad canary version during this process.  This might be a bug with linkerd which we're using for traffic splitting, and wouldn't really be a concern if the pod didn't start in the first place :)

## Diagnostics

Rollouts controller 1.1

## Paste the logs from the rollout controller

https://gist.github.com/bpoland/18afd27926f0b68cf37ad49019264255

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
> Another strange thing is that even though the dashboard said that the set/actual weight was 0 during the restart, we did see a small amount of traffic get sent to the bad canary version during this process.

I examined the controller logs I confirming see that the controller scaling up the canary and increasing weight even though the rollout is aborted. So the small amount of traffic is a result of the controller shifting 25% to the new version temporarily.

```
time="2021-11-18T19:46:26Z" level=info msg="2/6 pods require restart. restarted 0. retrying in 30s" Reconciler=PodRestarter namespace=default rollout=name
time="2021-11-18T19:46:26Z" level=info msg="Reconciling TrafficRouting with type 'SMI'" namespace=default rollout=name
time="2021-11-18T19:46:26Z" level=info msg="TrafficSplit `name` modified" event_reason=TrafficSplitModified namespace=default rollout=name
time="2021-11-18T19:46:26Z" level=info msg="Previous weights: &TrafficWeights{Canary:WeightDestination{Weight:0,ServiceName:name-canary,PodTemplateHash:7df87fcb7f,},Stable:WeightDestination{Weight:100,ServiceName:name-stable,PodTemplateHash:5557785977,},Additional:[]WeightDestination{},Verified:nil,}" namespace=default rollout=name
time="2021-11-18T19:46:26Z" level=info msg="New weights: &TrafficWeights{Canary:WeightDestination{Weight:25,ServiceName:name-canary,PodTemplateHash:7df87fcb7f,},Stable:WeightDestination{Weight:75,ServiceName:name-stable,PodTemplateHash:5557785977,},Additional:[]WeightDestination{},Verified:nil,}" namespace=default rollout=name
time="2021-11-18T19:46:26Z" level=info msg="Skipping analysis: isAborted: true, promoteFull: false, rollbackToScaleDownDelay: false, initialDeploy: false" namespace=default rollout=name
time="2021-11-18T19:46:26Z" level=info msg="Scaled up ReplicaSet name-7df87fcb7f (revision 66) from 0 to 1" event_reason=ScalingReplicaSet namespace=default rollout=name
time="2021-11-18T19:46:26Z" level=info msg="Not finished reconciling new ReplicaSet 'name-7df87fcb7f'" namespace=default rollout=name
time="2021-11-18T19:46:26Z" level=info msg="Not finished reconciling ReplicaSets" namespace=default rollout=name
time="2021-11-18T19:46:26Z" level=info msg="Patched: {\"status\":{\"HPAReplicas\":3,\"availableReplicas\":3,\"canary\":{\"weights\":{\"canary\":{\"weight\":25},\"stable\":{\"weight\":75}}},\"conditions\":[{\"lastTransitionTime\":\"2021-11-18T18:27:08Z\",\"lastUpdateTime\":\"2021-11-18T18:27:08Z\",\"message\":\"Rollout is paused\",\"reason\":\"RolloutPaused\",\"status\":\"False\",\"type\":\"Paused\"},{\"lastTransitionTime\":\"2021-11-18T19:41:10Z\",\"lastUpdateTime\":\"2021-11-18T19:41:10Z\",\"message\":\"RolloutCompleted\",\"reason\":\"RolloutCompleted\",\"status\":\"False\",\"type\":\"Completed\"},{\"lastTransitionTime\":\"2021-11-18T19:42:52Z\",\"lastUpdateTime\":\"2021-11-18T19:42:52Z\",\"message\":\"Rollout aborted update to revision 66\",\"reason\":\"RolloutAborted\",\"status\":\"False\",\"type\":\"Progressing\"},{\"lastTransitionTime\":\"2021-11-18T19:46:26Z\",\"lastUpdateTime\":\"2021-11-18T19:46:26Z\",\"message\":\"Rollout does not have minimum availability\",\"reason\":\"AvailableReason\",\"status\":\"False\",\"type\":\"Available\"}],\"readyReplicas\":3,\"replicas\":3}}" generation=207 namespace=default resourceVersion=8703936 rollout=name
```

NOTE: I did attempt to reproduce this, but was unable to. I had the following rollout using SMI, which was aborted, and canary scaled down:

```
Name:            rollout-smi-experiment
Namespace:       argo-rollouts
Status:          ✖ Degraded
Message:         RolloutAborted: Rollout aborted update to revision 2
Strategy:        Canary
  Step:          0/2
  SetWeight:     0
  ActualWeight:  0
Images:          nginx:1.19-alpine (stable)
Replicas:
  Desired:       2
  Current:       2
  Updated:       0
  Ready:         2
  Available:     2

NAME                                                KIND        STATUS        AGE    INFO
⟳ rollout-smi-experiment                            Rollout     ✖ Degraded    7m56s
├──# revision:2
│  └──⧉ rollout-smi-experiment-8544f9c4dc           ReplicaSet  • ScaledDown  7m18s  canary,delay:passed
└──# revision:1
   └──⧉ rollout-smi-experiment-85d47b586d           ReplicaSet  ✔ Healthy     7m56s  stable
      ├──□ rollout-smi-experiment-85d47b586d-ldlm9  Pod         ✔ Running     30s    ready:1/1
      └──□ rollout-smi-experiment-85d47b586d-f4n4b  Pod         ✔ Running     28s    ready:1/1
```

I ran: `kubectl-argo-rollouts restart rollout-smi-experiment` but only the stable pods restarted and the canary ReplicaSet did not change at all.

@bpoland which version of SMI spec are you running?

**Comment by jessesuen** [comment]
I can reproduce this now. It appears to be related to calculations when using the `dynamicStableScale` feature.

**Comment by agrawroh** [comment]
> I can reproduce this now. It appears to be related to calculations when using the `dynamicStableScale` feature.

@jessesuen You want me to work on this?

**Comment by bpoland** [comment]
> I examined the controller logs and I can confirm that the controller scaling up the canary and increasing weight even though the rollout is aborted. So the small amount of traffic is a result of the controller shifting 25% to the new version temporarily.

Is this also related to the `dynamicStableScale` bug that you mentioned in your next comment?  Because I think we can agree that the weights shouldn't be changed when the rollout is in an aborted state right?

**Comment by jessesuen** [comment]
Yes the issues are related. The fix I have will address both. 

> @jessesuen You want me to work on this?

No, I have a fix at hand
