### ISSUE TITLE
Number of replicas = Number of times notification sent to slack channel

### ISSUE THREAD

**Issue by deepanverma19** [argoproj/argo-rollouts#1667]
## Summary 

What happened/what you expected to happen?
I increased the number of replicas of argo rollouts deployment from 1 to 3 and on every success of canary rollout its sending me notification three times on slack channel. We're running more than one argo rollouts pods for HA on our aws eks.
## Diagnostics

What version of Argo Rollouts are you running?
v1.1.0
```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by huikang** [comment]
Thanks for reporting!

I think only the primary replica should be able to send the notification. Will fix this.

**Comment by huikang** [comment]
Hi, @deepanverma19 , I think the HA mode is not supported in v1.1.0; therefore when you have 3 replicas, it ends up 3 identical controllers.

The HA mode is planned for **v1.2**, so if you installed from the latest version the issue should be solved.
https://argoproj.github.io/argo-rollouts/FAQ/#can-we-run-the-argo-rollouts-controller-in-ha-mode

**Comment by deepanverma19** [comment]
@huikang perfect, sounds good 👍

**Comment by harikrongali** [comment]
@deepanverma19 please reopen if you see still see any issue.
