### ISSUE TITLE
kubectl plugin to manipulate rollouts

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#167]
We need a kubectl plugin which can manipulate rollouts. Some use cases:
* manually pausing/unpausing a rollout
* manually aborting a rollout
* restarting an aborted rollout

**Comment by jessesuen** [comment]
Remaining tasks:
- [ ]  make plugin part of release target
- [ ]  add command to get rollout details (showing current step, weight %)
- [ ]  add command to abort a rollout

**Comment by dthomson25** [comment]
Implemented by multiple PRs
