### ISSUE TITLE
Homebrew deprecation notice

### ISSUE THREAD

**Issue by xbuzz** [argoproj/argo-rollouts#1682]
## Summary 

What happened/what you expected to happen?

Homebrew installation deprecation.

> Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the argoproj/tap tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/argoproj/homebrew-tap/kubectl-argo-rollouts.rb:8

OS: macOS 12.0.1 (MacBook Pro 14" 2021, Apple M1 Max)
Homebrew `3.3.6`

## Diagnostics

What version of Argo Rollouts are you running?

N/A

```
# Paste the logs from the rollout controller

N/A

# Logs for the entire controller:

N/A

# Logs for a specific rollout:

N/A
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by danielhelfand** [comment]
This looks like it can be closed, right? Fixed by: https://github.com/argoproj/homebrew-tap/pull/22

**Comment by xbuzz** [comment]
@danielhelfand verified this has been resolved. Cheers!
