### ISSUE TITLE
Enable Notifications for Analysis Runs

### ISSUE THREAD

**Issue by RaviHari** [argoproj/argo-rollouts#1694]
# Summary

Notifications to be sent based on the triggers for analysis.

# Use Cases

This will be useful when in canary deployments/progressive delivery when the traffic is being shifted to latest deployments when the analysis runs fails it notifies the users in slack/email etc.,

cc: @jessesuen 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by faustodavid** [comment]
When the Analysis Run fails, the rollout is aborted. You can listen to `trigger.on-rollout-aborted` to notify your users.

**Comment by RaviHari** [comment]
sure.. I am thinking even other scenarios like: 

- when the canary rolls out if there is a delayed analysis it would be good to have a notification if that analysis is successful.. 
- If there are multiple templates under analysis used.. it would be good to know which ones failed and which ones passed with a notification.
- prePromotionAnalysis notification can help to determine if users can promote in case of blue-green deployments.
- postPromotionAnalysis notification can help to determine not only the rollout is complete but validation with data is successful. etc.,

**Comment by jessesuen** [comment]
I believe we already emit events for things like: AnalyisRunFailed AnalysisRunSucceeded. I feel like it might be possible to do this today with `on-analysisrun-failed` . If not, I think it should be fixed.

> When the Analysis Run fails, the rollout is aborted. You can listen to trigger.on-rollout-aborted to notify your users.

Another scenario where this might not be enough is, now that we will have DryRuns in v1.2, the abort event wont actually happen but analysis will still fail. it will be good to get notified about that.

**Comment by Abhishek-Kaudare** [comment]
How can we configure notifications for analysisrun step inconclusive
