### ISSUE TITLE
Use rollout informer instead of API list

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#17]
In service.go:
```golang
func (c *Controller) getRolloutsForService(service *corev1.Service) ([]*v1alpha1.Rollout, error) {
	allROs, err := c.rolloutsclientset.ArgoprojV1alpha1().Rollouts(service.Namespace).List(metav1.ListOptions{})
	if err != nil {
		return nil, err
	}
```

We should use the informer instead of list API

**Comment by dthomson25** [comment]
With this issue, we should investigate the code base and find other places that we can switch to informers in addition to the above example

**Comment by dthomson25** [comment]
After investigating the code, the only place we use the API instead of the rollout informer is at https://github.com/argoproj/argo-rollouts/blob/master/controller/replicaset.go#L35.  In this use, we are required to use the API to get up to date information.
