### ISSUE TITLE
UI: displaying canary scale in the steps

### ISSUE THREAD

**Issue by huikang** [argoproj/argo-rollouts#1702]
# Summary

The value of canaryscale is missing in the steps of the rollout UI

# Use Cases
<img width="387" alt="Screen Shot 2021-12-12 at 11 27 18 PM" src="https://user-images.githubusercontent.com/463631/145752491-e7b88541-1dec-4808-bd2d-be5b4c51e4fe.png">

When would you use this?

Like the weight % is displayed in the UI, it is useful to see the canaryscale value.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by harikrongali** [comment]
@schakrad assigned to you

**Comment by schakrad** [comment]
I would like to work on this PR.

**Comment by harikrongali** [comment]
https://github.com/argoproj/argo-rollouts/issues/1702 fixes the issue
