### ISSUE TITLE
Leader election lease namespace should be controller namespace

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#1704]
## Summary 

I noticed that the upcoming 1.2 leader election feature will try to use `kube-system` as the namespace to manage the Lease object. However, I think it should manage it in the same namespace as the controller (e.g. argo-rollouts). @huikang is there a reason `kube-system` is used as the default?

## Diagnostics

What version of Argo Rollouts are you running? v1.2 (unreleased)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by huikang** [comment]
@jessesuen , I don't think there is any particular reason to set `kube-system` as default. I agreed that we shall use the same namespace as the controller. Let me fix it.

**Comment by huikang** [comment]
Gotcha. I agree it is better to have the lease lock in the same namespace as the controller automatically.
But what if the controller is running out of the cluster (say, in a local dev mode)? Shall we provide a default value for the namespace?
