### ISSUE TITLE
Allow multiple stableIngress

### ISSUE THREAD

**Issue by luckyluke13** [argoproj/argo-rollouts#1708]
# Summary

Under trafficRouting, stableIngress in the rollout object, only one stableIngress can be specified. It would be good to be able to specify multiple ingress rules.

# Use Cases

In many serious kubernetes implementations, it is not sustainable to work with only one big ingress rule but instead have multiple ingress rules for example for different host endpoints. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
Which traffic provider integration are you using / asking to use this with?

Or are you asking about stableService (and not ingress)

**Comment by Kakaboto** [comment]
Hello,

NGINX

**Comment by javier-diaz-ppro** [comment]
This is how I have the rollout configured to use multiple ingress controllers:
`    canary:
      canaryService: rollouts-demo-canary
      stableService: rollouts-demo-stable
      trafficRouting:
        nginx:
          stableIngress: rollouts-demo-stable
        nginx:
          stableIngress: rollouts-demo-stable-public`

**Comment by therealdwright** [comment]
> This is how I have the rollout configured to use multiple ingress:

Are you sure this works? It looks like invalid YAML and I would have thought the last ingress object would "win" so to speak.

**Comment by andycoderapptio** [comment]
I'm testing this out now but appears to have been addressed: https://argo-rollouts.readthedocs.io/en/stable/features/traffic-management/nginx/

Just posting here as I noticed this issue was open when searching for a solution.

**Comment by kostis-codefresh** [comment]
Closing since this was covered by https://github.com/argoproj/argo-rollouts/issues/2001
