### ISSUE TITLE
kubectl-argo-rollouts arm64 docker image not working - Dashboard

### ISSUE THREAD

**Issue by cguertin14** [argoproj/argo-rollouts#1728]
## Summary 

The arm64 version of the `quay.io/repository/argoproj/kubectl-argo-rollouts` Docker image isn't working.
When running a container on my raspberry pi with the image tagged `v1.1.1`, I get the following error:
```
standard_init_linux.go:228: exec user process caused: exec format error
```

## Diagnostics

What version of Argo Rollouts are you running? `v1.1.1`

```
# Paste the logs from the rollout dashboard

standard_init_linux.go:228: exec user process caused: exec format error
```

The problem seems to be that `amd64` is hardcoded in the Dockerfile, [here](https://quay.io/repository/argoproj/kubectl-argo-rollouts/manifest/sha256:fd70202d6d3efbf2ca8c6ebaf4a1dd58732b4430bd465b0afc11e5c09f1949fb):
![image](https://user-images.githubusercontent.com/23645771/147196320-3eb58785-13d0-4a97-949c-d415e87703e1.png)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by kostis-codefresh** [comment]
I think that we need to create the ARM executable first. Doesn't look it is created by default https://github.com/argoproj/argo-rollouts/blob/4c08f7ea70e173c09ea35e9bb56cfcfc6bb0118c/.github/workflows/release.yaml#L130

**Comment by cguertin14** [comment]
> I think that we need to create/keep the ARM executable first. Doesn't look it is released by default
> 
> https://github.com/argoproj/argo-rollouts/blob/4c08f7ea70e173c09ea35e9bb56cfcfc6bb0118c/.github/workflows/release.yaml#L130

True, the arm64 artifacts don't seem to be released, but the arm64 Docker images are released on Quay. The problem with those images seems to be in the Dockerfile of the plugin where it uses an amd64 base image: https://github.com/argoproj/argo-rollouts/blob/master/Dockerfile#L74

The root cause of this is probably deeper than that, but to me that seems like a good starting point

**Comment by SahajMahajan** [comment]
When deploying this image: argoproj/rollouts-demo:blue on minikube cluster on MacBook air.
Getting this error - exec /rollouts-demo: exec format error

Argo Rollouts Version - quay.io/argoproj/argo-rollouts:v1.6.6

**Comment by kostis-codefresh** [comment]
@SahajMahajan the error probably means that the rollouts-demo is not compiled for mac/arm and has nothing to do with Argo Rollouts.

You should open an issue at https://github.com/argoproj/rollouts-demo
