### ISSUE TITLE
Add more prometheus metrics

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#173]
Need metrics for:
* counter whenever rollout spec changes and we deploy
* general Experiment and AnalysisRun metrics

**Comment by jessesuen** [comment]
* Consider only incrementing counters upon state changes instead of every reconciliation.

**Comment by dthomson25** [comment]
Other possible metrics include:
* Any kubernetes client operations on resources
* Current version
* Detecting a usually high number of reconciliations (i.e. infinite loop in the controller)
