### ISSUE TITLE
Argo Rollouts docs should prioritize k3d

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-rollouts#1750]
# Summary

The Argo Rollouts contribution docs should use k3d instead of Minikube. This will bring it in line with the [recommended setup for Argo CD](https://argo-cd.readthedocs.io/en/stable/developer-guide/toolchain-guide/#using-k3d) (and, I believe, Workflows).

# Use Cases

New developers starting with Argo Rollouts will have a better experience with k3d (we've encountered quite a few issues with Minikube), and they'll have a more consistent experience if they choose to also work on other Argo projects.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by iam-veeramalla** [comment]
Hi @crenshaw-dev , There is already a PR for this by @danielhelfand #1867 .. Do you think anything else is required on the PR. I will be more than happy to contribute or we can close this.
