### ISSUE TITLE
Adding InfluxDB as a metrics provider for Argo Rollouts

### ISSUE THREAD

**Issue by jaymebrd** [argoproj/argo-rollouts#1755]
# Summary

Add influxDB as a metrics provider to Argo Rollouts

# Use Cases

InfluxDB is a popular open source TSBD, it's make a great addition to the current metric providers available.

I already have a basic implementation of this, and if you're happy I'll go ahead and clean it up and make a PR for it.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by perenesenko** [comment]
Hi @jaymebrd 
Please go ahead with your PR.

**Comment by jaymebrd** [comment]
Thanks @perenesenko I've created a PR for this.

**Comment by jaymebrd** [comment]
Hi @jessesuen @huikang - Just wanted to reach out again, would love to get the above PR in soon if possible - would appreciate reviews

**Comment by jaymebrd** [comment]
This has been implemented, merged and released so I think we can close this.
