### ISSUE TITLE
Report notification metrics

### ISSUE THREAD

**Issue by WillSewell** [argoproj/argo-rollouts#1782]
# Summary

Currently if a notification fails to send, the controller [logs an error](https://github.com/argoproj/argo-rollouts/blob/5b140c97c569647a4f1e604a44262c9d5281656c/utils/record/record.go#L181), but it does not emit a metric.

It would be useful to have a counter metric for notifications sent (with a label to differentiate success and failures).

A metric to track latency would also be useful.

# Use Cases

We want to get an accurate idea of the success rate of notifications. We could do this by scraping the logs, but Prometheus would be more convenient for us because that's what we use for our existing alerting rules.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by RaviHari** [comment]
I would like to work on it.
