### ISSUE TITLE
VPA support for argo rollouts

### ISSUE THREAD

**Issue by DanTulovsky** [argoproj/argo-rollouts#1801]
VPA does not seem to be correctly supported by Argo Rollouts.

- If VPA points to the rollout, then VPA seems to generate updates, but they don't get applied.
- If VPA points to the Deployment and Rollout references the Deployment, VPA does not generate any suggestions because it claims there are no matching pods. (Which is true, if it's looking for Pods owned by the deployment).

I think the correct answer here is for the Controller to support VPA directly.

https://cloud.google.com/kubernetes-engine/docs/concepts/verticalpodautoscaler#verticalpodautoscalerspec_v1_autoscalingk8sio

Is there any workaround in the meantime?

Thank you

**Comment by harikrongali** [comment]
HPA is available with following example https://argoproj.github.io/argo-rollouts/features/hpa-support/#example
and from VPA [docs](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go#L86) , seems like same config is available.
Can you please verify if that works ?

**Comment by DanTulovsky** [comment]
Hi,

HPA does work. VPA does not work in the way I described above. 

Thank you
Dan

**Comment by jessesuen** [comment]
According to docs, to support VPA, the controller simply needs to support the scale subresource:

> You can point a VerticalPodAutoscaler at any controller that has a Scale subresource

Which we do. See:
https://github.com/argoproj/argo-rollouts/blob/master/pkg/apis/rollouts/v1alpha1/types.go#L18

Without the support for scale subresource, HPA wouldn't work either. So I'm not sure why VPA wouldn't work.

> then VPA seems to generate updates, but they don't get applied.

Can you shed more light on this? Where do you see it generating updates? Does the VPA controller have permission to update?

**Comment by DanTulovsky** [comment]
VPA + Deployment (no Rollout) definitely works, so I don't think permissions are an issue.

Here's a VPA recommendation:

```
API Version:  autoscaling.k8s.io/v1
Kind:         VerticalPodAutoscaler
...

Spec:
  Resource Policy:
    Container Policies:
      Container Name:  bento
      Max Allowed:
        Cpu:     1
        Memory:  1Gi
      Min Allowed:
        Cpu:           1
        Memory:        128Mi
      Mode:            Auto
  Target Ref:
    API Version:  argoproj.io/v1alpha1
    Kind:         Rollout
    Name:         staging-bento
  Update Policy:
    Update Mode:  Auto
```

Here's the status of the VPA:

```
Status:
  Conditions:
    Last Transition Time:  2020-08-06T18:30:48Z
    Message:               Fetching history complete
    Status:                False
    Type:                  FetchingHistory
    Last Transition Time:  2021-04-09T17:13:03Z
    Status:                False
    Type:                  LowConfidence
    Last Transition Time:  2022-01-21T15:11:13Z
    Status:                True
    Type:                  RecommendationProvided
  Recommendation:
    Container Recommendations:
      Container Name:  bento
      Lower Bound:
        Cpu:     1
        Memory:  1Gi
      Target:
        Cpu:     1
        Memory:  1Gi
      Uncapped Target:
        Cpu:     200m
        Memory:  1464860672
      Upper Bound:
        Cpu:     1
        Memory:  1Gi
```

Note the `Lower Bound` CPU of `1`.

The rollout has:

```
  Workload Ref:
    API Version:  apps/v1
    Kind:         Deployment
    Name:         staging-bento
```
Here's one of three pods:

```
    State:          Running
      Started:      Thu, 27 Jan 2022 12:52:13 -0500
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     500m
      memory:  1Gi
    Requests:
      cpu:      500m
      memory:   1Gi
```

Note that CPU is still at 500m.  

If I switch this workload back to a Deployment and remove the rollout, VPA works properly.

BTW, the last recommendation provided by VPA:

```
    Last Transition Time:  2022-01-21T15:11:13Z
    Status:                True
    Type:                  RecommendationProvided
```
That is the date when I switched VPA to point to Rollout instead of Deployment in its TargetRef.  With VPA pointing to the Deployment (that is scaled down to 0 and point to Rollout), VPA complains that there are no pods and does not provide any recommendations.

Have you seen this actually work?

Thank you
Dan

**Comment by RaviHari** [comment]
VPA works for Rollouts.. we have to update RBAC permission to get,list,watch for argoproj.io apigroup and rollouts resources

Here is the recommendation from vpa object I tried some time back:
```
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"autoscaling.k8s.io/v1beta2","kind":"VerticalPodAutoscaler","metadata":{"annotations":{},"name":"kubengix-vpa-rollout","namespace":"vpa-demo"},"spec":{"resourcePolicy":{"containerPolicies":[{"containerName":"*","controlledResources":["cpu","memory"],"maxAllowed":{"cpu":1,"memory":"500Mi"},"minAllowed":{"cpu":"5m","memory":"5Mi"}}]},"targetRef":{"apiVersion":"argoproj.io/v1alpha1","kind":"Rollout","name":"vpa-demo-rollout"},"updatePolicy":{"updateMode":"Auto"}}}
  creationTimestamp: "2021-08-19T07:07:57Z"
  generation: 2
  managedFields:
  - apiVersion: autoscaling.k8s.io/v1beta2
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        .: {}
        f:resourcePolicy:
          .: {}
          f:containerPolicies: {}
        f:targetRef:
          .: {}
          f:apiVersion: {}
          f:kind: {}
          f:name: {}
        f:updatePolicy:
          .: {}
          f:updateMode: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-08-19T07:07:57Z"
  - apiVersion: autoscaling.k8s.io/v1beta2
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:conditions: {}
        f:recommendation:
          .: {}
          f:containerRecommendations: {}
    manager: recommender
    operation: Update
    time: "2021-08-19T07:08:50Z"
  name: kubengix-vpa-rollout
  namespace: vpa-demo
  resourceVersion: "9406197"
  selfLink: /apis/autoscaling.k8s.io/v1beta2/namespaces/vpa-demo/verticalpodautoscalers/kubengix-vpa-rollout
  uid: 3c8755de-3fca-4917-948f-b9071e6dbaf2
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources:
      - cpu
      - memory
      maxAllowed:
        cpu: 1
        memory: 500Mi
      minAllowed:
        cpu: 5m
        memory: 5Mi
  targetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: vpa-demo-rollout
  updatePolicy:
    updateMode: Auto
status:
  conditions:
  - lastTransitionTime: "2021-08-19T07:08:50Z"
    status: "True"
    type: RecommendationProvided
  recommendation:
    containerRecommendations:
    - containerName: vpa-nginx
      lowerBound:
        cpu: 25m
        memory: 262144k
      target:
        cpu: 25m
        memory: 262144k
      uncappedTarget:
        cpu: 25m
        memory: 262144k
      upperBound:
        cpu: "1"
        memory: 500Mi
```

**Comment by DanTulovsky** [comment]
Are you saying these permissions are not currently in the install script?

To be clear, I get recommendations just like you, but nothing acts on those recommendations...

On Fri, Jan 28, 2022, at 10:40 AM, RaviHari wrote:
> 
> 
> VPA works for Rollouts.. we have to update RBAC permission to get,list,watch for argoproj.io apigroup and rollouts resources
> 
> Here is the recommendation from vpa object I tried some time back:
> 
> `apiVersion: autoscaling.k8s.io/v1beta2
> kind: VerticalPodAutoscaler
> metadata:
>   annotations:
>     kubectl.kubernetes.io/last-applied-configuration: |
>       {"apiVersion":"autoscaling.k8s.io/v1beta2","kind":"VerticalPodAutoscaler","metadata":{"annotations":{},"name":"kubengix-vpa-rollout","namespace":"vpa-demo"},"spec":{"resourcePolicy":{"containerPolicies":[{"containerName":"*","controlledResources":["cpu","memory"],"maxAllowed":{"cpu":1,"memory":"500Mi"},"minAllowed":{"cpu":"5m","memory":"5Mi"}}]},"targetRef":{"apiVersion":"argoproj.io/v1alpha1","kind":"Rollout","name":"vpa-demo-rollout"},"updatePolicy":{"updateMode":"Auto"}}}
>   creationTimestamp: "2021-08-19T07:07:57Z"
>   generation: 2
>   managedFields:
>   - apiVersion: autoscaling.k8s.io/v1beta2
>     fieldsType: FieldsV1
>     fieldsV1:
>       f:metadata:
>         f:annotations:
>           .: {}
>           f:kubectl.kubernetes.io/last-applied-configuration: {}
>       f:spec:
>         .: {}
>         f:resourcePolicy:
>           .: {}
>           f:containerPolicies: {}
>         f:targetRef:
>           .: {}
>           f:apiVersion: {}
>           f:kind: {}
>           f:name: {}
>         f:updatePolicy:
>           .: {}
>           f:updateMode: {}
>     manager: kubectl-client-side-apply
>     operation: Update
>     time: "2021-08-19T07:07:57Z"
>   - apiVersion: autoscaling.k8s.io/v1beta2
>     fieldsType: FieldsV1
>     fieldsV1:
>       f:status:
>         .: {}
>         f:conditions: {}
>         f:recommendation:
>           .: {}
>           f:containerRecommendations: {}
>     manager: recommender
>     operation: Update
>     time: "2021-08-19T07:08:50Z"
>   name: kubengix-vpa-rollout
>   namespace: vpa-demo
>   resourceVersion: "9406197"
>   selfLink: /apis/autoscaling.k8s.io/v1beta2/namespaces/vpa-demo/verticalpodautoscalers/kubengix-vpa-rollout
>   uid: 3c8755de-3fca-4917-948f-b9071e6dbaf2
> spec:
>   resourcePolicy:
>     containerPolicies:
>     - containerName: '*'
>       controlledResources:
>       - cpu
>       - memory
>       maxAllowed:
>         cpu: 1
>         memory: 500Mi
>       minAllowed:
>         cpu: 5m
>         memory: 5Mi
>   targetRef:
>     apiVersion: argoproj.io/v1alpha1
>     kind: Rollout
>     name: vpa-demo-rollout
>   updatePolicy:
>     updateMode: Auto
> status:
>   conditions:
>   - lastTransitionTime: "2021-08-19T07:08:50Z"
>     status: "True"
>     type: RecommendationProvided
>   recommendation:
>     containerRecommendations:
>     - containerName: vpa-nginx
>       lowerBound:
>         cpu: 25m
>         memory: 262144k
>       target:
>         cpu: 25m
>         memory: 262144k
>       uncappedTarget:
>         cpu: 25m
>         memory: 262144k
>       upperBound:
>         cpu: "1"
>         memory: 500Mi
`

**Comment by RaviHari** [comment]
Yes.. the permissions are not listed in the vpa deployment..
you need to update apigroup permissions here: https://github.com/kubernetes/autoscaler/blob/a393fe219c5ed6b024eb87e8e79e5004025322b0/vertical-pod-autoscaler/deploy/vpa-rbac.yaml#L174

and

resources here:
https://github.com/kubernetes/autoscaler/blob/a393fe219c5ed6b024eb87e8e79e5004025322b0/vertical-pod-autoscaler/deploy/vpa-rbac.yaml#L176

**Comment by DanTulovsky** [comment]
Ah.. so like:

```
  - apiGroups:
      - apps
      - argoproj.io <http://argoproj.io/v1alpha1>
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
      - rollouts
    verbs:
      - get
      - list
      - watch
```
Is that what you have?

**Comment by RaviHari** [comment]
yes.. you donot need  http://argoproj.io/v1alpha1..
just this will do:

```
  - apiGroups:
      - apps
      - argoproj.io
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
      - rollouts
    verbs:
      - get
      - list
      - watch
```

**Comment by DanTulovsky** [comment]
It also looks like: https://github.com/kubernetes/autoscaler/pull/3139/files would work.

This is on GKE.  I just tried to manually edit the roll, and gke promptly reverted it back.  :(

On Fri, Jan 28, 2022, at 11:00 AM, RaviHari wrote:
> 
> 
> 
> yes.. you donot need http://argoproj.io/v1alpha1..
> just this will do:
> 
> `  - apiGroups:
>       - apps
>       - argoproj.io
>     resources:
>       - daemonsets
>       - deployments
>       - replicasets
>       - statefulsets
>       - rollouts
>     verbs:
>       - get
>       - list
>       - watch
`

**Comment by RaviHari** [comment]
Ok.. I will update the documentation on how to enable VPA for argo-rollouts.
