### ISSUE TITLE
Issue after upgrading to v1.1.1 from v1.0.7 | failed to list *v1beta1.Ingress

### ISSUE THREAD

**Issue by AAATechGuy** [argoproj/argo-rollouts#1805]
Once upgraded, pod `pod/argo-rollouts-588d458875-whgdf` restarts and never in ready state. 

We used the command 
`kubectl apply -n argo-rollouts -f https://github.com/argoproj/argo-rollouts/releases/download/v1.1.1/install.yaml`

Logs as follows. 
```
E0125 21:55:37.784673       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/reflector.go:167: Failed to watch *v1beta1.Ingress: failed to list *v1beta1.Ingress: the server could not find the requested resource (get ingresses.extensions)
```

Our Azure Kubernetes Controller version: 1.22.4

Also tried, removing previous argo-rollout and installing new version, didn't work. 

In other posts, we saw few error messages, 
`W1216 16:13:02.055832       1 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress`

Appreciate any help here.

**Comment by SriranjithaR** [comment]
Facing the same issue. 
The argo-rollout pod goes into a crashloopbackoff with this error message :
`level=fatal msg="Error running controller: failed to wait for caches to sync"`

**Comment by leoluz** [comment]
Argo-Rollouts is currently incompatible with kubernetes 1.22. We have a fix already in master and will be part of Argo-Rollotus 1.2. It will be released in the coming weeks.
If this is urgent for you, the workaround and building and deploying Argo-Rollouts from `master`.
