### ISSUE TITLE
Reported weight doesn't match actual Rollout/Traffic Split weight

### ISSUE THREAD

**Issue by bpoland** [argoproj/argo-rollouts#1812]
## Summary 

When using a Rollout with traffic splitting (SMI to be precise) the weight reported in the rollouts dashboard and `kubectl argo rollouts get rollout <name>` sometimes don't match the value in the Rollout `.status.canary.weights.canary.weight` or the actual `TrafficSplit` resource.  For example, if we are at weight x and then proceed to a step `setWeight: y` where y would require more pods, the dashboard/plugin report y immediately for both SetWeight and ActualWeight but the Rollout status and TrafficSplit continue to report x until enough pods are ready, then get updated to y.

I think the dashboard/plugin should show SetWeight: y but ActualWeight: x until enough pods are available and the traffic split is updated.

## Diagnostics

1.1.1

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
The current displayed weight was written before the controller recording the weight into status. Now that we record the weight into status, this is what should be displayed in the dashboard.
