### ISSUE TITLE
Update `github.com/newrelic/newrelic-client-go` from 0.72.0 to latest

### ISSUE THREAD

**Issue by blkperl** [argoproj/argo-rollouts#1876]
# Summary

Dependabot needs assistance updating the newrelic-client https://github.com/argoproj/argo-rollouts/pull/1859

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by kidk** [comment]
Hi 👋  I'm a Technical Product Manager at New Relic. I just wanted to give notice that we will be deprecating versions of our `newrelic-client-go` before 0.73. 

How can we help move this forward? I tried to look at the build but didn't see anything related to our library. 

I'll continue digging, but any hints the right direction are much appreciated.

**Comment by blkperl** [comment]
Fixed in #2136
