### ISSUE TITLE
argo rollout does not delete metrics after rollout has been deleted

### ISSUE THREAD

**Issue by bysph** [argoproj/argo-rollouts#1885]
## Summary 

What happened/what you expected to happen?
When a rollout has been deleted, argo rollout does not delete it's metrics which has been cached in vec map. This will make response body of metric api too large.

## Diagnostics

What version of Argo Rollouts are you running?
1.11.0

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by bysph** [comment]
@jessesuen @dthomson25

**Comment by vabc3** [comment]
This may be similar issue https://github.com/argoproj/argo-rollouts/issues/1913 . Even after rollout got deleted, the sync controller still keeps patching it.
