### ISSUE TITLE
how to generate rollout.Status.canary.stableRS

### ISSUE THREAD

**Issue by ZhangShunzz** [argoproj/argo-rollouts#1906]
## Summary 

What happened/what you expected to happen?

rollout.Status.canary.stableRS is number.
<img width="215" alt="image" src="https://user-images.githubusercontent.com/44627917/157719079-9c251de4-af9b-4ee5-bad1-6bcb94d5e67a.png">

get error: ReadString: expects " or n, but found 5, error found in #10 byte of ...|tableRS":56868747}

## Diagnostics

What version of Argo Rollouts are you running?

v0.8.4

```
# Paste the logs from the rollout controller

Failed to list *v1alpha1.Rollout: v1alpha1.RolloutList.Items: []v1alpha1.Rollout: v1alpha1.Rollout.Status: v1alpha1.RolloutStatus.Canary: v1alpha1.CanaryStatus.StableRS: ReadString: expects " or n, but found 5, error found in #10 byte of ...|tableRS":56868747},"|..., bigger context ...|eReplicas":2,"blueGreen":{},"canary":{"stableRS":56868747},"conditions":[{"lastTransitionTime":"2021|...

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by harikrongali** [comment]
please try with latest image 1.3.1 and reopen if still an issue
