### ISSUE TITLE
Is v1.2.0 compatible with Kubernetes 1.16? If not, can the project provide a compatibility matrix?

### ISSUE THREAD

**Issue by hcelaloner** [argoproj/argo-rollouts#1939]
# Summary

Previously, some of our clusters had Argo Rollouts v1.1.1 installed via helm charts located in the argo-helm repository. When we tried to upgrade to v1.2.0, we encountered the following error 

```
error validating data: ValidationError(CustomResourceDefinition.spec.versions[0].schema.openAPIV3Schema.properties.spec.properties.template.properties.spec.properties.nodeSelector): unknown field "x-kubernetes-map-type" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps
```

I guess `x-kubernetes-map-type` was added in k8s 1.17. If Argo Rollouts is not compatible with k8s 1.16 clusters, it may be good to state this information somewhere? Maybe release notes if that is the case or a compatibility matrix for recent versions (like: https://github.com/open-telemetry/opentelemetry-operator#opentelemetry-operator-vs-kubernetes-vs-cert-manager)? Or with some sort of skip validation option can someone install it to a v1.16 cluster?

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by harikrongali** [comment]
Every ArgoRollout release supports the latest & latest-2 versions only. But you are correct, it is not mentioned anywhere in the docs and we will update them

**Comment by thatsmydoing** [comment]
I think this ticket is related to ingress versions https://github.com/argoproj/argo-rollouts/issues/1507 (there's a flag for it)

> Every ArgoRollout release supports the latest & latest-1 versions only. But you are correct, it is not mentioned anywhere in the docs and we will update them

I'm not sure that's true as only 1.2.0 supports kubernetes 1.22 and above. And 1.1.0 was released when 1.22 was latest.

**Comment by rcontreras-te** [comment]
So, I bumped into this just today.  We're running K8S `v1.16.13` / argo-rollouts `v1.1.1` and I was unable to upgrade to argo-rollouts `v1.2.1` because of this.  

So what is the minimum version of K8S required in order to use argo-rollouts `v1.2.0`?  I didn't see minimum requirement mention in the `v1.2.0` release notes.  @harikrongali , you mentioned that there might be an update to the docs for this... is it possible to get a link to that?

**Comment by hcelaloner** [comment]
Closing this one since it has been solved by https://github.com/argoproj/argo-rollouts/pull/2163
