### ISSUE TITLE
`when` condition does not work in notification triggers

### ISSUE THREAD

**Issue by geojakes** [argoproj/argo-rollouts#1962]
## Summary 

I've configured argo rollout notifications in our cluster like so via the helm chart values file:

```
notifications:
  # -- Configures notification services
  notifiers:
    service.slack: |
      token: $slack-token
  templates:
    template.rollout-paused: |
      message: |
        Rollout {{.rollout.metadata.name}} is now paused for 15 seconds.
      slack:
        attachments: |
          [{
            "title": "{{ .rollout.metadata.name}}",
            "color": "#18be52",
            "fields": [
            {
              "title": "Strategy",
              "value": "{{if .rollout.spec.strategy.blueGreen}}BlueGreen{{end}}{{if .rollout.spec.strategy.canary}}Canary{{end}}",
              "short": true
            },
            {
              "title": "Pause step",
              "value": "{{add .rollout.status.currentStepIndex 1}}/{{len .rollout.spec.strategy.canary.steps}}",
              "short": true
            }
            {{range $index, $c := .rollout.spec.template.spec.containers}}
              {{if not $index}},{{end}}
              {{if $index}},{{end}}
              {
                "title": "{{$c.name}}",
                "value": "{{$c.image}}",
                "short": true
              }
            {{end}}
            ]
          }]
  triggers:
    trigger.on-rollout-step-completed: |
      - when: rollout.metadata.name != "frontend"
        send: [rollout-paused]
```
What happened/what you expected to happen?

The expectation was that during deployment, this notification flows into a slack channel for all applications that are not frontend. Instead the `rollout-step-completed` notification happens for all valid when clause (I am assuming). If I use `.rollout.metadata.name` instead, the notifications doesn't work for all application rollouts in the cluster.

## Diagnostics

What version of Argo Rollouts are you running?

I am using argo rollouts version `1.2.0` and helm chart version `2.14.0`. Invalid conditions are the only ones that generate any logs regarding the violation of `Condition.when`. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by harikrongali** [comment]
@RaviHari can you please check if this is an issue.

**Comment by RaviHari** [comment]
I verified this it looks like when condition is not taking effect. The notification gets sent irrespective of the condition. I will update with more details by looking into more.

**Comment by harikrongali** [comment]
if this is a issue with notification engine, then we should move this ticket to notification engine repo.

**Comment by geojakes** [comment]
> I verified this it looks like when condition is not taking effect. The notification gets sent irrespective of the condition. I will update with more details by looking into more.

Thanks for verifying this

**Comment by harikrongali** [comment]
@alexmt / @jessesuen  can you please move the ticket to notification engine repo

**Comment by geojakes** [comment]
@harikrongali so is this issue confirmed as a notification engine one?

**Comment by geojakes** [comment]
@harikrongali @RaviHari Any chance there is an update on this issue?

**Comment by RaviHari** [comment]
> @harikrongali @RaviHari Any chance there is an update on this issue?

Hi @geojakes this is a notification issue. I am working on this. I will update this issue once the fix is in place.

**Comment by geojakes** [comment]
@RaviHari Is this being tracked in a different location as well?

**Comment by geojakes** [comment]
@RaviHari What is the release cadence here?
