### ISSUE TITLE
Kustomize Build: rollout deployment always on :latest

### ISSUE THREAD

**Issue by patgmiller** [argoproj/argo-rollouts#1965]
## Summary

When building manifests using `kustomize`, or even `kubectl kustomize`, the resulting deployment manifest has an image tag of `:latest`, instead of using the specified tag version. This is problematic when using a remote bases git URL with tag reference to build manifests, like this `https://github.com/argoproj/argo-rollouts//manifests/cluster-install/?ref=v1.0.7`. 

It leads to two problems

1. A strong likely hood of installing the wrong version of `argo-rollouts` which is newer than what you might want.
2. Updates may have no affect because container runtimes will not pull any new image tags without being forced since it has a policy of `imagePolicy: NotIfExists` in the manifest.

## Diagnostics

I found this while upgrading from the argo-rollouts `v0.10.2` version, and it can be reproduced with other tags of `argo-rollouts`. You can substitue `v1.1.1` or `v1.2.0` in the `argo-rollouts` example below, and I have used a `git clone` instead of the git URL for reliability.

Also, if you use the `v2.2.8` or `v2.3.3` versions of `argo-cd` you will see the image tags are respected while `argo-rollouts` tags are always using `latest`.

```
mkdir remote example out
git clone -b v1.0.7 --depth 1 https://github.com/argoproj/argo-rollouts.git remote/argo-rollouts
git clone -b v2.1.11 --depth 1 https://github.com/argoproj/argo-cd.git remote/argo-cd
cat <<EOF >example/kustomization.yaml
bases:
  - ../remote/argo-rollouts/manifests/cluster-install
  - ../remote/argo-cd/manifests/cluster-install

namespace: foobar
EOF
kustomize build example -o out
grep -rHni "image: q" out
```

The above will produce the following:

```
grep -rHni "image: q" out
out:15863:      - image: quay.io/argoproj/argo-rollouts:latest
out:15926:        image: quay.io/argoproj/argocd:v2.1.11
out:16109:        image: quay.io/argoproj/argocd:v2.1.11
out:16359:        image: quay.io/argoproj/argocd:v2.1.11
out:16550:        image: quay.io/argoproj/argocd:v2.1.11
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by patgmiller** [comment]
I am aware that depending on which version of `kubectl` or `kustomize` one is using there is a work around by putting the following in the `kustomize.yaml` file

```
images:
  - name: quayio/argoproj/argo-rollouts
    newTag: v1.0.7 # or whatever version you're installing
```

However, the purpose of `kustomize` is to be able to patch in only your own changes so this should probably be fixed in the source project. I'll submit an fix if and when I have some time. So for now I just wanted to bring it up.

**Comment by harikrongali** [comment]
dup of https://github.com/argoproj/argo-rollouts/issues/1641 

We no longer commit the install manifests into git with hardwired versions because it complicated the release process. Instead, we attach install manifests to the release. You can change your kustomization to reference this instead:

https://github.com/argoproj/argo-rollouts/releases/download/v1.0.7/install.yaml
