### ISSUE TITLE
allow prometheus AnalysisTemplate use secret for address and authentication

### ISSUE THREAD

**Issue by templarfelix** [argoproj/argo-rollouts#1976]
# Summary
What change needs making?

allow use secret for set address and headers for prometheus AnalysisTemplate.

# Use Cases
When would you use this?

the same technique of datadog AnalysisTemplate integration https://argoproj.github.io/argo-rollouts/analysis/datadog/

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by harikrongali** [comment]
i believe https://github.com/argoproj/argo-rollouts/pull/1956 solve this use case

@RaviHari can you please confirm

**Comment by templarfelix** [comment]
Yes thanks @harikrongali
