### ISSUE TITLE
Allow selecting datasource for grafana dashboard

### ISSUE THREAD

**Issue by jcantosz** [argoproj/argo-rollouts#1987]
# Summary

What change needs making?
The Grafana dashboard example does not allow selecting a datasource for the workflow templates. If one Grafana is used for multiple rollouts instance this means one dashboard for each is needed.

# Use Cases

When would you use this?
When monitoring multiple argo-rollouts data sources from one Grafana dashboard.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment]
fixes #1987
