### ISSUE TITLE
notification error: 550 User has no permission

### ISSUE THREAD

**Issue by 13567436138** [argoproj/argo-rollouts#2012]
## Summary 

What happened/what you expected to happen?
send email notification success
## Diagnostics

What version of Argo Rollouts are you running?
[root@node01 ~]# kubectl argo rollouts version
kubectl-argo-rollouts: v1.2.0+08cf10e
  BuildDate: 2022-03-22T00:25:11Z
  GitCommit: 08cf10e554fe99c24c8a37ad07fadd9318e4c8a1
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
```
# Paste the logs from the rollout controller
time="2022-05-01T03:01:44Z" level=error msg="notification error: 550 User has no permission"
time="2022-05-01T03:01:44Z" level=error msg="Notifications failed to send for eventReason RolloutStepCompleted with error: 550 User has no permission" event_reason=RolloutStepCompleted namespace=istio rollout=reviews-v1
time="2022-05-01T03:01:54Z" level=error msg="notification error: 550 User has no permission"
time="2022-05-01T03:01:54Z" level=error msg="Notifications failed to send for eventReason RolloutStepCompleted with error: 550 User has no permission" event_reason=RolloutStepCompleted namespace=istio rollout=reviews-v1
# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment]
This looks to be an error from notification-engine it also seems to be coming from what ever service your trying to send the notification too. That service is having trouble authenticating with whatever user you have it configured to try and use.
