### ISSUE TITLE
shell completion: `kubectl-argo-rollouts get rollout TAB` does not auto completes the rollout names

### ISSUE THREAD

**Issue by thomas-riccardi** [argoproj/argo-rollouts#2015]
## Summary 

I'm following the getting started guide on linux with auto completion on bash (https://argoproj.github.io/argo-rollouts/getting-started/).

When I hit TAB after `kubectl-argo-rollouts get rollout`, it does not auto completes the rollout names as I would expect. (for example `kubectl get pod TAB` does auto completes with existing pod names.)

It would be really useful for discovery of what's inside the cluster.

## Diagnostics

What version of Argo Rollouts are you running?

v1.2.0 server and kubectl plugin, on linux, bash.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment]
I will take this

**Comment by thomas-riccardi** [comment]
I've started working on it in #2379, with several questions there
