### ISSUE TITLE
Need scale cmd

### ISSUE THREAD

**Issue by jinleileiking** [argoproj/argo-rollouts#2025]
``` kubectl scale --replicas=0  deployment/xxx```

not exists in argo cmd

**Comment by danielhelfand** [comment]
The `kubectl scale` command works with Rollouts just like Deployments like below:

```
kubectl scale rollouts/rollouts-demo --replicas=0
```

Perhaps this should be documented somewhere though. Not sure if it's mentioned anywhere in docs.
