### ISSUE TITLE
Traffic flaps back to stable during canary promotion

### ISSUE THREAD

**Issue by iandelahorne** [argoproj/argo-rollouts#2064]
## Summary 
I believe this is similar to  https://github.com/argoproj/argo-rollouts/issues/1826

I am evaluating Argo Rollouts on EKS, using the AWS ALB controller for managing ingress. I've noticed while using the [demo app](https://github.com/argoproj/rollouts-demo) using a canary deployment with the manifests from the [getting-started/alb](https://github.com/argoproj/argo-rollouts/tree/master/docs/getting-started/alb) section of the docs, traffic will flap back for about 30s to the previous stable version when promoting to full.

The current canary steps are set to go to 10% automatically, then 50% and 100% in manual steps.

### What happened/what you expected to happen?

Here's a screenshot from the example app showing the behavior:
![Screen Shot 2022-05-31 at 7 24 22 PM](https://user-images.githubusercontent.com/184966/171445746-4cd8da58-d3dc-4ec2-9a7b-90b88cd3d209.png)

I expected traffic to ramp to the new purple version instead of flapping back to yellow for a brief moment.
When observingat the ALB target weighting rules, they're being set correctly - first splitting 10% traffic to the canary service's target group, then 50% canary/stable, then 100% to the stable target group.

### What version of Argo Rollouts are you running?

* Argo Rollouts v1.2.1
* AWS EKS 1.22
* AWS ALB controller 2.4.1

Debug logs from the rollout controller are available [here](https://gist.github.com/iandelahorne/9d6289799dd024b1e193a5af074a078d)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by perenesenko** [comment]
I've checked the issue and could reproduce it. I thought the [TargetGroup weight and IP](https://argoproj.github.io/argo-rollouts/features/traffic-management/alb/#targetgroup-weight-verification) verification would solve the issue but it's still there.

I found that the weight-changing functionality works fine (with TargetGroup verification enabled) when shifting traffic to 10, 50, 80. but the issue happened when traffic switched 100% to **canary**, service labels switched and sent 100% back to the **stable**. 
My assumption is that on the AWS side the changes reflected with a delay and traffic switched to the stable before the labels switched.

I could check also the [ping-pong feature](https://argoproj.github.io/argo-rollouts/features/traffic-management/alb/#zero-downtime-updates-with-ping-pong-feature) that was developed exactly for this kind of issue. And it solves this problem.

**Comment by iandelahorne** [comment]
@perenesenko thanks for confirming that you can reproduce.

Yes, from what I observe the Target Group weight is being managed correctly and without delay (that is, during the period traffic flaps back to stable, the weight is set correctly to go 100% to the "stable" service). It seems the rollouts controller is shifting weight to 100% stable before the stable service has updated to the new labels.

I'm experimenting with the ping-pong feature and I can confirm that for shifting production traffic it works great. However, if I expose the canaryService via the ALB on a separate Ingress, I am seeing that it takes longer to update the canary to the new version (60-120s vs 10s without ping-pong), and in addition it will flap between the stable and canary version on the canary ingress for about 15-20s - I don't see this behavior without ping-pong.

**Comment by ryanpagel** [comment]
I've also experienced the same issue.  So, the solution is to use the Ping-pong feature?

**Comment by ryanpagel** [comment]
Looks like I may not be able to use the Ping-Pong feature since my Ingress target type is Instance not IP.  Is there any other workaround for dealing with the initial issue of flapping back to stable for 30s at the end?
