### ISSUE TITLE
Argo Rollouts will mark a rollout in-progress after it is completed.

### ISSUE THREAD

**Issue by MarkSRobinson** [argoproj/argo-rollouts#2068]
## Summary 

If a finished deploy loses some pods (eg, a node is deleted), argo will mark the deploy as in-progress again.  It will continue to be in progress until all the pods are available again.

Once a rollout has finished, it should never go back to in-progress.

## Diagnostics

What version of Argo Rollouts are you running?

1.2.0

```
  - lastTransitionTime: '2022-06-02T23:13:31Z'
      lastUpdateTime: '2022-06-02T23:13:31Z'
      message: RolloutCompleted
      reason: RolloutCompleted
      status: 'False'
      type: Completed
```

```
NAMESPACE  NAME          STRATEGY   STATUS        STEP  SET-WEIGHT  READY    DESIRED  UP-TO-DATE  AVAILABLE
cs-team    batch-server  Canary     Progressing   8/8   100         448/450  450      450         448
```

This particular deploy finished 2 hours earlier and the node auto-scaler was rebalancing some nodes when this happened.  It had removed some nodes that it didn't need anymore which causes the deployment to shift back to in-progress.  I didn't see if it was running any analyses.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by harikrongali** [comment]
that is expected behavior. Rollout in progress doesn't mean there is ongoing deployment. When pods are not available, Rollout status changes to progress until pods are available. It follows the Kubernetes Deployment resource in calculating the health state.
