### ISSUE TITLE
Maybe problem with cluster-autoscaler when evicting pods for draining node

### ISSUE THREAD

**Issue by jinleileiking** [argoproj/argo-rollouts#2093]
## Summary 

See https://github.com/kubernetes/autoscaler/issues/4966

**Comment by perenesenko** [comment]
@jinleileiking 
Argo Rollouts doesn't control the pods directly only by replica sets.
So I don't think it's a Rollouts controller causing this issue.

**Comment by jinleileiking** [comment]
cluster-autoscaler uses evict. I do not know if this is the reason related. I will test
