### ISSUE TITLE
kubectl argo rollouts dashboard OOM kill

### ISSUE THREAD

**Issue by kzcPo** [argoproj/argo-rollouts#2095]
## Summary 

What happened/what you expected to happen?
`kubectl argo rollouts dashboard` high memory usage.
![image](https://user-images.githubusercontent.com/16077203/173475284-e7abd2a3-1c68-4d6a-bc6e-816cf1d65790.png)

before long time, this pod OOM kill!!

## Diagnostics

```
kubectl-argo-rollouts: v1.2.1+51c874c
  BuildDate: 2022-05-13T20:40:45Z
  GitCommit: 51c874cb18e6adccf677766ac561c3dbf69a8ec1
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by perenesenko** [comment]
@kzcPo Could you provide steps to reproduce?
How many rollouts
Manifest for rollout

**Comment by kzcPo** [comment]
你好，我已经收到邮件！

**Comment by kzcPo** [comment]
你好，我已经收到邮件！

**Comment by kzcPo** [comment]
你好，我已经收到邮件！

**Comment by kzcPo** [comment]
你好，我已经收到邮件！

**Comment by kzcPo** [comment]
你好，我已经收到邮件！

**Comment by m-shalenko** [comment]
Hello, guys! Are there any updates?

**Comment by kzcPo** [comment]
你好，我已经收到邮件！

**Comment by michellebeard** [comment]
Hello! Are there any updates. I have also observed a similar behavior with Argo Rollouts Dashboard being OOM killed due to rising memory. We expect that there is a memory leak.

**Comment by ppaez-life360** [comment]
We observed a similar behavior. The memory usage will increase over time, and it will stop only when the pod is terminated (the screenshot from above is from a cluster with ~20 rollouts):
<img width="500" alt="Screenshot 2024-10-02 at 10 38 39" src="https://github.com/user-attachments/assets/983c834b-ac7b-4cd1-9adc-89ab0a4ddfcc">
