### ISSUE TITLE
Support gradual increase of replicas for traffic shaped canary

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#21]
There are two conflicting use cases with **traffic-shaped** canary (as opposed to replicaset-based canary).

1. After changing the weight of a canary, the amount of traffic directed at the canary could be disproportionate to the scale, and overwhelm the pods. In this case, we would only want to set the weight in a gradual manner and eventually reach the target weight for the canary.

2. The weight set on a canary should be instantaneous despite disproportionate number of replicas. For example, going from 100% old, to 100% new atomically.

We need to allow users to be able to configure which of the two modes should happen when weights are set.

**Comment by dthomson25** [comment]
The current implementation solves for both use cases.
