### ISSUE TITLE
Unable to scrap controller_clientset_k8s_request_total metric

### ISSUE THREAD

**Issue by Pratyush-123** [argoproj/argo-rollouts#2139]
Checklist:

* [ ] I've included steps to reproduce the bug.
* [X] I've inclued the version of argo rollouts.

**Describe the bug**
I am trying to run a forked version of argo rollouts v1.2. The Argo Rollout Controller is working fine but I am unable to scrap `controller_clientset_k8s_request_total` metric.  As per the doc this metric should be there.

**To Reproduce**

**Expected behavior**
Argo rollout controller should produce all the given metrics.

**Screenshots**
<img width="1781" alt="Screenshot 2022-07-13 at 11 42 22 AM" src="https://user-images.githubusercontent.com/50448016/178663299-e2d23ab2-fd52-4f90-a4fb-9ef019d442f6.png">

**Version**
V1.2.0

**Logs**

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by nikhil1raghav** [comment]
Can anyone @harikrongali  @jessesuen  please assign this to me? From what I have found out these metrics shouldn't be working from v1.1.0 as well.

Kubeclient is initialized before adding metrics roundtripper to the config.
