### ISSUE TITLE
Add testkube analysis provider

### ISSUE THREAD

**Issue by marcportabellaclotet-mt** [argoproj/argo-rollouts#2157]
# Summary

What change needs making?

It would be interesting to add [teskube](https://kubeshop.github.io/testkube/) as analysys provider.
Testkube is a very useful framework which integrates a lof od testing tools like postman,cypress,k6s...
It has a very well defined API, and it returns the execution test results.

# Use Cases

When would you use this?

It is already possible to run a job and run testkube test, and exit the pod based on the results. (I am already using this approach)
However, I think that a native integration, will be very useful. 
I know this requires a lot of work, and I am just sharing the idea here.

Congrats for such amazing software!!
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by kostis-codefresh** [comment]
Argo Rollouts now supports plugins. So this doesn't need to be implemented in the core Argo Rollout code.

Anybody should be able to write a plugin on their own for this https://argo-rollouts.readthedocs.io/en/stable/analysis/plugins/

**Comment by marcportabellaclotet-mt** [comment]
That makes sense.
