### ISSUE TITLE
Leverage pod-template-hash label instead of rollout-pod-template-hash

### ISSUE THREAD

**Issue by dthomson25** [argoproj/argo-rollouts#219]
In order to have better compatibility with existing external Kubernetes solutions, the rollouts object should use the pod-template-hash instead of the rollout-pod-template-hash.  pod-template-hash is the label used by the deployment controller and other tools have used this label before (i.e. heapster). This is not a non-trivial change because we use the rollout-pod-template-hash to direct traffic via services, and we will need to make sure we have a well-tested migration path.

**Comment by jessesuen** [comment]
Closing wont-fix. But in the future, we may be able to support this via: https://github.com/argoproj/argo-rollouts/issues/455
