### ISSUE TITLE
Implicit understanding of rollback based on steps completion and pod hash

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#22]
In the case of an emergency rollback where the N-1 revision of manifests were re-applied, and the rollout strategy contains unfinished steps, we have difficulty understanding whether or not the steps logic should be repeated (e.g. a gradual canary), vs. moving as fast as possible back to the N-1 revision (due to a rollback). 

The proposal is to have implicit behavior where if the steps were not completed for the current rollout, and we are moving towards the N-1 revision of manifests, the entire steps logic should be skipped.

**Comment by dthomson25** [comment]
Implemented by #30
