### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by oke-py** [argoproj/argo-rollouts#221]
Some PRs, for example #162, are not reflected on https://argoproj.github.io/argo-rollouts/ .
The documentation is not automatically updated?
Are there any problems?

**Comment by dthomson25** [comment]
Hey @oke-py thank you for pointing this issue out. The process isn't automated yet, and I have updated the docs now. Please let me know if you are still seeing out of date docs!

**Comment by oke-py** [comment]
thanks!
