### ISSUE TITLE
Argo Rollouts pods crashing with failed to sync informer error

### ISSUE THREAD

**Issue by Sonam11** [argoproj/argo-rollouts#2232]
**Description** 
We are using workloadRef, in our services default configs, and when Argo Rollouts trying to sync the rollout objects, it uses a generic informer (which is not a shared informer) and when syncing with this informer, it fails, retries few times.. and fails again and then kills the pod and new pods gets started again and intermittently it starts happening again.
Debugging done so far: Our analysis of this error seems to be that this sync informer is timing out the timeout being set to 60s, but it's not reproducible in local setup. The error is happening for the new elected pod too, which should be fresh in terms of resources, so it shouldn't be resource crunch too. Need some help to understand this issue better.

The current version of Argo Rollouts we are using is V1.0, the issues is the pods are continuously restarting after sometime due to the error:

`"The Rollout "adobetest" is invalid: failed to sync informer for apps/v1, Kind=Deployment\" namespace=ns-team-test rollout=adobetest"`

**Possible resolution till we have exact solution:**

- We increase the timeout for sync? We are not sure of that as this timeout thing is not reproducible?
- Should we use shared informer for deployments too, like we do for other resources like services and all?
- Shouldn't use workloadref for all our services in cluster, it causes the sync informer to be loaded and possibly causing the timeout?

**Comment by zachaller** [comment]
Have you tried to reproduce this on v1.2.2 or the 1.3-rc?
