### ISSUE TITLE
Letter "L" doesn't work after navigating to a rollout details page

### ISSUE THREAD

**Issue by Cylix** [argoproj/argo-rollouts#2273]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've included the version of argo rollouts.

**Describe the bug**

Search inputs on the UI do not accept the letter "L" after navigating to a rollout details page.

The bug only seem to affect the letter "L". It is probably due to a shortcut implementation since the letter "L" seems to be used for navigating back to the dashboard root page.

**To Reproduce**

1. Navigate to the Argo Rollouts Dashboard
2. Try to input the letter "L" in the namespace or rollout search bars: it works 👍 
3. Navigate to a Rollout Details Page
4. Try to input the letter "L" in the namespace or rollout search bars: it doesn't work anymore 🤯  

**Expected behavior**

We should be able to input the letter "L" in search inputs.

**Screenshots**

**Version**

`v1.2.1+51c874c`

**Logs**

No logs, this is a UI issue. There are no logs in the browser console.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by dcortright** [comment]
@zachaller I would like to take this up for Hacktoberfest.

**Comment by zachaller** [comment]
Sounds good and thanks for jumping in. Feel free to reach out if you need anything!
