### ISSUE TITLE
Rollout resource not modify VirtualService

### ISSUE THREAD

**Issue by mihneastaub** [argoproj/argo-rollouts#2314]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've inclued the version of argo rollouts.

**Describe the bug**

I have upgraded the ArgoRollouts operator to the latest version v1.3.1, the problem is that the VirtualService resource is not modified by the Rollout. The destinationRule is modified as expected.

**To Reproduce**

Need to have istio deployed in the cluster and use subset-level method.

**Expected behavior**

Rollout resource should also modify the VirtualService.

**Screenshots**

**Version**

**Logs**

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by iam-veeramalla** [comment]
Hi @mihneastaub what is the change that you are expecting ? Can you please provide that details ?

**Comment by mihneastaub** [comment]
Hello @iam-veeramalla,

Thank you for the response.

As described in the [documentation](https://github.com/argoproj/argo-rollouts/blob/master/docs/features/traffic-management/istio.md#:~:text=Rollouts%20will%20continuously%3A-,modify%20the%20VirtualService%20spec.http%5B%5D.route%5B%5D.weight%20to%20match%20the%20current%20desired%20canary%20weight,-modify%20the%20DestinationRule), the Rollout resource should modify the weight of the VirtualService resource also. In my case this is not happening.

**Comment by iam-veeramalla** [comment]
Thanks @mihneastaub because you have mentioned about the upgrade, Can I assume it was working as expected before the upgrade ?

**Comment by mihneastaub** [comment]
Yes, I have used `v1.2.1` version and is worked as expected. After I have made the upgrade to the latest version `v1.3.1` this modification of the `VirtualService` is not working for me.

I want to mention that the modification of the DestinationRule resource is done correctly.

**Comment by mihneastaub** [comment]
@iam-veeramalla, those are the events inside of the Rollout resource.

![image](https://user-images.githubusercontent.com/57804495/195281912-f14bb542-1a22-45d0-a2d1-63f87f5bbc05.png)

From what I see, is mention in the events `TrafficWeightUpdated` but is not mention that the `VirtualService `was modified  like it does with the `DestinationRule`.

**Comment by iam-veeramalla** [comment]
Hi @mihneastaub , 

It's working fine for me. Please check below.

**Rollouts Version**:
`quay.io/argoproj/argo-rollouts:v1.3.1`

**ScreenShot of Rollout**:

![Screenshot 2022-10-12 at 5 21 01 PM](https://user-images.githubusercontent.com/43399466/195336012-d5e01e3b-b0dd-48db-8007-f13b9ab3cd5e.png)


**ScreenShot of VitualService Update**:

![Screenshot 2022-10-12 at 5 21 21 PM](https://user-images.githubusercontent.com/43399466/195336029-9f37048b-dcd5-469d-b848-5521312f1801.png)

And overall Rollout looks good to me. This is the example that I used.
https://raw.githubusercontent.com/argoproj/argo-rollouts/1ee46cff2a3203fd2da7d540c9fd25c8a61900c2/test/e2e/istio/istio-subset-split.yaml

**Comment by mihstaub** [comment]
Hello @iam-veeramalla,

Thank you very much for investigating this.

It seems that my problem was resolved using the routes name inside of the Rollout resource. But from what I understand from the documentation, is optional if there is a single route in VirtualService, required otherwise.

So, I think is problem with the documentation as for me is working without adding the name of the routes for the version `v1.2.1`.

**Comment by mihneastaub** [comment]
Hello @iam-veeramalla,

Thank you very much for investigating this.

It seems that my problem was resolved using the routes name inside of the Rollout resource. But from what I understand from the documentation, is optional if there is a single route in VirtualService, required otherwise.

So, I think is problem with the documentation as for me is working without adding the name of the routes for the version `v1.2.1`.

**Comment by iam-veeramalla** [comment]
so @mihneastaub can we close this issue ?

**Comment by mihneastaub** [comment]
Yes, we can close this issue, but the documentation should enhanced for this problem.
