### ISSUE TITLE
Dashobard namespace picker requires to text deletion to show full list of namespaces

### ISSUE THREAD

**Issue by lukpep** [argoproj/argo-rollouts#2317]
**Describe the bug**

Is this the desired behaviour?
![CleanShot 2022-10-12 at 16 21 22](https://user-images.githubusercontent.com/2960580/195369533-8996d0b3-f6cd-415d-9572-0e3802e29aef.gif)

In order to view the full list of namespaces with rollout objects I need to delete the namespace name first.

**To Reproduce**

Install 2 rollouts in 2 separate namespaces and dashboard in standard argo-rollouts namespace

**Expected behavior**

Full list of namespaces available always - even when one of the namespaces is selected

**Version**

v1.3.1+b0b95ca

**Logs**

no logs from dashboard or controller are produced during the problem

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment]
This is I feel expected behavior based on it being a filtered list. A filtered lists I feel works best when there are a lot of namespaces.

**Comment by lukpep** [comment]
I can understand the convenience of filtering the list - but at the same time, I feel that it should work differently:
* user clicks the dropdown
* all namespaces are visible (not all rollouts - all namespaces)
* user can choose one
* rollouts from that namespace are presented
* user clicks dropdown again, and all namespaces are visible - if one wants, one can filter it by writing something but by default user should not be required to "erase" the namespace name in order to view a full list of the namespaces.
