### ISSUE TITLE
Bring CLOMonitor score to 100%

### ISSUE THREAD

**Issue by eddie-knight** [argoproj/argo-rollouts#2329]
As Argo is signed up for the Security Slam, this issue is to track the efforts necessary to bring argo-rollouts [CLOMonitor](https://clomonitor.io/projects/cncf/argo) score to 100%.

### Summary

**Repository**: argo-rollouts
**URL**: https://github.com/argoproj/argo-rollouts
**Checks sets**:  `CODE`
**Score**: 86

### Checks passed per category

| Category  |  Score  |
| :----------------- | --------: |
|  Documentation  |  100%  |
|  License  |  75%  |
|  Best Practices  |  94%  |
|  Security  |  80%  |
|  Legal  |  n/a  |

### Documentation [100%]

  - [x] [Changelog](https://github.com/argoproj/argo-rollouts/blob/master/CHANGELOG.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#changelog))
  - [x] [Contributing](https://github.com/argoproj/argo-rollouts/blob/master/docs/CONTRIBUTING.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#contributing))
  - [x] [Maintainers](https://github.com/argoproj/argo-rollouts/blob/master/OWNERS) ([_docs_](https://clomonitor.io/docs/topics/checks/#maintainers))
  - [x] [Readme](https://github.com/argoproj/argo-rollouts/blob/master/README.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#readme))
  
### License [75%]

  - [x] Apache-2.0 ([_docs_](https://clomonitor.io/docs/topics/checks/#license_spdx_id))
  - [x] Approved license ([_docs_](https://clomonitor.io/docs/topics/checks/#license_approved))
  - [ ] License scanning ([_docs_](https://clomonitor.io/docs/topics/checks/#license_scanning))
  
### Best Practices [94%]

  - [x] Artifact Hub badge ([_docs_](https://clomonitor.io/docs/topics/checks/#artifacthub_badge))
  - [x] Contributor License Agreement ([_docs_](https://clomonitor.io/docs/topics/checks/#cla)) `EXEMPT`
  - [x] Developer Certificate of Origin ([_docs_](https://clomonitor.io/docs/topics/checks/#dco))
  - [x] [OpenSSF badge](https://bestpractices.coreinfrastructure.org/projects/3834) ([_docs_](https://clomonitor.io/docs/topics/checks/#openssf_badge))
  - [x] [Recent release](https://github.com/argoproj/argo-rollouts/releases/tag/v1.2.0-rc1) ([_docs_](https://clomonitor.io/docs/topics/checks/#recent_release))
  
### Security [80%]

  - [x] Binary artifacts ([_docs_](https://clomonitor.io/docs/topics/checks/#binary_artifacts))
  - [x] Code review ([_docs_](https://clomonitor.io/docs/topics/checks/#code_review))
  - [x] Dangerous workflow ([_docs_](https://clomonitor.io/docs/topics/checks/#dangerous_workflow))
  - [x] Dependency update tool ([_docs_](https://clomonitor.io/docs/topics/checks/#dependency_update_tool))
  - [x] Maintained ([_docs_](https://clomonitor.io/docs/topics/checks/#maintained))
  - [x] Software bill of materials (SBOM) ([_docs_](https://clomonitor.io/docs/topics/checks/#sbom))
  - [x] [Security policy](https://github.com/argoproj/argo-rollouts/blob/master/docs/security.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#security_policy))
  - [ ] Signed releases ([_docs_](https://clomonitor.io/docs/topics/checks/#signed_releases))
  - [x] Token permissions ([_docs_](https://clomonitor.io/docs/topics/checks/#token_permissions))
  
For more information about the checks sets available and how each of the checks work, please see the [CLOMonitor's documentation](https://clomonitor.io/docs/topics/checks/).

**Comment by zachaller** [comment]
Releases are now signed https://quay.io/repository/argoproj/argo-rollouts?tab=tags
