### ISSUE TITLE
Document cosign verification

### ISSUE THREAD

**Issue by zachaller** [argoproj/argo-rollouts#2353]
Now that we have signed images we should also document how to verify them argocd has done this via https://github.com/argoproj/argo-cd/pull/10967 and also possibly provide link to https://docs.sigstore.dev/cosign/overview/#kubernetes-integrations

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by skodamarthi** [comment]
@zachaller Can I work on this? Should we use the same public key in ArgoCD or a different one?

**Comment by 34fathombelow** [comment]
@skodamarthi you would use [this public key](https://github.com/argoproj/argo-rollouts/pull/2334#issuecomment-1284538907).  Feel free to ask any questions if you need help.
