### ISSUE TITLE
Add LightStep as a provider for Analysis Templates

### ISSUE THREAD

**Issue by ssanders1449** [argoproj/argo-rollouts#2371]
My company is moving to use LightStep (https://lightstep.com/) for metrics and alerting. We have existing rollouts that are using Prometheus for analysis, and we would like to port them to using the Lighstep Observability APIs (https://api-docs.lightstep.com/reference/overview)

**Comment by zachaller** [comment]
After taking a brief look at the API here https://api-docs.lightstep.com/reference/querytimeseries-1 do you think using something like argo rollouts web metric [provider](https://argoproj.github.io/argo-rollouts/analysis/web/) or even possibly something like the [job](https://argoproj.github.io/argo-rollouts/analysis/job/) to accomplish what you need?

**Comment by ssanders1449** [comment]
Yes I think that using the web provider will be a good solution
