### ISSUE TITLE
rollout_phase is marked deprecated in code but not the docs

### ISSUE THREAD

**Issue by blkperl** [argoproj/argo-rollouts#2377]
Checklist:

* [x] I've included steps to reproduce the bug.
* [ ] I've inclued the version of argo rollouts.

**Describe the bug**

rollout_phase is marked deprecated in code but not in the docs

- https://github.com/argoproj/argo-rollouts/blob/55a041a6b3d088cf9ddcfc4121ad8c97880489db/controller/metrics/prommetrics.go#L69-L75
- https://argoproj.github.io/argo-rollouts/features/controller-metrics/

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by iam-veeramalla** [comment]
I will add the deprecation notice to the docs. Assigning it to myself.
