### ISSUE TITLE
Apache APISIX support

### ISSUE THREAD

**Issue by daurnimator** [argoproj/argo-rollouts#2395]
# Summary

I was evaluating APISIX and found that Argo rollouts doesn't support it for traffic splitting.

From https://argoproj.github.io/argo-rollouts/features/traffic-management/#how-does-argo-rollouts-enable-traffic-management
> File a ticket [here](https://github.com/argoproj/argo-rollouts/issues) if you would like another implementation (or thumbs up it if that issue already exists)

APISIX supports traffic management via its CRD: https://apisix.apache.org/docs/ingress-controller/concepts/apisix_route/#weight-based-traffic-split

# Use Cases

When using APISIX as your ingress controller

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by Gallardot** [comment]
Maybe I can try to make it happen.

**Comment by mubarak-j** [comment]
API Gateway support in PR#2004 will at least cover Gateway Class/http routes use cases of APISIX

**Comment by tao12345666333** [comment]
Hi, I'm Jintao, Apache APISIX PMC member.

I am very glad to see that you have discussions related to APISIX, which shows that APISIX has been known by more and more people.

Currently, Apache APISIX Ingress controller supports three configuration methods.

- Ingress
- APISIX's CRD
- Gateway API

The first two have been GA a long time ago, and are used by a large number of users in the production environment.

However, the support for the Gateway API is currently in the alpha stage and cannot be used in production.
So, if you want to provide support for it, I recommend doing it through APISIX's CRD.


We are currently actively adding support for the Gateway API, but it may take some time before it reaches GA.

Thanks!
