### ISSUE TITLE
Argo Rollout Notifications - Triggers one notification per controller pod

### ISSUE THREAD

**Issue by tomellis91** [argoproj/argo-rollouts#2556]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've inclued the version of argo rollouts.

**Describe the bug**

Argo Rollouts Notifications fires duplicate messages when running multiple controller pods. 

**To Reproduce**
- Run more that 1 copy of the Argo Rollouts Controller
- Trigger a notification

**Expected behavior**
- Only a single notification should fire per issue

**Version**
- v1.4.0

**Logs**
![Screen Shot 2023-02-02 at 12 09 05 pm](https://user-images.githubusercontent.com/2328655/216206243-beefca5d-71b4-4a04-9cb0-965028a23546.png)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by nodox** [comment]
Did we find a fix for this?
