### ISSUE TITLE
Rollout repeatedly entering pause state after inconclusive AnalysisRun

### ISSUE THREAD

**Issue by dthomson25** [argoproj/argo-rollouts#261]
If a user continues a rollout that was paused for an inconclusive run, the rollout will continue to enter a paused state if the next AnalysisRun created is inconclusive. In this case, the user wants the rollout to proceed, that user has to skip all the steps or change the AnalysisTemplate to make the AnalysisRun consider the inconclusive Run into successful. If the user thinks the inconclusive run is acceptable, the rollout should be able to proceed through the steps instead of a repeated loop.

**Comment by jessesuen** [comment]
Could we introduce a command, `kubectl argo rollouts progress` to bump up the step index to solve this use case?

**Comment by jessesuen** [comment]
Probably `kubectl argo rollouts resume --skip-step` is better.

**Comment by jessesuen** [comment]
This is available now in `kubectl argo rollouts promote --skip-current-step`
