### ISSUE TITLE
Error when experiment running is invalid: [spec.ports[0].name: Required value, spec.ports[1].name: Required value, spec.ports[2].name:  

### ISSUE THREAD

**Issue by zakariais** [argoproj/argo-rollouts#2640]
Hey,
We are getting the port name invalid error though all the ports have name defined
Below is out rollout definition
`apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: 'zakaria-test:argoproj.io/Rollout:devops-apps/zakaria-test'
  labels:
    app: zakaria-test
    argocd.argoproj.io/instance: zakaria-test
    chart_version: 2.0.43-dev-zak-2
    commit: latest
    environment: dev
    name: zakaria-test
    owner: general
    project: support
    sidecar.istio.io/inject: 'false'
    team: devops
  name: zakaria-test
  namespace: devops-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zakaria-test
      environment: dev
      owner: general
      project: support
      team: devops
  strategy:
    canary:
      steps:
        - experiment:
            templates:
              - metadata:
                  annotations:
                    yourkit: >-
                      -agentpath:/usr/bin/YourKit-JavaProfiler-2022.3/bin/linux-x86-64/libyjpagent.so=port=10001,listen=all
                  labels:
                    yourkit: 'true'
                name: yourkit
                replicas: 1
                specRef: stable
  template:
    metadata:
      annotations:
        checksum/config: ba131b9efaeca08f06060d2e82530d4d12f8b40d2a83ce1f9af50b9da7e628dc
        yourkit: ''
        yourkitEnabled: 'true'
      labels:
        app: zakaria-test
        chart_version: 2.0.43-dev-zak-2
        commit: latest
        environment: dev
        name: zakaria-test
        owner: general
        project: support
        sidecar.istio.io/inject: 'false'
        team: devops
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - zakaria-test
              topologyKey: kubernetes.io/hostname
      containers:
        - env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: APPNAME
              value: zakaria-test
            - name: ENVNAME
              value: devops-apps
            - name: COMMIT
              value: latest
            - name: COMMIT_ID
              value: latest
            - name: OWNER
              value: general
            - name: YOURKIT
              valueFrom:
                fieldRef:
                  fieldPath: 'metadata.annotations[''yourkit'']'
            - name: JAVA_FLAGS
              value: ' vhvghjvh  $(YOURKIT)'
          image: 'nginx:latest'
          imagePullPolicy: IfNotPresent
          name: zakaria-test
          ports:
            - containerPort: 80
              name: default
            - containerPort: 9133
              name: metrics
            - containerPort: 19000
              name: jmx
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 256Mi
          volumeMounts:
            - mountPath: /etc/podinfo
              name: podinfo
            - mountPath: /etc/new-folder/configmaps
              name: configmaps-volume
      nodeSelector:
        intent: apps
        project: mobile-devops-dev
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
        - downwardAPI:
            items:
              - fieldRef:
                  fieldPath: metadata.labels
                path: labels
              - fieldRef:
                  fieldPath: metadata.annotations
                path: annotations
              - path: cpu_limit
                resourceFieldRef:
                  containerName: zakaria-test
                  divisor: 1m
                  resource: limits.cpu
              - path: cpu_request
                resourceFieldRef:
                  containerName: zakaria-test
                  divisor: 1m
                  resource: requests.cpu
              - path: mem_limit
                resourceFieldRef:
                  containerName: zakaria-test
                  divisor: 1Mi
                  resource: limits.memory
              - path: mem_request
                resourceFieldRef:
                  containerName: zakaria-test
                  divisor: 1Mi
                  resource: requests.memory
          name: podinfo
        - name: configmaps-volume
          projected:
            sources:
              - configMap:
                  name: zakaria-test-first-configmap-2901629760
              - configMap:
                  name: zakaria-test-second-configmap-2046896568`
Experiment definition
`apiVersion: argoproj.io/v1alpha1
kind: Experiment
metadata:
  annotations:
    rollout.argoproj.io/revision: '8'
  creationTimestamp: '2023-03-07T07:38:08Z'
  generation: 6
  labels:
    rollouts-pod-template-hash: 67666fcf68
  name: zakaria-test-67666fcf68-8-0
  namespace: devops-apps
  ownerReferences:
    - apiVersion: argoproj.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: Rollout
      name: zakaria-test
      uid: 7ae7d820-a65b-4d13-b4ca-cad1175dd998
  resourceVersion: '314852306'
  uid: 8bc44d54-d11a-4654-a4ee-be9cca7b0361
spec:
  templates:
    - name: yourkit
      replicas: 1
      selector:
        matchLabels:
          app: zakaria-test
          environment: dev
          owner: general
          project: support
          rollouts-pod-template-hash: 66f4675dd4
          team: devops
          yourkit: 'true'
      service: {}
      template:
        metadata:
          annotations:
            checksum/config: ba131b9efaeca08f06060d2e82530d4d12f8b40d2a83ce1f9af50b9da7e628dc
            yourkit: >-
              -agentpath:/usr/bin/YourKit-JavaProfiler-2022.3/bin/linux-x86-64/libyjpagent.so=port=10001,listen=all
          labels:
            app: zakaria-test
            chart_version: 2.0.43-dev-zak-2
            commit: latest
            environment: dev
            name: zakaria-test
            owner: general
            project: support
            rollouts-pod-template-hash: 66f4675dd4
            sidecar.istio.io/inject: 'false'
            team: devops
            yourkit: 'true'
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - zakaria-test
                  topologyKey: kubernetes.io/hostname
          containers:
            - env:
                - name: HOST_IP
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: status.hostIP
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: spec.nodeName
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.name
                - name: POD_IP
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: status.podIP
                - name: APPNAME
                  value: zakaria-test
                - name: ENVNAME
                  value: devops-apps
                - name: COMMIT
                  value: latest
                - name: COMMIT_ID
                  value: latest
                - name: OWNER
                  value: general
                - name: YOURKIT
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: 'metadata.annotations[''yourkit'']'
                - name: JAVA_FLAGS
                  value: ' vhvghjvh  $(YOURKIT)'
              image: 'nginx:latest'
              imagePullPolicy: IfNotPresent
              name: zakaria-test
              ports:
                - containerPort: 80
                  name: default
                  protocol: TCP
                - containerPort: 9133
                  name: metrics
                  protocol: TCP
                - containerPort: 19000
                  name: jmx
                  protocol: TCP
              resources:
                limits:
                  memory: 256Mi
                requests:
                  cpu: 50m
                  memory: 256Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /etc/podinfo
                  name: podinfo
                - mountPath: /etc/new-folder/configmaps
                  name: configmaps-volume
          dnsPolicy: ClusterFirst
          nodeSelector:
            intent: apps
            project: mobile-devops-dev
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: default
          serviceAccountName: default
          terminationGracePeriodSeconds: 30
          volumes:
            - downwardAPI:
                defaultMode: 420
                items:
                  - fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.labels
                    path: labels
                  - fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.annotations
                    path: annotations
                  - path: cpu_limit
                    resourceFieldRef:
                      containerName: zakaria-test
                      divisor: 1m
                      resource: limits.cpu
                  - path: cpu_request
                    resourceFieldRef:
                      containerName: zakaria-test
                      divisor: 1m
                      resource: requests.cpu
                  - path: mem_limit
                    resourceFieldRef:
                      containerName: zakaria-test
                      divisor: 1Mi
                      resource: limits.memory
                  - path: mem_request
                    resourceFieldRef:
                      containerName: zakaria-test
                      divisor: 1Mi
                      resource: requests.memory
              name: podinfo
            - name: configmaps-volume
              projected:
                defaultMode: 420
                sources:
                  - configMap:
                      name: zakaria-test-first-configmap-2901629760
                  - configMap:
                      name: zakaria-test-second-configmap-2046896568
status:
  conditions:
    - lastTransitionTime: '2023-03-07T07:38:08Z'
      lastUpdateTime: '2023-03-07T07:38:10Z'
      message: Experiment "zakaria-test-67666fcf68-8-0" is progressing.
      reason: ReplicaSetUpdated
      status: 'True'
      type: Progressing
  message: >-
    Failed to create Service for template 'yourkit': Service
    "zakaria-test-67666fcf68-8-0-yourkit" is invalid: [spec.ports[0].name:
    Required value, spec.ports[1].name: Required value, spec.ports[2].name:
    Required value]
  phase: Error
  templateStatuses:
    - availableReplicas: 1
      lastTransitionTime: '2023-03-07T07:38:10Z'
      message: >-
        Failed to create Service for template 'yourkit': Service
        "zakaria-test-67666fcf68-8-0-yourkit" is invalid: [spec.ports[0].name:
        Required value, spec.ports[1].name: Required value, spec.ports[2].name:
        Required value]
      name: yourkit
      readyReplicas: 1
      replicas: 1
      status: Error
      updatedReplicas: 1`
 Is there any solution we can try, i have cross checked all of mappings when we define ports it doesn't work but with ports it works

**Comment by zachaller** [comment]
This is fixed in master and will be fixed in 1.5
