### ISSUE TITLE
doc(examples): interval requires count

### ISSUE THREAD

**Issue by meeech** [argoproj/argo-rollouts#2691]
Was looking at an example. Noticed `examples/cluster-analysis-templates.yaml` doesn't work as is:
```
InvalidSpec: The Rollout "scratch-chart" is invalid: spec.strategy.canary.steps[1].analysis.templates: Invalid value: "always-pass": AnalysisTemplate always-pass has metric pass which runs indefinitely. Invalid value for count: <nil>
```

Checklist:

* [ n/a ] I've included steps to reproduce the bug.
* [ n/a ] I've included the version of argo rollouts.

**Describe the bug**

Example wasn't working, since interval needed a count in this case.

**To Reproduce**

try to use `examples/cluster-analysis-templates.yaml` as a step in rollout

**Expected behavior**

**Screenshots**

**Version**

**Logs**

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by agrawroh** [comment]
Could you provide more information on what version of ArgoRollouts you are using? I wouldn't expect it to fail as the docs clearly say: "If both interval and count are omitted, the effective count is 1. If only interval is specified, metric runs indefinitely."

I would expect the analysis to keep running indefinitely in absence of the `count`.
