### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by kalpanathanneeru21** [argoproj/argo-rollouts#2718]
is v1.5.0-rc1 release is compatible with EKS 1.22.17?
if not, which version can be used for supporting EKS 1.22 and 1.23 since we are observing vulnerability issue related k8s version.

**Comment by zachaller** [comment]
It should be compatible, I will try to upgrade k8s deps for 1.5 as well.

**Comment by kalpanathanneeru21** [comment]
when we can expect 1.5 stable version.
