### ISSUE TITLE
GKE Ingress Rollout Support

### ISSUE THREAD

**Issue by 333miiko** [argoproj/argo-rollouts#2725]
# Summary

I would love to use argocd rollout with gke autopilot, which really pushes you down the path of using gke's inbuilt ingress controller. Please provide a plugin for gke ingress :) Thanks

# Use Cases

GKE autopilot doesn't allow other ingress like isito and really pushes to use their inbuilt ingress controller

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment]
With plugin support in 1.5 this can be implemented as a plugin now.

**Comment by kostis-codefresh** [comment]
@333miiko Google cloud support is now available via the Gateway API :-) 

See https://argo-rollouts.readthedocs.io/en/latest/features/traffic-management/google-cloud/
