### ISSUE TITLE
Improve examples to be demo & use-case friendly

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#273]
Some examples don't do well as a demo, or doesn't show the use case well. Examples should be ready for either mode.

**Comment by dthomson25** [comment]
Fixed by:
- https://github.com/argoproj/argo-rollouts/pull/535
- https://github.com/argoproj/argo-rollouts/pull/548
- https://github.com/argoproj/argo-rollouts/pull/565
- https://github.com/argoproj/argo-rollouts/pull/590
