### ISSUE TITLE
Access Issues for Rollouts Dashboard 

### ISSUE THREAD

**Issue by talitz** [argoproj/argo-rollouts#2738]
Hi, 

I have issues making the dashboard work out-of-the-box using ArgoRollouts chart version 2.23.0 on k8s cluster v1.22.17-eks.
It seems like permissions are missing:

`:jfrog-argo-rollouts-dashboard" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace
`
I tried to manually add the different permissions, but it still didn't work... anyone experience issues with the dashboard as well?

As a workaround, I use `kubectl argo rollouts dashboard` which works locally, but I want to provide a dashboard url per region where argo rollouts is used.

**Comment by zachaller** [comment]
This is not an issue with rollouts per say, the helm charts are maintained by a different community I would reach out over there to see how to properly configure rbac for the dashboard. I briefly saw some mention of dashboard config but looking at the chart it also looks like something might be missing when comparing https://github.com/argoproj/argo-helm/blob/main/charts/argo-rollouts/templates/dashboard/clusterrole.yaml and https://github.com/argoproj/argo-rollouts/blob/master/manifests/role/argo-rollouts-clusterrole.yaml
