### ISSUE TITLE
Re-apply old canary selector label to canary service is rollout is aborted 

### ISSUE THREAD

**Issue by meeech** [argoproj/argo-rollouts#2781]
~(Not sure if this is a bug or enhancement)~ is bug. 

# Summary

When AR manages a canary service, it manages the selectors to ensure the canary service points at the canary pods. 

Once a rollout is fully promoted, the service continues to point at the stable pods.  So if you have something pointing at the service, it continues to operate. 

If you abort a rollout, the canary service selector label is not rolled back as well, leading to a 'dead'; service. I would like to change this behaviour that when you rollback, the selector should be restored as well. 

# Use Cases

Whats interesting about how this works is that is allows you to rig up a fully canary path for your services assuming a certain naming convention.

eg: canary.ingress.example.com > canary-service.ns.svc.local > another-service.ns.svc.local 

You can then have a trigger that whenever a request comes in to host `canary.ingress.example.com` that you hit up all the `canary-*` service endpoints internally. If other services are running a canary at the moment, great! if not, also great, since everything will respond on that code path. 

Wanted to check if this is desired before doing the work. 
Let me know if this needs more details. 

[edit] Since this seems to be a bug (#2540) a few more details

* Reproduced using 1.4 and 1.5
* Abort was done via dashboard

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment]
Is this just a missing condition of this https://github.com/argoproj/argo-rollouts/pull/2540

**Comment by meeech** [comment]
@zachaller probably? This is a rollout not using any service mesh. Just number of pods to control %.

**Comment by meeech** [comment]
@zachaller I started looking into this, but it looks like the issue is higher up - it exits early if there is no TrafficRouting Reconcilers found. 

https://github.com/zachaller/argo-rollouts/blob/820f516bd1aa0b003e9ebc956528053d8f69e8a8/rollout/trafficrouting.go#L124

Wondering if the solution would be in modifying the reconcileStableAndCanaryService: https://github.com/zachaller/argo-rollouts/blob/820f516bd1aa0b003e9ebc956528053d8f69e8a8/rollout/service.go#L256
