### ISSUE TITLE
Update namespace of the ClusterRoleBinding assigning role to ServiceAccount

### ISSUE THREAD

**Issue by niels-s** [argoproj/argo-rollouts#281]
I've noticed a small issue with the getting started install.yml file. The `ClusterRoleBinding` needs to specify a namespace in which the ServiceAccount gets deployed, right now it's hardcoded to `argo-rollouts`, but the getting started advertises a deployment without namespace, so you need to manually update the https://github.com/argoproj/argo-rollouts/blob/f188cf4e8ab3d8138ac93c13e8be7cdac63efe2e/manifests/install.yaml#L10805 to make sure you configure the right namespace in which your Argo ServiceAccount is deployed.
If not you'll encounter permission issue for the service account like:

```
reflector.go:126] github.com/argoproj/argo-rollouts/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1alpha1.Rollout: rollouts.argoproj.io is forbidden: User "system:serviceaccount:kube-public:argo-rollouts" cannot list resource "rollouts" in API group "argoproj.io" at the cluster scope
reflector.go:126] github.com/argoproj/argo-rollouts/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1alpha1.Experiment: experiments.argoproj.io is forbidden: User "system:serviceaccount:kube-public:argo-rollouts" cannot list resource "experiments" in API group "argoproj.io" at the cluster scope
reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.ReplicaSet: replicasets.apps is forbidden: User "system:serviceaccount:kube-public:argo-rollouts" cannot list resource "replicasets" in API group "apps" at the cluster scope
```

It will probably make the quick install a little "harder", but at least it should be mentioned somewhere in the docs, I think.

**Comment by dthomson25** [comment]
@niels-s I added a note about `ClusterRoleBinding` to the getting started guide with this PR https://github.com/argoproj/argo-rollouts/pull/315.

**Comment by niels-s** [comment]
@dthomson25 thanks for updating the documentation 👍
