### ISSUE TITLE
Annotation: argo-rollouts.argoproj.io/managed-by-rollouts

### ISSUE THREAD

**Issue by deepanverma19** [argoproj/argo-rollouts#2827]
**Describe the bug**

I have 4-5 AWS eks clusters running with argo-rollouts `1.2.2` installed in them. I see the above annotation for all services running in only one of the cluster but the remaining 4 don't show the annotation for the same services.

Can someone please explain how is this annotation `argo-rollouts.argoproj.io/managed-by-rollouts` added automatically? And why would it be there for services running in one cluster and not others? 

**Version**
1.2.2

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by kostis-codefresh** [comment]
Regarding the "how it is added" you can look at the source code. I think the relevant point is here https://github.com/argoproj/argo-rollouts/blob/9bd26c6b78ddd3140155fc908b987703c9c3896f/service/service.go#L37

Why it does not exist in other clusters is hard to anwser. What is different for this clusters than the one that has the annotations? Do you have maybe other controllers that do stuff with annotations there?
