### ISSUE TITLE
Requesting new argoproj-labs plugin repo for Gloo Platform

### ISSUE THREAD

**Issue by bensolo-io** [argoproj/argo-rollouts#2876]
# Summary

I have a [Gloo Platform](https://docs.solo.io/) plugin implementation that I would like to maintain within argoproj-labs; creating this issue per the latest docs on contributing plugins.

The repo name should be `rollouts-plugin-trafficrouter-glooplatform`

The desired plugin name is `solo-io/glooplatform`

Please let me know if any other information is required!

# Use Cases

Using Argo Rollouts to automate Gloo Platform canary and blue/green deployments.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment]
Done: https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-glooplatform when you are ready feel free to also open a PR to add the plugin to the main argo-rollouts docs page etc.

**Comment by bensolo-io** [comment]
Thanks @zachaller - seems I do not have permissions for the https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-glooplatform repo
