### ISSUE TITLE
Add Rollout match selector label to AnalysisRuns

### ISSUE THREAD

**Issue by gnunn1** [argoproj/argo-rollouts#2888]
# Summary

Add the Rollout match selector to AnalysisRuns as labels

# Use Cases

At the moment there is no easy to select all of the AnalysisRuns that belong to a specific rollout so if you want to review the past history with kubectl it's painful to select them. While the AnalysisRun does have the ownerReference set to the Rollout this is not selectable with a field-selector or any other mechanism AFAIK, typically some scripting would be needed to do so.

The idea here is to basically do the same thing with AnalysisRuns that already happens with ReplicaSets and Pods.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment]
As a side note this is also possible: https://argo-rollouts.readthedocs.io/en/latest/features/analysis/#define-custom-labelsannotations-for-analysisrun
