### ISSUE TITLE
Requesting new argoproj-labs plugin repo for Gloo Edge

### ISSUE THREAD

**Issue by bdlilley** [argoproj/argo-rollouts#2891]
# Summary

Requesting a new repo  in argoproj-labs for [Gloo Edge](https://docs.solo.io/gloo-edge/latest/), repo name `rollouts-plugin-trafficrouter-glooedge `.  The plugin name will be `solo-io/glooedge`.

Note: I did recently have a Gloo Platform repo created (https://github.com/argoproj/argo-rollouts/issues/2876).  This is not in error; Gloo Edge is a different product with a different API, so I'd like to maintain them as separate plugins.

# Use Cases

Using Argo Rollouts to automate Gloo Edge canary and blue/green deployments

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment]
Created: https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-glooedge
