### ISSUE TITLE
Add header support for prometheus provider

### ISSUE THREAD

**Issue by dwalker-sabiogroup** [argoproj/argo-rollouts#2925]
# Summary

AnalysisTemplates and ClusterAnalysisTemplate do not support passing HTTP headers to prometheus provider.

# Use Cases

When using [Grafana Mimir](https://grafana.com/docs/mimir/latest/operators-guide/secure/authentication-and-authorization/) with multi-tenancy enabled the tenant is set by passing a `X-Scope-OrgID` header with the tenant name as the value

This is a common setup where Grafana Agent is used for metric collection but provides no ability to query metrics directly. 

The prometheus provider should be updated to support passing headers similar to the [web](https://argoproj.github.io/argo-rollouts/analysis/web/) provider.  

```yaml
headers:
  - name: X-Scope-Org-ID
    value: tenant_a
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by AhmedGrati** [comment]
Working on it! 👍
