### ISSUE TITLE
Don't promote canary via label changes

### ISSUE THREAD

**Issue by dodwmd** [argoproj/argo-rollouts#3048]
# Summary

What change needs making?

It would be good to allow promotion to occur via rolling out new pods rather than updating the existing pods labels. Pods in our canary needs to be self-aware that they are canary pods (pubsubs and connecting to fellow canary pods upstream). 

# Use Cases

When would you use this?

When promotion currently happens the pods labels are updated but the container isn't restarted, the container running the workload isn't aware that it's labels have been updated so continues to act as a canary pod even tho it's now getting stable workload.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment]
You can accomplish this via mounting labels to files within the pods, file update automatically that way.

**Comment by zachaller** [comment]
https://cloud-native.slack.com/archives/C01U781DW2E/p1686576619237719

**Comment by dodwmd** [comment]
We're using similar but use env variables and connect to the labels, the problem is the env values are populated on nodejs startup and not refreshed when the labels are updated. i'll look to make changes to use files for config instead of env variables. Thanks

**Comment by dodwmd** [comment]
closing
