### ISSUE TITLE
Argo Rollouts 1.6.0 UI Comments

### ISSUE THREAD

**Issue by DanTulovsky** [argoproj/argo-rollouts#3051]
# Summary

Hi. I wanted to give some feedback on the new Rollouts 1.6.0 UI.

Overall, thank you very much, it's much better.  I have two specific improvements that perhaps you would consider.

1. The landing page has a box for each Rollout on it.  I think it would be much easier to look at it if each Rollout was on its own line.  You should easily be able to fit the same information and it would allow things like sorting on status.

2. A very common use case for me is to look at the progress of multiple related Rollouts. For example:

![image](https://github.com/argoproj/argo-rollouts/assets/509887/4ef5cb49-fd73-494f-99ce-96032d0f2296)

It used to be the case that this view would show the progress as well (the green boxes). It no longer does this, which means I have to click into each one for status.

Thank you!

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by phclark** [comment]
We have a similar ask in our organization. We have several hundred Rollouts, and it's difficult for engineers to follow progress on coordinated deployments involving many rollouts. It would be great to have several different view options so that we could get a view of the global state at a glance.

**Comment by phclark** [comment]
If no one else is working on this, I'd love to take a pass at it.

**Comment by phclark** [comment]
I've got a few screenshots for comment, would love some feedback!

The major changes I'm planning are:
* Additional filters in the toolbar which allow the user to filter by status as well as a "meta" status "Needs Attention" which is defined as Rollouts with degraded status or paused where the pause message is not "CanaryPauseStep". 
* Ability to Favorite a Rollout, which will make the Rollout appear at the top of the screen. You can also filter to show only Favorites.
* Added Rollout Message to the bottom of the Rollout cards
* Improved name filtering to allow filtering of multiple rollouts ("frontend,backend" will return rollouts containing both terms in their name)
* Added display mode selection to toolbar
* Create new table display mode with sortable columns

New toolbar:
![image](https://github.com/argoproj/argo-rollouts/assets/35117115/7478bdc2-db65-45e5-82df-f87236251ecb)

Message shown on bottom of card for easy identification of important status conditions
![image](https://github.com/argoproj/argo-rollouts/assets/35117115/18b56183-e990-4ba3-8fad-3313b1140545)

New table view
![image](https://github.com/argoproj/argo-rollouts/assets/35117115/4ec8050c-0f28-42af-8c91-fcde14057553)

**Comment by zachaller** [comment]
@phclark looks good, are the screenshots mockups or do you have a working PR?

**Comment by phclark** [comment]
@zachaller I can throw up a working PR :)

**Comment by phclark** [comment]
This is still a WIP, and the code likely needs to be cleaned up a air amount, but it should give you an idea of the approach I'm taking.  Note that I'm more of an infra engineer than frontend dev, so if you see anything that needs improvement don't be shy :) 

https://github.com/argoproj/argo-rollouts/pull/3097

**Comment by martynd** [comment]
Noticed the latest changes when running a test build and was pleasantly surprised.
Definitely a worthwhile improvement

**Comment by zachaller** [comment]
Closed by: https://github.com/argoproj/argo-rollouts/pull/3118
