### ISSUE TITLE
Openshift Route Plugin Support

### ISSUE THREAD

**Issue by ishitasequeira** [argoproj/argo-rollouts#3092]
# Summary

There is an open PR https://github.com/argoproj/argo-rollouts/pull/1301 for adding openshift route support. 
Based on the comment [here](https://github.com/argoproj/argo-rollouts/pull/1301#issuecomment-1437626750), the feature needs to go as a plugin support. So, could I get a repository created under [argoproj-labs](https://github.com/argoproj-labs) organization?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment]
Repo has been created and you have been giving admin access feel free to add other maintainers to the repo

https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-openshift
