### ISSUE TITLE
Support for traefik.io api group version

### ISSUE THREAD

**Issue by tomsozolins** [argoproj/argo-rollouts#3119]
# Summary

What change needs making?

Add support for traefik.io crd API group version.

# Use Cases

When would you use this?

In Traefik v3 support for Kubernetes CRDs API Group traefik.containo.us has been removed - https://doc.traefik.io/traefik/master/migration/v2-to-v3/#kubernetes-crds-api-group-traefikcontainous

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment]
This probably is not to bad of an additiont to add we use an dynamic unstructured client so you just need to use change how that client gets created I think. Here is the start of that code https://github.com/argoproj/argo-rollouts/blob/master/utils/defaults/defaults.go#L63

**Comment by DrFaust92** [comment]
Ill take a look at this

**Comment by DrFaust92** [comment]
PR Ready
