### ISSUE TITLE
Add more diagrams to documentation

### ISSUE THREAD

**Issue by dthomson25** [argoproj/argo-rollouts#323]
In order to make our documentation more approachable, we should add more diagrams and graphics to help explain information.

**Comment by jessesuen** [comment]
![Argo Rollouts](https://user-images.githubusercontent.com/12677113/70842165-43259f00-1dd5-11ea-9229-2726aa7280bd.png)

**Comment by kostis-codefresh** [comment]
@jessesuen Is this issue blocked by something? Why not add this diagram to the docs?

If it it not up-to-date I would be happy to create another.
