### ISSUE TITLE
Reference an AnalysisTemplate in another AnalysisTemplate

### ISSUE THREAD

**Issue by OpenGuidou** [argoproj/argo-rollouts#3247]
# Summary

Hello,

I think it's a use case covered by Workflow/WorkflowTemplate in argo-workflow, but I couldn't find it for the Analysis.

I'd like to reference in my AnalysisTemplate another AnalysisTemplate, in order to group them together without redefining them.

# Use Cases

AnalysisTemplate 1: metric A
AnalysisTemplate 2: metric B
AnalysisTemplate 3: metric A + metric B

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment]
Would a ClusterAnalysisTemplate help you at all?

**Comment by OpenGuidou** [comment]
I would say it's the same issue with ClusterAnalysisTemplates.
We can't reference one inside the other. We can list several ones inside a Rollout analysis, but grouping them under an "umbrella" template would be more convenient for reusage.
