### ISSUE TITLE
Deprecate SMI support due to archiving by the CNCF

### ISSUE THREAD

**Issue by NissesSenap** [argoproj/argo-rollouts#3254]
# Summary

SMI has become [archived](https://www.cncf.io/blog/2023/10/03/cncf-archives-the-service-mesh-interface-smi-project/).
Thus, it makes sense to remove it from argo-rollouts.
How quickly that should happen is of course a question 

# Use Cases

Less code = good

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment]
I know quite a few people depend on it still, if you would be open to it I would love a start of updating docs with the mention of the depreciation.
