### ISSUE TITLE
the rollout will stuck in "progressing", if the new spec is applied with ("replicas" increasement, and pod spec is changed) when the rollout is in "paused".

### ISSUE THREAD

**Issue by andyliuliming** [argoproj/argo-rollouts#3256]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've included the version of argo rollouts.

**Describe the bug**

**To Reproduce**
1. deploy one "Rollout" with:
replicas: 3
  strategy:
    canary:
      dynamicStableScale: true
      minPodsPerReplicaSet: 1
      maxSurge: 1
      maxUnavailable: 1
      steps:
      - setCanaryScale: {weight: 60}
      - setWeight: 60
      - pause: {duration: 1000m}
 
 and then deploy change the replias of the Rollout.

then it will be stuck there. the promote also not work.

I think it's because the FindNewReplicaSet will return nil in this case.

**Expected behavior**

**Screenshots**

**Version**

latest in master branch.

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment]
Are you able to reproduce the 100% of the time, I am suspicious that something is going on but am unable to reproduce. If you can get this to trigger easily can you maybe explain a bit more your exact steps.

**Comment by zachaller** [comment]
I have been able to replicate something similar if I update both the replica count and the pod template at the same time, was this what you where doing?

**Comment by andyliuliming** [comment]
> I have been able to replicate something similar if I update both the replica count and the pod template at the same time, was this what you where doing?

yes, forgot to mention that the pod spec is changed together with the replias.

**Comment by andyliuliming** [comment]
I think this might help fix that:
https://github.com/argoproj/argo-rollouts/pull/3257
