### ISSUE TITLE
too big AnalysisRun status

### ISSUE THREAD

**Issue by erkanzileli** [argoproj/argo-rollouts#3259]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've included the version of argo rollouts.

**Describe the bug**

argo-rollouts duplicate analysis status and create too big YAML. My AnalysisRun object was 58225 line.

**To Reproduce**

- set an invalid Prometheus URL in AnalysisRun
- initialize a Rollout 
- set canary background analysis using that Prometheus AnalysisTemplate

**Expected behavior**

It should only store a couple of history or stop at somewhere

**Screenshots**

![image](https://github.com/argoproj/argo-rollouts/assets/26749979/7eb5ba13-9064-483a-a9c1-7e6a02782808)

**Version**

v1.4.0

**Logs**

```
# first logs
Failed to garbage collect measurements: prometheus address is not is url format

# latest logs
analysisrun syncHandler error: etcdserver: request is too large
Error updating analysisRun: etcdserver: request is too large
```

**Message from the maintainers**:
Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment]
This should be fixed in newer versions.

**Comment by zachaller** [comment]
Please re-open if you still see issues on newer versions.
