### ISSUE TITLE
UI 1.6.4 no longer highlights AnalysisRun Status

### ISSUE THREAD

**Issue by gnunn1** [argoproj/argo-rollouts#3295]
Checklist:

* [X] I've included steps to reproduce the bug.
* [X] I've included the version of argo rollouts.

**Describe the bug**

Using Argo Rollouts 1.6.0 with the 1.6.4 dashboard the AnalysisRun button no longer highlights the status using a color (i.e. green for success, red for failure, etc). Instead the button is always white with grey text. Here is a screenshot of a successful run, note the white button with grey text:

![Successful](https://github.com/argoproj/argo-rollouts/assets/9358238/4db79efc-b536-4f87-9983-81ada32bedf8)

Looking at the generated HTML and CSS I can see an `analysis--success` class is added to the surrounding div but not to the button itself.

```
<div class="analysis">
  <div class="analysis-header">Analysis Runs</div>
  <div class="analysis__runs">
    <div class="analysis__runs-action analysis--success">
      <button type="button" class="ant-btn css-1kn1vta ant-btn-default">
        <span>Analysis 2-pre</span>
      </button>
    </div>
  </div>
</div>
```
The `analysis--success` CSS class is trying to set the color to green however I think it's getting overriden by the `ant-btn CSS class which is set in the button itself:

```
:where(.css-1kn1vta).ant-btn {
    outline: none;
    position: relative;
    display: inline-block;
    font-weight: 400;
    white-space: nowrap;
    text-align: center;
    background-image: none;
    background-color: transparent;
    border: 1px solid transparent;
    cursor: pointer;
    transition: all 0.2s cubic-bezier(0.645, 0.045, 0.355, 1);
    user-select: none;
    touch-action: manipulation;
    line-height: 1.5714285714285714;
    color: rgba(0, 0, 0, 0.88);
}
```

Commenting out the color from the `.ant-btn` gets the expected green text to display correctly but also adding the `success-analysis` class to the button element does as well. I suspect the correct solution is removing the color from the `.ant-btn` class but not 100% given you probably want to avoid two classes trying to set the color on the same element but I don't know if there are other places `.ant-btn` gets used where removing the color will cause issues.

**To Reproduce**

* Create a rollout with Argo Rollouts with an analysistemplate
* Deploy a new image to start a promotion and kick off an AnalysisRun
* Note the AnalysisRun button never changes color.

**Expected behavior**

Button changes color to indicate current status of the AnalysisRun

**Screenshots**

**Version**

Argo Rollouts 1.6.0
Argo Rollouts kube ctl plugin for dashboard 1.6.4

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by gnunn1** [comment]
I tested quickly with the 1.6.0 version of the UI as well and the behavior is identical.

**Comment by zachaller** [comment]
This whole interface has been redesigned in 1.7 (currently on master) not sure it's worth going back and fixing it or not on 1.6.x, if you want to open a PR I would review it for a cherry pick on 1.6.

**Comment by gnunn1** [comment]
Thanks, I just tested `master` locally and I can see it's working fine with a nice green circle being shown, I was raising this issue for a Rollouts workshop I'm maintaining at Red Hat. I think since the UI is going to change again I'll revert the dashboard to v1.5 in the workshop and then upgrade it to v1.7 when released to save myself the effort of recreating the screenshots of the dashboard multiple times.

Appreciate the insight on the upcoming changes.
