### ISSUE TITLE
Hope to support Alibaba Cloud Alb Ingress Controller

### ISSUE THREAD

**Issue by callmefool** [argoproj/argo-rollouts#3301]
# Summary

What change needs making?

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment]
This can now be done as a plugin https://argo-rollouts.readthedocs.io/en/stable/plugins/

**Comment by callmefool** [comment]
thank you.
