### ISSUE TITLE
how to increase rollout replicas when rollout reach stable(only one rs)

### ISSUE THREAD

**Issue by tandd1123** [argoproj/argo-rollouts#332]
sometime, we want to manual increase rollout replicas number. i try patch rollout spec.replicas  field , but it not work. rollout relicas no change. 
if there is way  through modify rollout yaml some fields  to  get it. we use canary rollout
thanks

**Comment by danielzheng** [comment]
I got the same problem, the canary only increase partial replicas number.

**Comment by dthomson25** [comment]
Hi @tandd1123 and @danielzheng, I was able to reproduce the issue and filed a fix here: https://github.com/argoproj/argo-rollouts/pull/343

**Comment by dthomson25** [comment]
Closed with https://github.com/argoproj/argo-rollouts/pull/343
