### ISSUE TITLE
Honeycomb metric provider

### ISSUE THREAD

**Issue by cbertinato** [argoproj/argo-rollouts#3320]
# Summary

I'd like to suggest adding a Honeycomb metric provider for `AnalyisTemplate`s.

# Use Cases

Honeycomb is widely used as a distributed tracing backend. The use case is fairly clear, I think. :) 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by cbertinato** [comment]
I have done a good bit of the work here, so would be happy to submit a PR for this issue.

**Comment by zachaller** [comment]
This can now be created as a plugin: https://argo-rollouts.readthedocs.io/en/stable/plugins/

**Comment by zachaller** [comment]
If you would like to open source it as well we can put it under argoproj-labs

**Comment by cbertinato** [comment]
Oh, right! Good call. I'll pivot to that method.

**Comment by cbertinato** [comment]
@zachaller along those lines, may I have a repo created under argoproj-labs for such a plugin?

**Comment by zachaller** [comment]
repo created, sorry for the delay going to close this feel free to reach out here or in cncf slack if you need any help or anything else.

https://github.com/argoproj-labs/rollouts-plugin-metric-honeycomb

**Comment by zachaller** [comment]
Also when your ready, feel free to open a PR to the main repo's docs adding the plugin
