### ISSUE TITLE
Option to specify a different KUBECONFIG where Analysis vs. Jobs would run

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#3337]
# Summary

Currently, when using the Job metric, the Job object will be created in the same cluster where the AnalysisRun resides. This proposal is to introduce a configuration option (environment variable) where a JOB_KUBECONFIG could be pointed to a **_different_** cluster where Jobs would be created (different from the AnalysisRuns).

# Use Cases

Having this option would enable some multi-cluster use cases, namely the ability for AnalysisTemplates, AnalysisRuns to be defined at a central location, without having to deploy/distribute the CRDs or AnalysisTemplates/Runs to workload clusters.

This should of course be an optional setting -- if the option is unspecified, the controller would maintain the current behavior. 

## Other notes

In addition to having a remote setting, the jobs should also have the option to be created using in-cluster credentials (instead of static credentials).

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment]
Would this JOB_KUBECONFIG be set at the controller level, I am wondering if say a multi cluster job plugin would make sense?

**Comment by jessesuen** [comment]
Yes, this would be a controller-level setting, and when set, it would simply change the kube client that would be used for the Job client/informer.

Unfortunately, using plugin isn't desirable, since the entire job/pod spec would have to be duplicated into a plugin stanza, creating unnecessary nesting, and not to mention the overhead of the plugin development itself. Since, Jobs are already a native type we already support, this request is just allowing an operator an added control on where the workload gets created.

Another use case is not necessarily multi-cluster. Another one that came up is that can be desired to create Jobs under a different namespace from the AnalysisRun (e.g. if that namespace has additional node/affinity/networking controls).

**Comment by zachaller** [comment]
Yea that's fair about plugin embedding whole pod spec is a little "not fun" mainly due to the lose of typing, that said with this as an ENV is it true that a controller could only ever connect to one different cluster or namespace for all jobs?
