### ISSUE TITLE
Supported kuberenetes versions

### ISSUE THREAD

**Issue by smyja** [argoproj/argo-rollouts#3358]
# Summary

What change needs making?
Add all versions of argo-rollouts and their supported kuberenetes version. For argo rollouts less than 1.20 there's no testing file for me to find the kubernetes version. It would be nice to just have everything on a page like other cncf plugins. 

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by kostis-codefresh** [comment]
Does this answer your question? https://argo-rollouts.readthedocs.io/en/latest/installation/#supported-versions

**Comment by smyja** [comment]
yes

> Does this answer your question? https://argo-rollouts.readthedocs.io/en/latest/installation/#supported-versions
