### ISSUE TITLE
Search Bar in Namespace Selector on Argo Rollouts UI lacks matching filter

### ISSUE THREAD

**Issue by DimKanoute** [argoproj/argo-rollouts#3408]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've included the version of argo rollouts.

**Describe the bug**

When using the search bar in the namespace selector, there is no filter applied to display only the matching namespaces as I type. This makes it difficult to efficiently locate and select the desired namespace, especially in environments with a large number of namespaces.

**To Reproduce**

1. Navigate to the namespace selector in the UI.
2. Click on the search bar to input text.
3. Start typing a namespace name.
4. Notice that there is no live filter applied to display only the matching namespaces.
5. Experience difficulty in identifying and selecting the desired namespace, particularly in environments with a large number of namespaces.

**Expected behavior**

When using the search bar in the namespace selector, I expect a live filter to be applied, displaying only the namespaces that match the typed input. This would make it easier to identify and select the desired namespace, improving the user experience in environments with numerous namespaces.

**Contribution Offer**

We have successfully resolved this issue locally and we are willing to contribute the solution. Let us know if interested in incorporating this fix into the project?

**Version**
`v1.2.0`

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by CarlosLanderas** [comment]
Any update on this issue? We have a very large list of namespaces and the autocomplete filtering not working makes it hard to use.

Thanks

**Comment by DimKanoute** [comment]
For anyone that might be interested you can enable the filter by adding `filterOption={true}` in the `<Autocomplete />` module [here](https://github.com/argoproj/argo-rollouts/blob/master/ui/src/app/components/header/header.tsx#L83)
