### ISSUE TITLE
Add RolloutAnalysis check on presence of metrics before trying to create AnalysisRuns

### ISSUE THREAD

**Issue by kevinqian-db** [argoproj/argo-rollouts#3441]
# Summary

Today we have the following when reconciling AnalysisRuns (ARs)

https://github.com/argoproj/argo-rollouts/blob/46f14278eef6735498c33835e795b0315f33f948/rollout/analysis.go#L314-L319

However, this check will not catch the case if the analysis field is an empty object vs a nil. If an empty object is placed here, the subsequent AR creation code will run, and eventually result in the failure `spec.metrics is empty` and errors out. Argo today will keep retry this failure and it will never realize that it can never create this AR.

Right now we did encounter that some entity (we are not sure which one, might even been Argo itself) setting it to empty when trying to skip health checks during an emergency fix. Nevertheless, we believe having an extra check that the configuration here actually yields any metrics should still be beneficial to avoid unintended infinite retry.

# Use Cases

When user passed an empty object instead of nil.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment]
Yea, we actually get hit by by this as well.

**Comment by zachaller** [comment]
Having a rollout object with args but no templates I think also recreates this?

```
analysis:
        args:
          - name: stable-hash
            valueFrom:
              podTemplateHashValue: Stable
        startingStep: 1
```

**Comment by kevinqian-db** [comment]
> Having a rollout object with args but no templates I think also recreates this?

Yeah. My idea is to probably check that if the manifest does not provide any templates

**Comment by kevinqian-db** [comment]
Create PR https://github.com/argoproj/argo-rollouts/pull/3446, PTAL
