### ISSUE TITLE
Update kubernetes dependencies to 1.27

### ISSUE THREAD

**Issue by blkperl** [argoproj/argo-rollouts#3487]
# Summary

Kubernetes dependencies need to be updated to a minimum of 1.27 to receive security updates as 1.26 went EOL in February. 

This function will need to be changed as it panics on 1.27

- https://github.com/argoproj/argo-rollouts/blob/master/hack/gen-crd-spec/main.go#L51

```
go run ./hack/gen-docs/main.go
panic: feature gate "OpenAPIV3" with different spec already exists: {true true }
```

We can also address these comments as we no longer will support Kubernetes 1.16

- https://github.com/argoproj/argo-rollouts/blob/master/hack/gen-crd-spec/main.go#L233-L234
- https://github.com/argoproj/argo-rollouts/blob/master/hack/gen-crd-spec/main.go#L243-L244
- https://github.com/argoproj/argo-rollouts/blob/master/hack/gen-crd-spec/main.go#L253-L254

# Use Cases

* Security and compliance 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment]
closed by https://github.com/argoproj/argo-rollouts/pull/3494
