### ISSUE TITLE
Docs: Current Rollout specification uses `spec.workloadRef.scaleDown`, which does not exist in latest v1.6.6

### ISSUE THREAD

**Issue by mildmojo** [argoproj/argo-rollouts#3505]
**Describe the bug**

👋 

The latest [Rollout resource manifest specification](https://argoproj.github.io/argo-rollouts/features/specification/) references the `spec.workloadRef.scaleDown` field, which does not exist in the [latest (v1.6.6) Rollout CRD](https://github.com/argoproj/argo-rollouts/blob/v1.6.6/manifests/crds/rollout-crd.yaml#L3325).

This field was proposed in #2748 and added in PR #3111 five months back on December 5th, 2023, slated for release in v1.7, but has not been released yet. Using the spec in the documentation produces a manifest that can't be deployed.

I checked to see if the docs were versioned, but the navbar "latest" is the only version available, shown next to the latest release tag in the repo, v1.6.6:

![image](https://github.com/argoproj/argo-rollouts/assets/103495/fb111375-143f-42fe-8f38-e986e924eaf1)

I'd suggest removing the field from the docs, or versioning the docs to make it clear the field only exists in 1.7rc1+. If the 1.7 release is imminent, I understand, and we can close this issue. It may be useful to someone like me who went searching the issues for deployment problems with `workloadRef` as specified in the docs under Rollouts v1.6.6.

Thanks!

**To Reproduce**

Try deploying a manifest for a Rollout with `spec.workloadRef.scaleDown` present.

Example error from a helm release:

```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Rollout.spec.workloadRef): unknown field "scaleDown" in io.argoproj.v1alpha1.Rollout.spec.workloadRef
```

**Expected behavior**

Based on the docs, I expected it to work.

**Version**

v1.6.6

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment]
Yes 1.7 is very soon was hoping today but got caught up with internal work. Should be tommorow or early next week.

**Comment by MohammedShetaya** [comment]
@zachaller Thanks for the heads up. Any update on this?

**Comment by MohammedShetaya** [comment]
@zachaller 
Thanks, Is there a way to version the docs or fix the navbar :) I kept testing this for a whole day thinking it is in 1.6.x
