### ISSUE TITLE
Documentation formatting issue on page "Analysis & Progressive Delivery"

### ISSUE THREAD

**Issue by bmuschko** [argoproj/argo-rollouts#3509]
**Describe the bug**

The documentation page "Analysis & Progressive Delivery" has a formatting issue. The provided Markdown code isn't rendered properly and show the markup code instead.

**To Reproduce**

Navigate to the documentation page [Analysis > Overview](https://argoproj.github.io/argo-rollouts/features/analysis/). The section underneath "The result in the AnalysisRun will have the aggregation of metrics of each template:" doesn't properly format the header of a code snippet and the code snippet itself.

**Expected behavior**

The header the code snippet are formatted correctly using Markdown.

**Screenshots**

<img width="1443" alt="image" src="https://github.com/argoproj/argo-rollouts/assets/440872/3a18d208-cac1-46c7-bf54-d2cf8d896f53">

**Version**

v1.6.6

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by blkperl** [comment]
Hey @bmuschko, thanks for reporting this issue. Would you be interested in opening a PR to fix it?

**Comment by bmuschko** [comment]
Yes, absolutely. I am going to work on a PR sometime next week.

**Comment by bmuschko** [comment]
@blkperl You can find the PR here: https://github.com/argoproj/argo-rollouts/pull/3511
