### ISSUE TITLE
How to configure Argo Rollout UI Dashboard in Existing Argocd UI

### ISSUE THREAD

**Issue by tppalani** [argoproj/argo-rollouts#3542]
Checklist:

* [ ] I've included steps to reproduce the bug.
* [ ] I've included the version of argo rollouts.

**Describe the bug**
"This is not a bug; I’m just seeking documentation on how to install the Argo CD Rollout dashboard in a Multi-Tenant EKS cluster. I have already installed Argo CD, and it’s up and running in the EKS cluster.

I’m not able to find the right document to install the Argo Rollout dashboard UI in our existing Argo CD. Is there any extension to integrate the rollout dashboard into the existing Argo CD main UI homepage? If yes, please share the document." 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

{
    "Version": "v2.6.2+6e02f8b",
    "BuildDate": "2023-02-16T15:05:14Z",
    "GitCommit": "6e02f8b23201b0620a4ff1bce5d38229ba1eb02e",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.5.7 2022-08-02T16:35:54Z",
    "HelmVersion": "v3.10.3+g835b733",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}

**Logs**

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by wanghong230** [comment]
https://github.com/argoproj-labs/rollout-extension
