### ISSUE TITLE
Argo Rollouts needs a custom annotation option for canary ingresses

### ISSUE THREAD

**Issue by kutysam** [argoproj/argo-rollouts#3574]
# Summary

Argo Rollouts Ingress needs to have a setting for canary ingress annotations itself.
Currently, it has one but its appended by a fixed prefix.
https://github.com/argoproj/argo-rollouts/blob/master/rollout/trafficrouting/nginx/nginx.go#L126

# Use Cases

I have external DNS on all my ingresses.
They have a specific ip address tied to them through ingress.
`external-dns.alpha.kubernetes.io/target: XX.XX.XX.XX`
When a canary gets created, I would like them to have an ingress annotation.
`      external-dns.alpha.kubernetes.io/exclude: "true"`

I can use the fixed prefix to be external-dns.alpha.kubernetes.io but it is not right as its fixed and I cannot have any other various types of annotations.

Thus, it will be best if a customAnnotation yaml key can be created on Rollouts.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment]
Releated: https://github.com/argoproj/argo-rollouts/issues/2225

**Comment by cyrilico** [comment]
Proposed a change at https://github.com/argoproj/argo-rollouts/pull/3671
