### ISSUE TITLE
Argo Rollouts Dashboard Stuck in Loading 

### ISSUE THREAD

**Issue by sdoncila** [argoproj/argo-rollouts#3618]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've included the version of argo rollouts.

**Describe the bug**

<!-- After installing Argo-Rollouts Helm Chart, the screen is stuck in loading.

It happens in both of these scenarios:

1. when I do port-forwarding of the dashboard pod or service
2. when I enable ingress for dashboard and create a AWS application load balancer.

**To Reproduce**

1. Install the helm chart for Argo-Rollouts and enable the dashboard
2. Port-forward the dashboard pod and dashboard will be stuck in loading mode

Chart.yaml:

apiVersion: v2
name: argocd-rollouts
version: 1.0.0
appVersion: v1.6.6
description: A Helm chart for Argo Rollouts
dependencies:
  name: argo-rollouts
  version: "2.35.3"
  repository: https://argoproj.github.io/argo-helm
  type: application

values.yaml:

argo-rollouts:
  serviceAccount:
  create: true
  controller:
    replicas: 2
  dashboard:
    enabled: true

**Expected behavior**

I want to be able to see and use the dashboard

**Screenshots**

<img width="1710" alt="Screenshot 2024-06-06 at 12 44 47" src="https://github.com/argoproj/argo-rollouts/assets/139113647/bd4f2f5f-ab36-4832-91c4-00bbe5bc2bdc">
<img width="1302" alt="Screenshot 2024-06-06 at 12 55 10" src="https://github.com/argoproj/argo-rollouts/assets/139113647/8e8edbdc-beb8-47a8-a8d3-8cab2c37c206">
<img width="1701" alt="Screenshot 2024-06-07 at 09 03 58" src="https://github.com/argoproj/argo-rollouts/assets/139113647/80ea5fde-7de1-4f38-9758-3d7302723809">

**Version**

1.66

**Logs**

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

```
time="2024-06-06T08:53:15Z" level=info msg="Argo Rollouts starting" version=v1.6.6+737ca89
time="2024-06-06T08:53:15Z" level=info msg="Creating event broadcaster"
time="2024-06-06T08:53:15Z" level=info msg="Setting up event handlers"
time="2024-06-06T08:53:15Z" level=info msg="Setting up experiments event handlers"
time="2024-06-06T08:53:15Z" level=info msg="Setting up analysis event handlers"
time="2024-06-06T08:53:15Z" level=info msg="Leaderelection get id argocd-rollouts-argo-rollouts-8477d4b6f9-4twdj_a5f1908f-5e0b-4c1c-b0b6-90737114d99a"
time="2024-06-06T08:53:15Z" level=info msg="Starting Metric Server at 0.0.0.0:8090"
time="2024-06-06T08:53:15Z" level=info msg="Starting Healthz Server at 0.0.0.0:8080"
time="2024-06-06T08:53:15Z" level=info msg="attempting to acquire leader lease argo-rollouts/argo-rollouts-controller-lock...\n"
time="2024-06-06T08:53:16Z" level=info msg="New leader elected: argocd-rollouts-argo-rollouts-868546b4bc-8dccz_835bab9e-d1eb-4b47-828e-5c2d8070d3f7"
time="2024-06-06T08:53:32Z" level=info msg="successfully acquired lease argo-rollouts/argo-rollouts-controller-lock\n"
time="2024-06-06T08:53:32Z" level=info msg="New leader elected: argocd-rollouts-argo-rollouts-8477d4b6f9-4twdj_a5f1908f-5e0b-4c1c-b0b6-90737114d99a"
time="2024-06-06T08:53:32Z" level=info msg="I am the new leader: argocd-rollouts-argo-rollouts-8477d4b6f9-4twdj_a5f1908f-5e0b-4c1c-b0b6-90737114d99a"
time="2024-06-06T08:53:32Z" level=info msg="Starting Controllers"
time="2024-06-06T08:53:32Z" level=info msg="invalidated cache for resource in namespace: argo-rollouts with the name: argo-rollouts-notification-configmap"
time="2024-06-06T08:53:32Z" level=info msg="Waiting for controller's informer caches to sync"
time="2024-06-06T08:53:32Z" level=info msg="Started controller"
time="2024-06-06T08:53:32Z" level=info msg="Starting Service workers"
time="2024-06-06T08:53:32Z" level=info msg="Starting Ingress workers"
time="2024-06-06T08:53:32Z" level=info msg="Started Service workers"
time="2024-06-06T08:53:32Z" level=info msg="Started Ingress workers"
time="2024-06-06T08:53:32Z" level=info msg="Starting analysis workers"
time="2024-06-06T08:53:32Z" level=warning msg="Controller is running."
time="2024-06-06T08:53:32Z" level=info msg="Starting Rollout workers"
time="2024-06-06T08:53:32Z" level=info msg="Started rollout workers"
time="2024-06-06T08:53:32Z" level=info msg="Started 30 analysis workers"
time="2024-06-06T08:53:32Z" level=info msg="Starting Experiment workers"
time="2024-06-06T08:53:32Z" level=info msg="Started Experiment workers"
time="2024-06-06T09:08:32Z" level=info msg="invalidated cache for resource in namespace: argo-rollouts with the name: argo-rollouts-notification-configmap"
time="2024-06-06T09:23:32Z" level=info msg="invalidated cache for resource in namespace: argo-rollouts with the name: argo-rollouts-notification-configmap"
time="2024-06-06T09:38:32Z" level=info msg="invalidated cache for resource in namespace: argo-rollouts with the name: argo-rollouts-notification-configmap"
```

Logs from Dashboard:

`time="2024-06-07T07:57:20Z" level=info msg="Argo Rollouts Dashboard is now available at http://localhost:3100/rollouts"`


---
<!-- Issue Author: Don't delete this message to encourage other users to support your issue! -->
**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by nikoshet** [comment]
@sdoncila hello, how did you manage to solve this?

**Comment by shahGnp** [comment]
Hello, any solution for this?
