### ISSUE TITLE
Ability to add env variable to canary pod

### ISSUE THREAD

**Issue by ayanhamza** [argoproj/argo-rollouts#3622]
It will good if we can ability to add ephemeral env variable to canary pod. 
It will be useful when 

- service should connect to another DB and for testing in canary with new variables
- run service with new variables in canary to change credentials or endpoint to another service

**Comment by zachaller** [comment]
This can be accomplished using rollouts ephemeralMetadata configuration and k8s downward api

**Comment by eddiewebb** [comment]
The env variables would stay fixed as they were pulled at start though wouldn't they? (ie. always show canary value)
