### ISSUE TITLE
Analysis Template Success condition is not working

### ISSUE THREAD

**Issue by amitbitcse** [argoproj/argo-rollouts#363]
Hi,

In the AnalysisTemplate, the successCondition field is not working as expected.

```
successCondition: result >= 0
```

The Analysis Run is successfully running the query on Prometheus. Below is the AnalysisRun status

```
Status:
  Metric Results:
    Consecutive Error:  1
    Error:              1
    Measurements:
      Finished At:  2020-01-16T14:55:35Z
      Phase:        Error
      Started At:   2020-01-16T14:55:35Z
      Value:        [2]
    Name:           success-rate
    Phase:          Running
  Phase:            Running
  Started At:       2020-01-16T14:55:35Z
```

The value from prometheus query is 2 which is evaluated correctly by AnalysisRun as mentioned against Value field in Status. However the Phase is resulting into Error instead of Successful.

When I hard-coded successCondition to be true, I got Phase as Successful in the AnalysisRun

```
successCondition: "true"
```
Argo Rollout Version: 0.6.2

**Comment by dthomson25** [comment]
Hey @amitbitcse, I noticed that your result is an array instead of a single value. Could you try `all(result, {# > 0})` as your success conditions? This is checking that each element of the array is greater than 0. If this works, then I think this would be a bug in the Prometheus code since it is supposed to convert single element arrays into just the value.

Also, can you send the logs with the error reported with the original output?

**Comment by amitbitcse** [comment]
Thanks @dthomson25.
The solution worked for me. I tried upgrading Prometheus to the latest version, but still getting array.

> Also, can you send the logs with the error reported with the original output?

The only error message I can see is the "Error" value against Phase in the AnalysisRun measurement. Although it didn't occur to me earlier, but when I checked the logs from argo-rollout pod, I can see below message.

```
time="2020-01-17T06:12:41Z" level=warning msg="invalid operation: > (mismatched types []float64 and int) (1:8)\n | result > 0\n | .......^" analysisrun=nginx-rollout-f65ff45b8-2-success-rate metric=success-rate namespace=temp
time="2020-01-17T06:12:41Z" level=info msg="measurement completed Error" analysisrun=nginx-rollout-f65ff45b8-2-success-rate metric=success-rate namespace=temp
time="2020-01-17T06:12:41Z" level=warning msg="measurement had error: " analysisrun=nginx-rollout-f65ff45b8-2-success-rate metric=success-rate namespace=temp
```

I will explore more later to find out whether Prometheus is returning array or Argo is encapsulating it in array.

**Comment by jessesuen** [comment]
I think our Prometheus docs need to be updated to be ‘result[0]’.

**Comment by thiagonache** [comment]
> I think our Prometheus docs need to be updated to be ‘result[0]’.

yep. I spent several hours before I saw this issue. Just adding result[0] fixes the issue for me and it does make sense because it's going to return just one item but using array as variable type.
