### ISSUE TITLE
Add webhooks for rollout failure/success

### ISSUE THREAD

**Issue by sarialem** [argoproj/argo-rollouts#369]
Would be great if argorollouts can call a webhook on success/failure of promoting a rollout, for example sending a slack message.

**Comment by leoluz** [comment]
Hi Argo Team! 

I'm currently working on a project where this functionality would be really interesting to have. I see that it was removed from the planned milestones. I wanted to confirm that there is no planned work related to this? If this is confirmed I might have the bandwidth to implement it.

Please let me know.

Thank you!

**Comment by ryota-sakamoto** [comment]
Hi @leoluz 
Sorry for being late.
I'm maintainer of argocd-notifications, then I'm considering to implement it using https://github.com/argoproj/notifications-engine if you have been not already implementing it.
