### ISSUE TITLE
feat: enable Profiling support to detect cpu/mem bottlenecks

### ISSUE THREAD

**Issue by kostis-codefresh** [argoproj/argo-rollouts#3757]
# Summary

Idea came from this discussion. https://github.com/argoproj/argo-rollouts/discussions/3752

We need a way to allow people to get profiling data from Argo Rollouts (ideally in a production env) so that we can detect and fix bottlenecks.

# Use Cases

Large installations of Argo Rollouts with many resources on a single cluster would benefit from this
It will also allow us to analyze the performance of new/suggested features in advance.

Ideally this should be a command line argument/flag which is off by default and enabled on demand (to avoid any performance hit when profiling is not used).

Argo Workflows already has this https://argo-workflows.readthedocs.io/en/latest/running-locally/#troubleshooting

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by johnmwood** [comment]
The profiling PR has been merged so this issue can be closed.
