### ISSUE TITLE
Canary support with argo rolllouts with kong traffic provider does not work seamlessly

### ISSUE THREAD

**Issue by som-kanade-zepto** [argoproj/argo-rollouts#3763]
Checklist:

Argo roll out image version : v1.7.0
Kong Version: 3.5
Argo roll out app version: 2.37.2

Describe the bug

<Tried Canary support with argo roll outs with kong traffic provider everything works and rollout happens BUT after some time (not fixed). other APIs which are routed via same gateway start failing where as there are no changes made to those http routes>

To Reproduce

Install argo roll out
Install kong ingress controller
Followed this doc (https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/tree/main/examples/kong)
Everything works as expected
Existing API which shares same gateway start giving 5xx error where as no changes made to that object starts failing
Deleting http object of sample app created using above documentation will fix the issue
Expected behavior

All routes should without any issues

Screenshots

We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.

Version

Argo roll out image version : v1.7.0
Argo roll out app version: 2.37.2

Logs

No specific errors in roll out controller when this issue happend

Message from the maintainers:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment]
This issue should move to the plugin repo.
