### ISSUE TITLE
AbortScaleDownDelaySeconds (scale-down-deadline) not working in case of retry

### ISSUE THREAD

**Issue by matbhe** [argoproj/argo-rollouts#3774]
**Describe the bug**
Argo rollouts does not await the AbortScaleDownDelaySeconds timeout in case of a retried rollout (already once aborted). It immediately terminates the pods (can cause downtimes when using ALB traffic routing).

_It seems that the 2nd retry sets the scale-down-deadline - annotation to empty (because of conflict when updating replicaset xy, falling back to patch error) and this then later causes problems when aborting the rollout (Unable to read scaleDownAt)._ 

**To Reproduce**
* Create a rollout with yellow version
* Rollout to green version
* Abort the running rollout (AbortScaleDownDelaySeconds is working)
* Retry the rollout
* Abort the running rollout again (AbortScaleDownDelaySeconds is not working)

**Expected behavior**
Argo rollouts should await the AbortScaleDownDelaySeconds timeout in every case.

**Version**
Tested with version 1.7.1 (release-1.7 branch)

**Logs**
Controller
[rollouts-controller.log](https://github.com/user-attachments/files/16519857/rollouts-controller.log)

Replicaset - Watch
[replica-watch.log](https://github.com/user-attachments/files/16519861/replica-watch.log)

**Comment by zachaller** [comment]
Closing in favor of other ticket
