### ISSUE TITLE
1.7.2 bug fix release

### ISSUE THREAD

**Issue by kevinji** [argoproj/argo-rollouts#3785]
# Summary

Can we get a 1.7.2 bug fix release? There's a few changes in master that would be great to have out.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment]
I am planning on this soon, anything in master that is not on this list https://github.com/argoproj/argo-rollouts/pulls?q=is%3Apr+is%3Aclosed+label%3Acherry-pick%2Frelease-1.7++-label%3Acherry-pick-completed

**Comment by kevinji** [comment]
Nope, I think those changes look good to me.
