### ISSUE TITLE
Rollout Controller deployment should use the recreate strategy

### ISSUE THREAD

**Issue by dthomson25** [argoproj/argo-rollouts#38]
Since we need to have the Argo Rollout Controller to deploy rollouts, we have a chicken and egg problem for deploying the controller. As a result, the rollout controller is deployed with a deployment.  Currently, it is deployed using the rolling update strategy.  Instead, the controller should use the recreate strategy because controllers operate under the assumption that they are the only one modifying a resource.

**Comment by nedal87** [comment]
Hi @dthomson25 I've got a [PR](https://github.com/argoproj/argo-helm/pull/2412) open for the Argo Helm chart to add a configurable deployment strategy for the Argo Rollouts controller.

Referencing the issue #38 about using "Recreate" strategy. I'm reaching out to get some more insights. Do you see any issues with having it configurable?

I've tested it locally, and all seems good, but I wanted to make sure I'm not missing anything crucial. Your thoughts would be super helpful! Thanks!
