### ISSUE TITLE
Reference multiple analysis templates in a rollout's analysis

### ISSUE THREAD

**Issue by dthomson25** [argoproj/argo-rollouts#384]
Currently, Rollouts can only reference one analysis template for an analysis step or a background analysis. Instead, the rollout should be able to specify multiple analysis templates and then create analysis runs from these templates. This makes it easier to have separate modular analysis runs instead of users creating a single analysis template.

Questions for the implementations:
1. Should the controller combine all the analysis templates into one analysis run or create multiple analysis templates?

**Comment by jessesuen** [comment]
> Should the controller combine all the analysis templates into one analysis run or create multiple analysis templates?
 
When multiple AnalysisTemplates are referenced, we should compose them into a single AnalysisRun for simplicity.

**Comment by dthomson25** [comment]
Note: https://github.com/argoproj/argo-rollouts/issues/348 is dependent on this ticket since it will introduce Analysis to BG.
