### ISSUE TITLE
certificate verification issue when using wavefront as metric provider

### ISSUE THREAD

**Issue by akshaychitneni** [argoproj/argo-rollouts#391]
During analysis run with wavefront, I see certificate verification issue when accessing https endpoint. Should the docker image be updated with ca-certificates?

Following is the log during analysis run,

`time="2020-02-04T01:13:42Z" level=warning msg="measurement had error: Get https://xxx.wavefront.com/api/v2/chart/api?autoEvents=%3Cbool+Value%3E&g=s&i=%3Cbool+Value%3E&includeObsoleteMetrics=%3Cbool+Value%3E&listmode=%3Cbool+Value%3E&p=1&q=sum%28rate%28%0A++5m%2C+ts%28%22nginx.ingress.controller.requests.counter%22%2C+ingress%3D%22canary-demo%22+and+status%3D%22200%22%0A%29%29%29+%2F%0Asum%28rate%28%0A++5m%2C+ts%28%22nginx.ingress.controller.requests.counter%22%2C+ingress%3D%22canary-demo%22%0A%29%29%29%0A&s=1580778822000&strict=%3Cbool+Value%3E: x509: certificate signed by unknown authority" analysisrun=canary-demo-6758949f55-4-success-rate-wavefront metric=success-rate namespace=demo`

**Comment by jessesuen** [comment]
> Should the docker image be updated with ca-certificates?

Great insight. I'm pretty certain this is the issue.
