### ISSUE TITLE
How do I trigger my greyscale release to continue when it's in a paused stage?

### ISSUE THREAD

**Issue by HelonLee135** [argoproj/argo-rollouts#3910]
`      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 100
      - pause: {duration: 10}`

As the configuration above shows, I expect to pause when the grey release reaches phase 1, which is when the traffic weights go to 20%. And maintain this state, then wait until I manually execute the relevant command to trigger it to continue with the grey scale publishing. So what command do I execute to make it continue? I've already followed the relevant plugins, such as  “kubectl-argo-rollouts ”

[root@k8s-master01 /root/microYaml/xiaodu/argo-rollouts ]# kubectl argo rollouts version
kubectl-argo-rollouts: v1.7.2+59e5bd3
  BuildDate: 2024-08-13T18:26:20Z
  GitCommit: 59e5bd385c031600f86075beb9d77620f8d7915e
  GitTreeState: clean
  GoVersion: go1.21.13
  Compiler: gc
  Platform: linux/amd64

I looked online and saw that I needed to run this command to get it to continue, but it reported an error. It says that this resume command is not supported。
Do I have a valid need for this? Or is my configuration written wrong.
![image](https://github.com/user-attachments/assets/09e9eedf-cceb-4047-bd91-d3423a1aebc3)

This one is my greyscale configuration:

[Uploading rollout.json…]()

**Comment by kostis-codefresh** [comment]
You need to run the promote command https://argo-rollouts.readthedocs.io/en/stable/generated/kubectl-argo-rollouts/kubectl-argo-rollouts_promote/
