### ISSUE TITLE
argo-rollouts-dashboard Can't it be deployed and used independently

### ISSUE THREAD

**Issue by zhaomingcheng01** [argoproj/argo-rollouts#3971]
After executing using the command line
![image](https://github.com/user-attachments/assets/50783669-ca62-4515-99a4-3fc69f866998)

After independent installation and deployment
![image](https://github.com/user-attachments/assets/0660802f-4371-45c8-98a9-50aa568b2760)
![image](https://github.com/user-attachments/assets/eba4af64-ad38-4c4a-8bf1-abc7a2e8323a)

Can you provide an account system similar to argocd,Or simply embed this page into argocd

version 1.7.2

**Comment by juwon8891-sidewalk** [comment]
+
