### ISSUE TITLE
Remove deprecated templateName field 

### ISSUE THREAD

**Issue by dthomson25** [argoproj/argo-rollouts#408]
With the implementation of https://github.com/argoproj/argo-rollouts/issues/384, we depreciated the templateName field. We need to remove that field and change any of the tests that use it for the v0.9.0 release.

**Comment by jessesuen** [comment]
> we depreciated the templateName field

I think you mean "deprecated" and not depreciated :wink::

> **dep·​re·​cate | \ ˈde-pri-ˌkāt** - to withdraw official support for or discourage the use of (something, such as a software product) in favor of a newer or better alternative

> **de·​pre·​ci·​ate | \ di-ˈprē-shē-ˌāt** - to lower the price or estimated value of

**Comment by jessesuen** [comment]
Fixed
