### ISSUE TITLE
Allow users to specify individual metrics within template to use in a Rollout

### ISSUE THREAD

**Issue by dthomson25** [argoproj/argo-rollouts#410]
When a user references multiple AnalysisTemplates in a rollout, they may want to only use certain metrics within a referenced AnalysisTemplate. We should add a metrics field to the RolloutAnalysisTemplate struct that allows developers to specify which metrics they want to use. If they do not specify any metrics we should use all the listed metrics.

**Comment by jessesuen** [comment]
I think proper workaround is to break it into multiple analysis templates
