### ISSUE TITLE
panic: no Auth Provider found for name "azure"

### ISSUE THREAD

**Issue by jmulcahyTSC** [argoproj/argo-rollouts#449]
I'm on the stable release for argo rollouts and followed the quick start guide on the webpage for this. However, I'm getting this error when trying to list/get my rollouts. I'm using kubectl and my company has AKS clusters. I tried changing the `ClusterRoleBinding` to deploy to the namespace I have my app in, however this is not working. I believe this is a bug in the command itself. I notice that the Go code pulls in `oicp` and `gcp` but not azure. This was a similar issue here: https://github.com/argoproj/argo/issues/1078

Please help.

**Comment by dthomson25** [comment]
Hey @jmulcahyTSC, can you try this image I built: [dthomson25/argo-rollouts:v0.7.2-azure](https://hub.docker.com/layers/dthomson25/argo-rollouts/v0.7.2-azure/images/sha256-e3f067ee4fdc91214d9c8acd3f5085dc45f61185b3721783b76854cf1637db13?context=repo) and see it works? I built it off the v0.7 release branch and I added the `k8s.io/client-go/plugin/pkg/client/auth/azure` import. You can check https://github.com/dthomson25/argo-rollouts/commit/6c84fdc9ca4adbb460a30eba8a4e2dfe9e2ce37f for the changes. If that works, I'll make a PR onto master.

**Comment by jmulcahyTSC** [comment]
I'm currently trying to run the docker image, after pulling it onto my local machine, however I'm getting this error: `level=fatal msg="invalid configuration: no configuration has been provided"`.

The command I ran was: `docker run dthomson25/argo-rollouts:v0.7.2-azure`

**Comment by jmulcahyTSC** [comment]
I'm still having the issue with this image. How have you been testing this image? I have tried re-applying the `install.yaml` that pulled in your new image and that did not work. What I was able to do was I added the `k8s.io/client-go/plugin/pkg/client/auth/azure` to both `kubectl-argo-rollouts/main.go` and `rollouts-controller/main.go` and built the `cmd/` folder. After that, I then simply moved the executable to my PATH and adjusted the file `/manifests/cluster-install/argo-rollouts-clusterrolebinding.yaml` to give the `argo-rollouts` a role in my namespace I am deploying my API to. Doing that fixed my issue.

I am having trouble trying to figure how else to test your docker image. 

Please let me know if I'm doing something wrong, as I may be doing.

**Comment by dthomson25** [comment]
I don't have an Azure account, so I can't really test it with Azure. To make sure that I don't completely break the controller, I tested it in GKE which worked for me. 

Did you try my image after you changed and applied `/manifests/cluster-install/argo-rollouts-clusterrolebinding.yaml`? I think that could be one potential reason it could fail since it may have not had the permission previously.

Also, when you built the binary, did you then use it in a container on the cluster? If not, I think you were using the credentials you have on your local instead of the service account for Argo Rollouts.

**Comment by mariom-consultec** [comment]
Any news on this? I'm having the say issue.
`kubectl argo rollouts list rollouts -n devs
panic: no Auth Provider found for name "azure"

goroutine 1 [running]:
github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/options.(*ArgoRolloutsOptions).RolloutsClientset(0xc0000d9040, 0x7ffeefbffb36, 0x4)
	/go/src/github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/options/options.go:110 +0xf4
github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/cmd/list.NewCmdListRollouts.func1(0xc00026f400, 0xc0000f01c0, 0x0, 0x2, 0x0, 0x0)
	/go/src/github.com/argoproj/argo-rollouts/pkg/kubectl-argo-rollouts/cmd/list/list_rollouts.go:51 +0x69
github.com/spf13/cobra.(*Command).execute(0xc00026f400, 0xc0000f0160, 0x2, 0x2, 0xc00026f400, 0xc0000f0160)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000141b80, 0xc000141b80, 0x24995a0, 0xc0000b2000)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/go/src/github.com/argoproj/argo-rollouts/cmd/kubectl-argo-rollouts/main.go:20 +0xbf`

`kubectl version -o yaml
clientVersion:
  buildDate: "2020-01-15T08:26:26Z"
  compiler: gc
  gitCommit: e7f962ba86f4ce7033828210ca3556393c377bcc
  gitTreeState: clean
  gitVersion: v1.16.6-beta.0
  goVersion: go1.13.5
  major: "1"
  minor: 16+
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-05-29T21:50:25Z"
  compiler: gc
  gitCommit: a2cfecc33f6911261fb8a670d2df2714094002a6
  gitTreeState: clean
  gitVersion: v1.16.9
  goVersion: go1.13.9
  major: "1"
  minor: "16"
  platform: linux/amd64`
