### ISSUE TITLE
Rollback to previous revision

### ISSUE THREAD

**Issue by ivanov-aleksander** [argoproj/argo-rollouts#450]
I try to use blue-green deployment. Deploy Rollout with such starategy
```
    blueGreen:
      activeService: rollouts-demo
      previewService: rollouts-demo-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 3600
```
Updated to new version and as a result have 2 revision.
```
Strategy:        BlueGreen
Images:          alexmt/rollouts-demo:blue
                 alexmt/rollouts-demo:green (active)
Replicas:
  Desired:       5
  Current:       10
  Updated:       5
  Ready:         10
  Available:     5

NAME                                       KIND        STATUS         AGE    INFO
⟳ rollouts-demo                            Rollout     ◌ Progressing  21m    
├──# revision:2                                                              
│  └──⧉ rollouts-demo-5cb98dff86           ReplicaSet  ✔ Healthy      2m53s  active
│     ├──□ rollouts-demo-5cb98dff86-68xnd  Pod         ✔ Running      2m52s  ready:1/1
│     ├──□ rollouts-demo-5cb98dff86-ch7mq  Pod         ✔ Running      2m52s  ready:1/1
│     ├──□ rollouts-demo-5cb98dff86-jl7nt  Pod         ✔ Running      2m52s  ready:1/1
│     ├──□ rollouts-demo-5cb98dff86-rx2bg  Pod         ✔ Running      2m52s  ready:1/1
│     └──□ rollouts-demo-5cb98dff86-zjg4x  Pod         ✔ Running      2m52s  ready:1/1
└──# revision:1                                                              
   └──⧉ rollouts-demo-5544748b5c           ReplicaSet  ✔ Healthy      21m    
      ├──□ rollouts-demo-5544748b5c-fgt7w  Pod         ✔ Running      21m    ready:1/1
      ├──□ rollouts-demo-5544748b5c-ntfps  Pod         ✔ Running      21m    ready:1/1
      ├──□ rollouts-demo-5544748b5c-rhgqm  Pod         ✔ Running      21m    ready:1/1
      ├──□ rollouts-demo-5544748b5c-rqnn9  Pod         ✔ Running      21m    ready:1/1
      └──□ rollouts-demo-5544748b5c-xbcz9  Pod         ✔ Running      21m    ready:1/1
```

How to roll-back to the previous revision?

**Comment by cronik** [comment]
I think you are looking for the [abort](https://argoproj.github.io/argo-rollouts/generated/kubectl-argo-rollouts/kubectl-argo-rollouts_abort/) command. That should abort the current rollout and make revision 1 the only running version.

**Comment by dthomson25** [comment]
Additionally, you should change the Rollout's .spec.template back to the previous version if you want the Rollout to stay at the previous version. The Abort command tells the rollout to stop progressing and revert all steps, but the rollout still thinks the new version is the desired ReplicaSet. If the Rollout leaves the aborted state, it will try to go to the new version. If you change the .spec.template back to the previous version, the rollout will be healthy

**Comment by markrity** [comment]
@dthomson25 Can you give more information on how to change .spec.template to keep the rollout healthy ?

**Comment by jessesuen** [comment]
Simply apply the old manifest. Once the old manifest is applied, the live state matches the desired state and the Rollout is "Healthy"

**Comment by talentrydev** [comment]
So is there no built-in command for performing a rollback? This command (https://argoproj.github.io/argo-rollouts/generated/kubectl-argo-rollouts/kubectl-argo-rollouts_undo/) claims that it performs a rollback, but it doesn't. Same thing applies to the dashboard: there is a "Rollback" button there that doesn't actually perform a rollback. Is this the expected behavior or have I misconfigured something?
