### ISSUE TITLE
Ability to add ephemeral labels to canary/stable pods

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#455]
A common request/use case is for a Rollout to label the canary/stable pods with a user-defined label, for the duration that they are the canary/stable set, and for the labels to be removed from the pods afterwards.

The use case which this enables, is to allow prometheus, wavefront, datadog, etc... queries that can utilize a consistent label, rather than the pod-hash which is always changing.

Rollouts manages ReplicaSets at the moment, and doesn’t manage pods. Changing label of the pod template in the ReplicaSet spec, only takes affect on the next pod created by that ReplicaSet and does not affect the existing pods which were created. For temporary labels to work, Rollouts would now now have to edit pod labels of the pod, after they were created.

Note that starting in v0.8, Rollouts is starting to need access to pods anyways, in order to facilitate [pod restarts](https://github.com/argoproj/argo-rollouts/pull/453).

This issue will be pretty tricky to get right because Rollouts will also need to mutate the existing ReplicaSet pod spec labels depending on the current phase of the rollout (so that pod restarts will get the label), while also mutating the pods associated with the replicaset. 

I imagine the logic would be:
1. during an update, when creating the replicaset with the new spec, ensure the replicaset contains the user defined ephemeral labels.
2. once rollout is complete, mutate the replicaset to remove the ephemeral labels (so that any new pods created from the replicaset will not contain the ephemeral labels)
3. iterate all pods of the replicaset, and mutate all pods to remove the ephemeral labels.

**Comment by jessesuen** [comment]
Response to https://github.com/argoproj/argo-rollouts/issues/583#issue-655023880

Currently, the only thing we inject which can discern between the canary vs. stable ReplicaSets/Pods, is the `rollouts-pod-template-hash` label, which is a simply a hash of the podspec (this is the same technique as Deployments). The problem is that once you create a ReplicaSet with a label/annotation, it is typically intended to be immutable (since changes to ReplicaSets do not affect running pods). This conflicts with the desired to have predictable "canary" and "stable" labels, which actually change meaning the moment a Rollout has been fully promoted (i.e. a running pod which was once considered canary, would now be considered stable).

> Or is it possible for Argo Rollouts to update the labels/annotations (to something called stable) to the existing pods just the moment before it starts to rollout new pods?

That is the idea behind this enhancement. Once a ReplicaSet has been promoted, we now want to change the meaning of "stable" as well as the labels and/or annotations of the running pods. But we also need to update the ReplicaSet so that when it creates new pods (e.g. due to autoscaling), any new pods will also get the correct labels. And as I mentioned earlier, changes to the PodTemplate in a ReplicaSet will only take affect on any **_new_** pods it creates, and not existing ones.

There are also some unknowns in this feature request. Even with this feature implemented, I'm not sure if the underlying tooling will properly react to runtime changes to the pod labels and/or annotations. In other words, even if we change a pods labels, will things like log forwarders reflect the new label when they are sending metrics to providers? I'm not sure that all tools will do so.

**Comment by ozooxo** [comment]
Or alternative to mutate the labels, is there a possibility that you always replace the previous-deployment canary pods to the current-deployment canary pods (so at the end of a deployment, you have identical but distinguishable canary and stable pods), rather than let the canary ReplicaSet to "expand" to stable set?

Through it may get messy when you have multiple `steps` with different weight, and you want the load to be relatively constant for each pod.

**Comment by lavanyachennupati** [comment]
Nice to see this added to v0.10 milestones. Any timeline on when this is expected to be available?
Are there any design docs on how this would be implemented, what the outcome would look like?
Is there any WIP stuff that we could follow/contribute to?

**Comment by davidxia** [comment]
@jessesuen hi, could you clarify what you mean by step 3 above? Just curious. Thanks.

> iterate all pods of the replicaset, and mutate all pods to remove the ephemeral labels.

**Comment by jessesuen** [comment]
> iterate all pods of the replicaset, and mutate all pods to remove the ephemeral labels.

When a ReplicaSet creates pods, it carries forward the labels and annotations in the `spec.template.labels` and `spec.template.annotations`. When a Rollout is updated, we generate a new ReplicaSet, and set `spec.template.labels` with the user defined annotations. So the resulting generated pod would look like:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: guestbook-abc1234-xs2d
  labels:
    role: canary    # this label is user-defined
```

However, once the rollout has completed its update. We no longer want these pods to have these user defined label. Therefore, we would need to update the Pod itself, and remove the label. We cannot do this by simply updating the ReplicaSet, because any changes to the ReplicaSet are only reflected in *new* pods it generates, not existing running ones. Therefore the rollout controller needs to edit pods directly.

Alternatively, we may want the label to be updated with the "stable" ephemeral user-defined labels:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: guestbook-abc1234-xs2d
  labels:
    role: stable    # changed from role: canary since it is no longer canary after the update
```

**Comment by jessesuen** [comment]
> Or alternative to mutate the labels, is there a possibility that you always replace the previous-deployment canary pods to the current-deployment canary pods (so at the end of a deployment, you have identical but distinguishable canary and stable pods), rather than let the canary ReplicaSet to "expand" to stable set?

If I understand your suggestion correctly, by "replace" are you suggesting to restart the pods having the undesired labels, so that new pods are generated with the desired labels?

I would say if mutating the labels ultimately does not have the desired affect (e.g. pod metric collectors and log forwarders do not notice the change in labeling), then I think there is no option but to restart pods so that the tooling can notice the new labeling.

**Comment by jessesuen** [comment]
> Nice to see this added to v0.10 milestones. Any timeline on when this is expected to be available?
Are there any design docs on how this would be implemented, what the outcome would look like?
Is there any WIP stuff that we could follow/contribute to?

Given that v0.9 was just released yesterday, we're likely~2 months from v0.10.

Step 1 will be to garner agreement on the syntax in the Rollout spec
Step 2 should be to perform some research on how retroactively changing a label on a pod might affect popular metric/log collectors such as kube-state-metrics, datadog, etc... In other words, do they notice changes in labels so that they are ultimately reflected when querying the metric provider.
Based on findings in step 2, I think we can make some decisions on how the behavior would look like (e.g. if we need to restart pods after an update for new labels to be noticed).

**Comment by davidxia** [comment]
> Step 2 should be to perform some research on how retroactively changing a label on a pod might affect popular metric/log collectors such as kube-state-metrics, datadog, etc... In other words, do they notice changes in labels so that they are ultimately reflected when querying the metric provider.

I'm not sure about other metric/log collectors, but for my use case I have a metric collector running inside the Pod as a sidecar that adds tags to its metric points. I was thinking of having this sidecar get the ephemeral label as an env var via the K8s Downward API. So I think the Container itself and thus Pod will have to be restarted to get the new labeling. @mclarke47 is my thinking correct?

**Comment by jessesuen** [comment]
Proposed spec to support this:

```yaml
spec:
  strategy:
    canary:
      stableMetadata:
        labels:
          role: stable
      canaryMetadata:
        labels:
          role: canary
      steps:
      - setWeight: 50
      - pause: {}
```

**Comment by jessesuen** [comment]
> Step 2 should be to perform some research on how retroactively changing a label on a pod might affect popular metric/log collectors such as kube-state-metrics, datadog, etc... In other words, do they notice changes in labels so that they are ultimately reflected when querying the metric provider.

I've verified with prometheus-operator/kube-state-metrics, the new pod labels get reflected in the metrics within minutes.

**Comment by mclarke47** [comment]
Sounds good, we will assume that the label will change but the pod will not be re-created. We should be able to account for this with our metric setup.

**Comment by jessesuen** [comment]
> we will assume that the label will change but the pod will not be re-created. 

Correct

**Comment by chihaiaalex** [comment]
Hello! Regarding Step 2. I would like to also give you some input with regards to my described use case: https://github.com/argoproj/argo-rollouts/issues/589. Is it enough to patch the pod with the new label to mimic what ArgoRollouts would do?

**Comment by irvifa** [comment]
I was wondering if this Pr https://github.com/argoproj/argo-rollouts/pull/770 is ready to be reviewed

**Comment by RochesterinNYC** [comment]
The implementation of #770 and some internal changes to our metrics emission shim to attach a special tag to metrics emitted from canary Pods has allowed us to do baseline vs. canary comparisons during rollout analysis.

As a follow-up to this, we have a few use cases where we want to do baseline vs. canary comparisons for a few metrics that are emitted from some very common K8s metric tools:
- Ex. comparison of container-restarts (`kube_pod_container_status_restarts_total` metric) that's emitted from [`kube-state-metrics`](https://github.com/kubernetes/kube-state-metrics)
- Ex. comparison of CPU usage (`gke-container-cpu-usage` metric) that's emitted from [`kube-resource-metrics`](https://kubernetes.io/docs/tasks/debug-application-cluster/resource-metrics-pipeline/)

How might we or Argo go about supporting differentiating the metrics emitted by these tools for canary vs. baseline Pods?

Right now, the only difference I can tell of between canary vs. baseline Pods is via this new label feature (all the Pods are named similarly/do not have `canary` in their names or etc.), though third party metric emitters like `kube-resource-metrics` or `kube-state-metrics` will not consider or pass along this kind of Pod label at all into their metric tags.

**Comment by cooperbenson-qz** [comment]
Is there any reason this wasn't implemented for the BlueGreen strategy as well? I'm looking to file a PR adding it, but wanted to see if there were any reasons that would be a bad idea
