### ISSUE TITLE
Metrics distinguishing "before" and "after"

### ISSUE THREAD

**Issue by dimbleby** [argoproj/argo-rollouts#458]
Hi, 

Does Argo Rollouts do anything that would allow me to distinguish eg between "blue" and "green" pods, or between pods that are in the "after" part of a canary deployment as opposed to the "before" part?

I'm thinking eg it could put a label on them, but I have not found such a thing.

The particular use case that I have in mind would be to be able to compare the metrics for new and old things - either in an AnalysisTemplate, or on my regular dashboards.

Thanks!

**Comment by dimbleby** [comment]
Ah yes, that sounds like the sort of thing I was hoping for!

I'm actually mostly interested in the canary strategy: if that proposal can also make sense for canaries, then let's close this as a duplicate.

(Sorry that I didn't spot this when raising.)

**Comment by jessesuen** [comment]
Yea I think we can close as dup of #455
