### ISSUE TITLE
User controlled handling of NaN metric

### ISSUE THREAD

**Issue by HatsuneMiku3939** [argoproj/argo-rollouts#459]
I know NaN as treat as 'Inconclusive' after #180. 
But, I think the treat of NaN is very dependent on use cases.

- Some of the users may want NaN as treat as 'Inconclusive'.
- On the other hand, some other users may want NaN as treat as 0 or false...something else.

To allow users to handle NaN himself, 

- A default treatment of NaN should be override per 'AnalyzeTemplate'.
- 'utils/evaluate/evaluate.go' should export more math-related functions.

**Comment by jessesuen** [comment]
I wonder if this already can be handled by an expression in `successCondition`, e.g.
`result == NaN || result > 90`

**Comment by HatsuneMiku3939** [comment]
@jessesuen 

The current implementation treats NaN as an error.

- https://github.com/argoproj/argo-rollouts/blob/master/metricproviders/prometheus/prometheus.go#L98
- https://github.com/argoproj/argo-rollouts/blob/master/metricproviders/prometheus/prometheus.go#L118

**Comment by jessesuen** [comment]
I confirmed that Rollout cannot use an expression like: `successCondition: result[0] == NaN || result[0] > 90`. I feel that it should 

In the meantime, a workaround is `inconclusiveLimit: 999999` to treat it as success.

**Comment by byangtri** [comment]
I see that there is a new feat allowing users to handle NaN result to be successful, however, I am encountering issues treating NaN as successful instead of Inconclusive. I would like NaN to be treated as successful in my analysis run. Any advice on doing this, below is my successCondition

`  metrics:
  - name: success-rate
    successCondition: isNaN(result[0]) || result[0] >= 0.10`
