### ISSUE TITLE
Blue-Green Rollout is paused after first syncronization

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-rollouts#48]
The Rollout automatically switched to `paused` state after the first synchronization even there is only `green` version if deployment. The Rollout should be paused only if there are both `green` and `blue` and the user has to promote `blue` to `green`.

**Comment by dthomson25** [comment]
The Rollout is being paused because the newRS is not fully saturated when it reaches the reconcile preview service function.

Code: https://github.com/argoproj/argo-rollouts/blob/73df5f080a6028eacb26e5118ce01e1bc115caa7/controller/service.go#L43-L46
