### ISSUE TITLE
ALB Ingress action annotation is hard to read

### ISSUE THREAD

**Issue by dthomson25** [argoproj/argo-rollouts#492]
The ALB Ingress's action annotation is difficult to read as it is stored as a single line of JSON with no lines or tabs. Check out the image below for an example

![image](https://user-images.githubusercontent.com/8616845/81090914-4cfa8c80-8eb3-11ea-8552-4ec42c50f1a7.png)

We should add new lines and tabs to the JSON string to make it easier to read.

**Comment by jessesuen** [comment]
Newlines and tabs will simply appear as `\n` and `\t` in the annotation. It's invalid to have those characters in json.
