### ISSUE TITLE
The progressDeadlineSeconds field is missing in Rollout spec

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-rollouts#50]
The `progressDeadlineSeconds` is field is missing in Rollout spec, so it never reaches degraded state.

**Comment by dthomson25** [comment]
PR #54 adds the implementation of progressDeadlineSeconds and I need to make one other small PR to add some validation to the progressDeadlineSeconds

**Comment by dthomson25** [comment]
Added validation with https://github.com/argoproj/argo-rollouts/pull/62 to fix the issue
