### ISSUE TITLE
Invalid template postPromotionAnalysis does not cause rollback

### ISSUE THREAD

**Issue by johnkost** [argoproj/argo-rollouts#504]
I'm working on creating an Analysis template to use with my postPromotionAnalysis. I was modifying the successCondition and triggered a rollout. I watched the rollout occur and then saw the error symbol (using Kubectl plugin); however, the rollout was not rolled back. After diving into the rollout controller logs, I found the type error (expected).

**Comment by jessesuen** [comment]
Could you provide details about:

1. the spec error which you induced
2. the error you saw in the logs

Note that we have added improved validation in v0.9 so I think one thing to check if the problem still occurs there.

**Comment by johnkost** [comment]
Let me see if I can reproduce on v0.9

**Comment by jessesuen** [comment]
I believe this to be fixed in v0.9.2. Please reopen if you can reproduce it there
