### ISSUE TITLE
Rollout Patch doesn't work on OpenShift cluster

### ISSUE THREAD

**Issue by zroubalik** [argoproj/argo-rollouts#508]
On a clean and fresh OpenShift cluster I did these steps:
1. install argo-rollouts controller by deploying install.yaml (https://argoproj.github.io/argo-rollouts/#quick-start) (and explicitly added RBAC for finalizers)
2. create Rollout resource from example (https://github.com/argoproj/argo-rollouts/blob/master/examples/rollout-bluegreen.yaml) 

Rollout resource is deployed, there aren't any errors or issues in the controller log. But this resoruce doesn't have `Status` subresource, (so for example HPA based scaling si not working, but there are other bad consequences for sure).

@dthomson25 found out that patch operation doesn work (it does nothing to the resource)

Tried on:
- Openshift 4.4 (kubernetes v1.17)
- Openshift 4.2 (kubernetes v1.14)

**Comment by zroubalik** [comment]
@johnkost haven't you hit the same issue on OpenShift? (asking since you created OpenShift related PR in HELM repo)

**Comment by johnkost** [comment]
Yes. I ran into this on Openshift 3.11. The PR I created fixed the issue for me (I was seeing failed events related to deleting blockOwner)

**Comment by jessesuen** [comment]
Fixed by https://github.com/argoproj/argo-rollouts/pull/510 (I believe).
