### ISSUE TITLE
Traefik Support

### ISSUE THREAD

**Issue by mikesir87** [argoproj/argo-rollouts#516]
In addition to the current controllers, it would be great to support Traefik!

The [TraefikService](https://docs.traefik.io/routing/providers/kubernetes-crd/#kind-traefikservice) object supports the ability for weighted round robin load balancing and traffic mirroring when using Traefik as ingress.

As a quick pass, an `IngressRoute` is configured to send traffic to a `TraefikService`, which then provides configuration for sending traffic to one or more Kubernetes `Service` objects. While I haven't dived into Argo's architecture, I imagine it wouldn't be too complicated to own and manage the TraefikService object.

While I may not be the best to contribute code, I could try or help with docs and testing the implementation. Or if someone wants to chat on Slack and give me direction on how/where to get started, I can take a crack at it.

**Comment by debu99** [comment]
we already use traefik ingressroute for blue/green deployment, we would like to try rollout once it supports traefik

**Comment by debu99** [comment]
https://troy.wang/docs/kubernetes/posts/argo-rollouts-support-traefik/

**Comment by vishalct** [comment]
We want to leverage traefk for cananry deployment.
I tried following the document to use traefik for traffic management with canary 
https://troy.wang/docs/kubernetes/posts/argo-rollouts-support-traefik/
It failed, with below error.
```
$ kubectl apply -f nginx-rollout.yaml -n argo-demo
error: error validating "nginx-rollout.yaml": error validating data: ValidationError(Rollout.spec.strategy.canary.trafficRouting): unknown field "traefik" in io.argoproj.v1alpha1.Rollout.spec.strategy.canary.trafficRouting; if you choose to ignore these errors, turn validation off with --validate=false

```
what code level changes i need to do to make it work? since it's written in Chinese, I am finding it difficult to follow.
@debu99 can u help me here

**Comment by kostis-codefresh** [comment]
It seems that Traefik will have an implementation for the Kubernetes Gateway API https://gateway-api.sigs.k8s.io/implementations/#traefik

So Traefik support might be available after implementing https://github.com/argoproj/argo-rollouts/issues/1438

**Comment by kennethtxytqw** [comment]
Is this possible today?

**Comment by PhilippPlotnikov** [comment]
https://github.com/argoproj/argo-rollouts/pull/1907
