### ISSUE TITLE
controller-gen not foud in $PATH

### ISSUE THREAD

**Issue by Ivan-Zhu** [argoproj/argo-rollouts#517]
make codegen
./hack/update-mocks.sh
./hack/update-codegen.sh
Generating deepcopy funcs
Generating clientset for rollouts:v1alpha1 at github.com/argoproj/argo-rollouts/pkg/client/clientset
Generating listers for rollouts:v1alpha1 at github.com/argoproj/argo-rollouts/pkg/client/listers
Generating informers for rollouts:v1alpha1 at github.com/argoproj/argo-rollouts/pkg/client/informers
./hack/update-openapigen.sh
go run ./hack/gen-crd-spec/main.go
panic: exec: "controller-gen": executable file not found in $PATH

**Comment by jessesuen** [comment]
controller-gen is built in `dist` directory and the makefile add the dist directory in the path
