### ISSUE TITLE
Contour support

### ISSUE THREAD

**Issue by victornoel** [argoproj/argo-rollouts#523]
It would be great to have contour support for traffic management.

**Comment by ghostsquad** [comment]
Can you describe more specifically what this is asking for?

**Comment by victornoel** [comment]
@ghostsquad yes sorry.

So Contour is an ingress controller, like nginx-ingress. I saw in the doc that the latter was supported for traffic management, so I thought naively that contour was not.

I have no idea what must be done to support contour, maybe it's already working because argo-rollouts is only using ingresses?

**Comment by ghostsquad** [comment]
@victornoel based on the docs (https://argoproj.github.io/argo-rollouts/features/traffic-management/#how-does-argo-rollouts-enable-traffic-management) this is the right place for the request. I just know from experience that very sparse issues won't get as much attention as tickets like #516 which asks for Traefik Traffic Management, that go into a little bit more depth about the specific integration problem, including links back to Traefik docs. (Also I'm not a maintainer of this repo, just browsing)

**Comment by kostis-codefresh** [comment]
It seems that contour will have an implementation for the Kubernetes Gateway API https://gateway-api.sigs.k8s.io/implementations/#contour

So Contour support might be available after implementing https://github.com/argoproj/argo-rollouts/issues/1438

**Comment by ghostsquad** [comment]
not stale

**Comment by wilsonwu** [comment]
@jessesuen Hi Jesse, do you think support contour by plugin way is acceptable? We'd like to contribute.

**Comment by zachaller** [comment]
@wilsonwu Yes, this is exactly what plugins where created for and they will go out in 1.5 there is not a lot of docs yet but there is this https://argo-rollouts.readthedocs.io/en/latest/plugins/ and some light weight example ones in the argo rollouts repo [here](https://github.com/argoproj/argo-rollouts/tree/master/test/cmd) I am also planing on doing a blog series on creating plugins as well.

**Comment by wilsonwu** [comment]
@zachaller Thanks for your reply, so could you please help to create a repo: rollouts-contour-httpproxy-plugin

**Comment by zachaller** [comment]
@wilsonwu https://github.com/argoproj-labs/rollouts-contour-trafficrouter-plugin

**Comment by wilsonwu** [comment]
Got it, we will start to contribute, and any update will be synced here.

**Comment by izturn** [comment]
nice

**Comment by wilsonwu** [comment]
@zachaller, the contour trafficerouter plugin v0.1.0 released: https://github.com/argoproj-labs/rollouts-contour-trafficrouter-plugin/releases/tag/v0.1.0

**Comment by zachaller** [comment]
@wilsonwu awesome, whenever you think you are ready feel free to open a PR agains the docs here https://argo-rollouts.readthedocs.io/en/latest/features/traffic-management/plugins/#add-your-plugin-here

**Comment by wilsonwu** [comment]
> @wilsonwu awesome, whenever you think you are ready feel free to open a PR agains the docs here https://argo-rollouts.readthedocs.io/en/latest/features/traffic-management/plugins/#add-your-plugin-here

Sure, I will update it ASAP.

**Comment by zachaller** [comment]
Closing due to it being implemented in both gateway api and as it's own plugin
