### ISSUE TITLE
Trying to watch resource types that do not exist

### ISSUE THREAD

**Issue by wnagele** [argoproj/argo-rollouts#531]
Noticed that the controller keeps trying to add a watch on a resource type that is not installed in our cluster. In this case we do not have Istio installed and are not using those capabilities. It would make sense to check if the relevant types exist before trying to process them.
```
time="2020-06-10T15:42:23Z" level=warning msg="Error with watch: the server could not find the requested resource"
time="2020-06-10T15:42:24Z" level=info msg="Starting watch on resource 'virtualservices'"
time="2020-06-10T15:42:24Z" level=warning msg="Error with watch: the server could not find the requested resource"
time="2020-06-10T15:42:26Z" level=info msg="Starting watch on resource 'virtualservices'"
time="2020-06-10T15:42:26Z" level=warning msg="Error with watch: the server could not find the requested resource"
time="2020-06-10T15:42:30Z" level=info msg="Starting watch on resource 'virtualservices'"
time="2020-06-10T15:42:30Z" level=warning msg="Error with watch: the server could not find the requested resource"
```

/kind bug

**Comment by jessesuen** [comment]
FWIW, it was actually a design decision to keep attempt the request, in order to avoid adding configuration knobs in the controller. But I thought it was at a lower frequency (e.g. 5-10 minutes).

**Comment by dmizelle** [comment]
I'm definitely seeing this too as well. Would we want to revisit the idea of being able to disable certain "types" of handling routing? 

Something like a flag of `--disable-isto`, `--disable-nginx`, so that being "on" is the default?

**Comment by jessesuen** [comment]
So the annoying log message has been suppressed with https://github.com/argoproj/argo-rollouts/pull/656, but rollouts does still has a "feature" to auto-detect istio at 10 minute intervals.
