### ISSUE TITLE
Option to skip rollout on helm rollback

### ISSUE THREAD

**Issue by markrity** [argoproj/argo-rollouts#537]
Hi, we are using argo-rollouts blue green deployments , but we want to able to perform `helm rollback` without triggering the blue green rollout, since we need it as fast as possible, is there a way to make it skip the rollout process ? 

Thanks.

**Comment by carlosdoordash** [comment]
Have you tried `helm upgrade`? We use `helm upgrade` with the old values.yaml and do benefit of the immediate rollback where only the service selector is changed to use the old `rollouts-pod-template-hash`.

I haven't tried `helm rollback` but, in theory, it should be no different than `helm upgrade` from Argo Rollouts perspective.

**Comment by markrity** [comment]
@carlosdoordash Hi , thank you for your answer,
To perform rollback with old values , we will have to store somewhere this old values (values like image tags )

Some how helm rollback does it the long way once again , it acts like it a completely new revision and does the whole blue/green process once again.

also --skip-all-steps doesn't work on blue/green :(

**Comment by jessesuen** [comment]
In current version of Rollouts, there are two knobs which you can allow a "fast-tracked" rollback using the blue-green strategy (which would skip the pause and analysis):

* [`scaleDownDelaySeconds`](https://argoproj.github.io/argo-rollouts/features/bluegreen/#scaledowndelayseconds)
* [`scaleDownDelayRevisionLimit`](https://argoproj.github.io/argo-rollouts/features/bluegreen/#scaledowndelayrevisionlimit)

When Rollouts detects that it is moving back to a ReplicaSet which is **still scaled up**, it performs the fast-rollback and skips the pause, and any analysis.

The caveat to the current solution that you have to leave the old stack still running for the fast-tracked rollback to occur, which might be expensive. I recently filed https://github.com/argoproj/argo-rollouts/issues/557 to provide more functionality for intelligent rollbacks. I think we could extend this idea to give users control on when a fast-tracked rollback should occur.

> also --skip-all-steps doesn't work on blue/green :(

This is an oversight and should be fixed.

**Comment by markrity** [comment]
@jessesuen Thanks , looking forward for this to be accepter/implemented !

**Comment by jessesuen** [comment]
Closing in favor of https://github.com/argoproj/argo-rollouts/issues/574.
