### ISSUE TITLE
Unable to create AnalysisRuns with provider type Kayenta

### ISSUE THREAD

**Issue by kcboschert** [argoproj/argo-rollouts#541]
When trying to create an AnalysisRun from an AnalysisTemplate with `kayenta` defined as the provider, we received the following error:
```
analysis spec invalid: metrics[0]: no provider specified
```

The AnalysisRun and AnalysisTemplate CRDs are both configured to allow for this value:
https://github.com/argoproj/argo-rollouts/blob/fbe33e87dcd3a3cb24f1d53c993bfaa8bf52d746/manifests/crds/analysis-template-crd.yaml#L2574
https://github.com/argoproj/argo-rollouts/blob/fbe33e87dcd3a3cb24f1d53c993bfaa8bf52d746/manifests/crds/analysis-run-crd.yaml#L2580

But it looks like the validation in the Analysis factory isn't expecting Kayenta as an option:
https://github.com/argoproj/argo-rollouts/blob/fbe33e87dcd3a3cb24f1d53c993bfaa8bf52d746/utils/analysis/factory.go#L140-L155

**Comment by dthomson25** [comment]
Yikes, that's a bad one. I'll make a PR to fix that.
