### ISSUE TITLE
Error Message for Invalid Comparison in AnalysisRun

### ISSUE THREAD

**Issue by gavin-db** [argoproj/argo-rollouts#547]
Currently, if an AnalysisRun receives Prometheus metrics in a list, for example [8], it will fail the comparison without any meaningful error message. 

![image](https://user-images.githubusercontent.com/65616577/85427994-61611a00-b531-11ea-94b4-947885271f18.png)

Should add an informative error message if the comparison is invalid (e.g. checking if an array is less than or equal to an integer).

**Comment by jessesuen** [comment]
We now have better errors in the analysis run, which get surfaced upwards
