### ISSUE TITLE
The traffic ActualWeight's calculation is wrong

### ISSUE THREAD

**Issue by henrywangx** [argoproj/argo-rollouts#568]
The actualWeight should be 5% for the[ official example](https://argoproj.github.io/argo-rollouts/getting-started/nginx/). But it's 50%.
I think the actualWeight's [calculation](https://github.com/argoproj/argo-rollouts/blob/master/pkg/kubectl-argo-rollouts/info/rollout_info.go#L73) method is not correct.
It should use the actual ingress/smi's weight to calculate the actual weight.

**Comment by henrywangx** [comment]
sorry, I found the **actualWeight** indicates the pod's weight not traffic's weight. Yes it misleads my mind.

**Comment by jessesuen** [comment]
I think this is a valid bug. The output from the kubectl plugin was written before mesh and ingress traffic routing support was implemented, and it was only displaying pod weights. The plugin output should be updated to understand when traffic routing is used, and have `actualWeight` be equal to the `setWeight`.

**Comment by jessesuen** [comment]
Fixed by https://github.com/argoproj/argo-rollouts/pull/584
