### ISSUE TITLE
Docker image for ARM32/64

### ISSUE THREAD

**Issue by airmonitor** [argoproj/argo-rollouts#582]
Hello.

Will it be possible to extend build process to produce also ARM compatible images?

Regards
Tom

**Comment by jessesuen** [comment]
We do this in other argo projects so I'm sure the answer is yes. Contributions welcome!

**Comment by airmonitor** [comment]
You are using circle right? 

I was not able to find arm image from circle though. 

I can help you with building arm image on gitlab or aws codebuild of this is possible and then push image to docker registry.. 

I will be building argo, linux plugin and rollouts for myself and phishing to public docker registry but more suitable approach would be to push it to your docker registry :)
