### ISSUE TITLE
BlueGreen/Canary deployment - Custom labels for Pods that are in preview/canary   

### ISSUE THREAD

**Issue by chihaiaalex** [argoproj/argo-rollouts#589]
Use case: Two microservices, A and B, that are deployed using a blue green/canary deployment. Microservice A talks to microservice B via http. While both are in preview/canary mode, we would like _Microservice A preview/canary_ to talk only with _Microservice B preview/canary_. 

The solution we found for the routing between the preview service and active service is by using Istio's HTTPMatchRequest.SourceLabels (https://discuss.istio.io/t/route-http-traffic-based-on-source-pod/4380/3). This way we would do it transparently without any logic inside the application.

The only thing that we're missing is a custom label on the pods that are in preview/canary (this label would be removed from the pod when the version is promoted). 

Is there a way we can inject this label by using any of the ArgoRollouts mechanisms? (Maybe an experiment or maybe we can use the rollouts-pod-template-hash label)

I know this use case might sound as an anti pattern (and it is), but this is an issue that some of our teams are facing and we are looking for a solution with minimal impact to them.

Thanks!

**Comment by jessesuen** [comment]
Duping to https://github.com/argoproj/argo-rollouts/issues/455, which would allow user-defined labels to pods for the duration in which they are the canary/stable.
