### ISSUE TITLE
Ability to restart more than one pod at a time

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#592]
Currently, a restarting a Rollout iterates the pods, and deletes them one by one, ensuring the new pod reaches readiness before moving onto the next. This is very slow if there are many replicas in a Rollout and the pods have a long start-up time. A rollout restart could be sped up if we could honor "maxUnavailable" of the canary spec. However, since we need to also speed-up Rollouts of a blue-green deployment, we should not limit ourselves to maxUnavailable since that field does not exist in the blueGreen strategy. We may need something more generic, such as a `spec.restartStrategy` to provide controls over this.

**Comment by jessesuen** [comment]
Another issue is that we currently cannot surge **_up_** when restarting a Rollout, since we only terminate the pods. Not sure this is easily solve-able.

**Comment by smitthakkar96** [comment]
incase of restart we simply bring up new pods all together and then swap similar to bluegreen deployment

**Comment by jessesuen** [comment]
Resolved by https://github.com/argoproj/argo-rollouts/pull/833. Note that blue-green does not support multi-pod restarts at this time. A separate issue can be filed for it if needed.
