### ISSUE TITLE
Update rollout replicas the controller doesn't reflect

### ISSUE THREAD

**Issue by ngtuna** [argoproj/argo-rollouts#594]
For example, I update replica number in this sample demo: https://github.com/argoproj/argo-rollouts/blob/master/docs/getting-started/basic/rollout.yaml.

Expect: number of pod will be reflected.
Actual: nothing happens.

**Comment by jessesuen** [comment]
@ngtuna this issue, as well as https://github.com/argoproj/argo-rollouts/issues/595 are indications that your controller seems to have a problem reconciling rollouts. Please check logs to see what might be happening.

**Comment by ngtuna** [comment]
It seems that. Good to close now.
