### ISSUE TITLE
nodeSelector update doesnt work

### ISSUE THREAD

**Issue by ngtuna** [argoproj/argo-rollouts#595]
Pod are rolled out successfully. I want to put a constraint to only some nodes that pods are allowed to run on. Edit the rollout crd doesn't change anything.

if I put nodeSelector prior to creating rollout crd, it works.

**Comment by jessesuen** [comment]
nodeSelector is part of the pod template spec, and when updated, a new hash would be calculated, triggering a new rollout. I think some other change might be what is causing the update to not happen. Controller logs during the update will be necessary to debug further.

**Comment by ngtuna** [comment]
i'm going to close the issue now
