### ISSUE TITLE
Rollouts should add owner references to Services

### ISSUE THREAD

**Issue by dthomson25** [argoproj/argo-rollouts#6]
Per the [Controller Ref proposal](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/controller-ref.md), there are three laws that a controller should follow:

1. Take ownership of a Object
1. Don't interfere with an object that the controller does not own
1. Don't share owned objects with other controllers

We aren't respecting these laws with the service objects because the rollout controller modifies services that the controller does not own.  To be in line with the Kubernetes Best standards, the rollout controller should be following these laws.  However, the owner references are also leveraged with Kubernetes garage collection, and the rollout controller should not delete a service when a rollout is deleted.  Instead, the rollout controller should orphan the service.  More investigation is required to see if it is possible to add this type of behavior in the rollout controller.

**Comment by jessesuen** [comment]
Relevant discussion about ownership references for another project (workflows) over a year ago:

jessesuen [11:39 PM]
Can someone explain the `controller` field in ownerReferences? e.g.:
```
- apiVersion: workflows.argoproj.io
    blockOwnerDeletion: true
    controller: true
    kind: Workflow
    name: hello-world-fwr28
    uid: e0f89c23-f1dc-11e7-9bef-06b1d000076b
```
A user hit a SIGSEGV in k8s 1.8.5 scheduler when `controller: true` was omitted. I’m unclear about the meaning of `controller: true` and if our controller should be setting it or not.
https://github.com/argoproj/argo/issues/656
GitHub
K8s Scheduler crashes · Issue #656 · argoproj/argo
What did you do? Deployed Argo on K8s 1.8.5 and the hello-world example What did you see? kube-scheduler crashes for some reason (See the exception below) What did you expect? a running example K8s...


ash2k [1:39 AM]
@ jessesuen hopefully this doc will clarify things https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/controller-ref.md
GitHub
kubernetes/community
Kubernetes community content

jessesuen [2:15 AM]
Thanks @ ash2k, yes that helps. So is it a general rule of thumb that if your custom resource is creating other resources, you should be setting `controller: true` for those child resources (in addition to the name/uuid/kind)? We currently do not set `controller: true` but things like cascaded deletion still function properly.

jhorwit2 [2:24 AM]
@ jessesuen `metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"` has a `NewControllerRef` method you can use to help create owner references.
Here is a couple good posts i found on it as well
https://blog.openshift.com/garbage-collection-custom-resources-available-kubernetes-1-8/
https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/
OpenShift Blog
Garbage Collection of Custom Resources Available in Kubernetes 1.8 – OpenShift Blog
Learn how to integrate custom resources with the garbage collector in Kubernetes 1.8.
Sep 29th, 2017
Kubernetes
Garbage Collection
Production-Grade Container Orchestration

jessesuen [2:30 AM]
Looks like that function will set controller: true. I will use that function. Can’t think of a scenario where you would set name/uuid/kind but not controller: true. Thanks for the pointer!

ash2k [3:39 AM]
@ jessesuen a scenario where object A depends on object B but B is not its controller. For example a Deployment and a ConfigMap. If you want the Deployment to be deleted when ConfigMap is deleted you can use owner reference with controller: false. Perhaps the name "OwnerReference" is a bit misleading.

deads2k [5:27 AM]
@ ash2k I think its actually the "controller" flag that is confusing.  In general, it's entirely possible to end up with resources managed by multiple controllers.  I still struggle to find any value added by putting a controller flag in the ownerref.
@ jessesuen simple case? You have one controller managing scale of a thing and another controller managing the podspec of the thing.  Any controller creating a deployment, replication controller, or replicaset hits this with HPA
@ jessesuen Also cases around keeping content of a secret in sync with something via a controller, but the controller doesn't own the lifecycle of the thing.
@ jessesuen and not all controllers are related to resources.  You can imagine controllers driven by external config.  Basically, the controller flag and the 'only one of' semantic doesn't reflect a general pattern in keeping with the meta API

**Comment by jessesuen** [comment]
I don't necessarily think controllers follow these laws. 

For example when HPA modifies a deployment, it does not mutate ownerReference of the deployment. By that token, when Rollouts modifies a preview service, it doesn't necessarily need to add itself as an ownerReference.

**Comment by jessesuen** [comment]
closing wontfix since I don't think we should take ownership of these objects and cause them to be deleted when a rollout is deleted.
