### ISSUE TITLE
Support gloo

### ISSUE THREAD

**Issue by snuggie12** [argoproj/argo-rollouts#620]
We're very interested in using rollouts and use gloo as our gateway and istio as our service mesh. It seems like istio will work for all services within the mesh. 

Could gloo be added to the support list as a gateway handling north/south traffic?

**Comment by jessesuen** [comment]
We don't have much gloo experience but Rollouts manages VirtualServices, so if gloo is pointing to the VirtualService, in theory your use case **_might_** be already supported, unless you are asking for a gloo specific integration.

**Comment by snuggie12** [comment]
I read on the website if something wasn't supported to request it. However, I think the istio `VirtualService` (gloo also has a resource called that,) with gateway set to `mesh` might work. It might not though because gloo has no sidecar for outbound traffic, but rather is running envoy and can use the same mtls certs.

In the next couple of weeks I'll give it a shot, but in the meantime I wanted to make the request for official support.

**Comment by snuggie12** [comment]
After reading over rollouts and istio more this will definitely work for any services for east/west traffic, but any north/south traffic that goes through gloo will not work.

So this would be requesting that gloo gets added to the list as a standalone api gateway probably most similar to the nginx IC.

**Comment by lowkeyliesmyth** [comment]
I would definitely be interested in this feature too. Functionally the integration should be similar to that of the Ambassador integration.

**Comment by kostis-codefresh** [comment]
It seems that Gloo will have an implementation for the Kubernetes Gateway API https://gateway-api.sigs.k8s.io/implementations/#gloo-edge

So Gloo support might be available after implementing #1438

**Comment by zachaller** [comment]
This will also probably be coming closing due to the two options: https://github.com/argoproj/argo-rollouts/issues/2876

**Comment by kostis-codefresh** [comment]
Supported via the API gateway https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/tree/main/examples/gloo-gateway

There is also a native plugin as well https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-glooplatform
