### ISSUE TITLE
Provide OpenApi Definition in Json for Kustomize CRD's

### ISSUE THREAD

**Issue by Gknoblau** [argoproj/argo-rollouts#63]
I'd like to add rollouts as a CRD to kustomize. An example of how to do this can be found here: https://github.com/kubernetes-sigs/kustomize/blob/master/docs/kustomization.yaml#L215

The provided generated yaml does not work as kustomize requires json.
https://github.com/argoproj/argo-rollouts/blob/master/manifests/crds/rollout-crd.yaml

Converting the above yaml to json by commenting out https://github.com/argoproj/argo-rollouts/blob/master/hack/gen-openapi-spec/main.go#L82-L85 does not resolve the issue either.

**Comment by jessesuen** [comment]
I think we can close this because we document the transformer configs here needed to properly work with kustomize here:
https://github.com/argoproj/argo-rollouts/tree/master/docs/features/kustomize
