### ISSUE TITLE
Control over the replica scale of canary stack (when trafficRouting is used)

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#669]
Spawned from https://github.com/argoproj/argo-rollouts/issues/556

NOTE: this proposal has is only related to canary with trafficRouting, and does not apply to the basic canary strategy.

EDIT: I was completely wrong about scaling the canary stack to 100%. We actually match the canary stack scale to the current weight. However, we always leave the stable RS scaled to 100%. So the only thing that I think should be done is to provide a `setCanaryScale` step, to allow control over the canary scale.

~Currently, when we deploy the canary stack (when trafficRouting is used), we scale the canary stack to 100%. This is done even if there is a small traffic weight (e.g. 5%) being directed to the canary, thereby wasting of resources. Some background on why the current design is to scale the canary stack to 100%:~

~1. code complexity. it was easier to just bring up the new stack's to match the old stack, and avoid matching the scale of the canary ReplicaSet to the current weight. For example, progressing through the steps would mean we have to wait until the canary replicas are all ready, before actually adjusting the weight in istio/nginx/etc...~

~2. The wasted compute was though to be a temporary situation (relative to the overall running of the service). Of course, this argument becomes less valid for a strategy which wants to run a 5% canary for 24 hours.~

3. It was debated whether or not the stable stack should also adjust to match the weights. For example, if the canary weight was 95%, should the stable replicaset be scaled down to 0.05 * replica count? Ultimately, it was decided that the stable stack should not be downscaled, because of the situation where the rollout needed to be aborted, and traffic should shift back ASAP to the running, stable stack, not held up by pod scheduling/start up.

This enhancement proposal is to provide users with some controls on how to scale the canary. Here are some ideas:

1. always match the canary scale to the current canary weight. e.g. if the current canary weight is 20%, and the rollout's `spec.replicas: 10`, then the canary scale should be 2.

2. explicit scale values in steps (https://github.com/argoproj/argo-rollouts/issues/556#issuecomment-679468231):

```yaml
steps:
- setWeight: 10
- setCanaryScale:
     replicas: 1     # explicit count
- setCanaryScale:
     weight: 10     # percentage of spec.replicas
```

3. Separate HPA for the canary (https://github.com/argoproj/argo-rollouts/issues/556#issuecomment-679468231). Here we would reference an existing HPA which will target the canary:

```yaml
spec:
  strategy:
    canary:
      canaryHPA: canary-hpa # will be updated to point to the canary replicaset
```

The rollout controller would update the referenced HPA to always point to the pods of the canary ReplicaSets. This option could be tricky because the Rollout itself could have an HPA, and there could be be infighting between the HPA of the rollout vs. the HPA of the canary ReplicaSet.

**Comment by aweis89** [comment]
> 1. always match the canary scale to the current canary weight. e.g. if the current canary weight is 20%, and the rollout's `spec.replicas: 10`, then the canary scale should be 2.
Isn't this already being done here: https://github.com/argoproj/argo-rollouts/blob/master/utils/replicaset/canary.go#L84

> 2. explicit scale values in steps ([#556 (comment)](https://github.com/argoproj/argo-rollouts/issues/556#issuecomment-679468231)):
> 
> ```yaml
> steps:
> - setWeight: 10
> - setCanaryScale:
>      replicas: 1     # explicit count
> - setCanaryScale:
>      weight: 10     # percentage of spec.replicas
> ```
That sounds perfect!

> 3\. Separate HPA for the canary ([#556 (comment)](https://github.com/argoproj/argo-rollouts/issues/556#issuecomment-679468231)). Here we would reference an existing HPA which will target the canary:
> 
> ```yaml
> spec:
>   strategy:
>     canary:
>       canaryHPA: canary-hpa # will be updated to point to the canary replicaset
> ```
> 
> The rollout controller would update the referenced HPA to always point to the pods of the canary ReplicaSets. This option could be tricky because the Rollout itself could have an HPA, and there could be be infighting between the HPA of the rollout vs. the HPA of the canary ReplicaSet.
Yeah, I could see that getting tricky, especially if the two HPAs have different scaling criteria. I'm wondering if to get around that, it would make sense to also have a `stableHPA` reference as well. Perhaps then the controller could just assign each HPA to their appropriate ReplicaSets so they each target a different group of pods. A setup like that would also prevent the canary pods from having any effect on the stable pods, which could be desirable

**Comment by jessesuen** [comment]
> Isn't this already being done here: https://github.com/argoproj/argo-rollouts/blob/master/utils/replicaset/canary.go#L84

If you look at the implementation of that method, you see:

```golang
	if rollout.Spec.Strategy.Canary.TrafficRouting != nil {
		return desiredNewRSReplicaCount, rolloutSpecReplica
	}
``` 

So when traffic routing is used, we scale canary to 100%.

**Comment by jessesuen** [comment]
> Isn't this already being done here: https://github.com/argoproj/argo-rollouts/blob/master/utils/replicaset/canary.go#L84

I think I might be completely wrong about this. Let me test the behavior.

**Comment by jessesuen** [comment]
I'm closing this, because it was made under the false assumption that we don't already smartly scale the canary stack based on current weight. So the only gap that I see, is the zero-weight use case, mentioned in https://github.com/argoproj/argo-rollouts/issues/556. Will go back to that issue.
