### ISSUE TITLE
Allow separate HPA isolation for canary and stable

### ISSUE THREAD

**Issue by aweis89** [argoproj/argo-rollouts#685]
# Summary

Currently, argo supports creating an HPA with a Rollout target. This proposal would support isolated HPAs that target the canary or stable ReplicaSets directly.

# Use Cases

When using `canary-by-header`, or some other non-proportional traffic routing pattern, the stable ReplicaSet can be under or over-provisioned since the HPA is looking at the average of Pods belonging to both ReplicasSets. If for example, less traffic is going to the canary, due to a header restriction, the stable ReplicaSet is likely to be configured with too few replicas by controller since the HPA and Rollout assume all target Pods will receive equal traffic.

Perhaps to resolve this issue we could add a `stableHPA` and `canaryHPA` which would accept an HPA spec and add the appropriate ReplicasSet to those newly created (by the Rollout controller) HPAs. When `canaryHPA` is supplied, the `setWeight` could just control traffic distribution as apposed to replicas (assuming `trafficRouting` is supplied as well).

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by scoplin** [comment]
@aweis89 Was there a discussion that decided against supporting separate canary/stable HPAs?  Seems like this spawned out of the shuffle of #699 and #556, but I don't see that the unique need expressed here for individual autoscaling was otherwise addressed.
