### ISSUE TITLE
Any plans to garbage collect AnalysisRuns for each Rollout?

### ISSUE THREAD

**Issue by davidxia** [argoproj/argo-rollouts#693]
# Summary

Are there any plans to garbage collect at the AnalysisRun level for each Rollout? Like keep only 10 most recent AnalysisRuns from a single Rollout?

# Use Cases

Garbage collection only happens when number of Jobs created by a single AnalysisRun exceed 10 [via this PR](https://github.com/argoproj/argo-rollouts/pull/258). We are creating a new AnalysisRun each time for a Rollout.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
It was the intent to GC analysisruns tied to the ReplicaSet. If this isn't working, it's a bug.

**Comment by davidxia** [comment]
@jessesuen, thanks. I don't think old AnalysisRuns are being GCed. But I'm not sure because I don't know the GC logic. Are there docs or a link to code or commit of how this should work?

**Comment by jessesuen** [comment]
Here is the code which is supposed to delete AnalysisRuns:

https://github.com/argoproj/argo-rollouts/blob/7689b1f2f1f69c93d212cb1253c3a8ad37251268/utils/analysis/filter.go#L105-L147

So this should be tied to `spec.revisionHistoryLimit`, just as older replicaSets are GC'd. 

I don't see any reason why this wouldn't be working. Have you confirmed that the number of AnalysisRuns does not honor `spec.revisionHistoryLimt`?

**Comment by davidxia** [comment]
Thanks, let me check.

**Comment by davidxia** [comment]
Yup, this is all working as expected. We just had a lot of steps in our AnalysisTemplate which caused a lot of Jobs. Once I looked at the unique number of Pod template hashes in the AnalysisRuns, I noticed there's a max of 10 which corresponds to the Rollout's spec.revisionHistoryLimit of 10.
