### ISSUE TITLE
kubectl argo rollouts lint -f <FILE>

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#695]
# Summary

Now that we have validation libraries, the plugin could leverage the library to allow users to lint the rollout objects via the CLI, in order to catch mistakes before applying or committing to a git repo

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by abatilo** [comment]
I've attempted an implementation for this [here](https://github.com/argoproj/argo-rollouts/pull/783). Please let me know if this is sufficient!

**Comment by russellwhitaker** [comment]
Any progress on this? If implemented, this would be a _major_ developer usability enhancement. I know I could use it right now, myself...
