### ISSUE TITLE
Kustomise and Argo Rollout: The overlay of a rollout manifest is overriding the container configuration instead of merging it.

### ISSUE THREAD

**Issue by qcastel** [argoproj/argo-rollouts#700]
## Summary 

When using kustomise and an overlay, the rollout manifest resulting is not behaving the same way as a deployment.
In particular, the containers section is completely override by the overlay instead of using a merge strategy.

It's probably easier to illustrate this bug. This is why I created a reproduction git repo: https://github.com/qcastel/kustomise-argo-rollout-bug

## Diagnostics

The overlay strategy for the container section is in overriding mode instead of merging mode.

**Comment by jessesuen** [comment]
This is actually a kustomize issue where they lack proper support of CRDs. They can only do a JSON merge patch, instead of the kubernetes style *Strategic* Merge Patch. I'll link to some bugs about this in a little bit.

**Comment by jessesuen** [comment]
Duping to https://github.com/argoproj/argo-rollouts/issues/538 which links to upstream kustomize issue.
