### ISSUE TITLE
docs: I can't see any docs about kubectl plugin commands

### ISSUE THREAD

**Issue by shibataka000** [argoproj/argo-rollouts#707]
## Summary 

I can't see any docs about kubectl plugin commands in https://argoproj.github.io/argo-rollouts/ .

For example, following pages are broken.

- https://argoproj.github.io/argo-rollouts/generated/kubectl-argo-rollouts/kubectl-argo-rollouts.md
- https://argoproj.github.io/argo-rollouts/generated/kubectl-argo-rollouts/kubectl-argo-rollouts_abort.md
- https://argoproj.github.io/argo-rollouts/generated/kubectl-argo-rollouts/kubectl-argo-rollouts_create.md
- etc

And nav bar say `None` , `None` , `None` ...

![image](https://user-images.githubusercontent.com/1219666/92389638-6b6bdf80-f154-11ea-8c8f-54e3a1219e82.png)

I guess these pages are generated by `make plugin-docs` .

## Diagnostics

None

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
Fixed
