### ISSUE TITLE
NewRelic metric provider

### ISSUE THREAD

**Issue by jwelch92** [argoproj/argo-rollouts#736]
# Summary

Expanding the [New Relic](https://newrelic.com/) support to include standard analysis instead of only Mann-Whitney experimentation with Kayenta will cover more use cases. 

# Use Cases

This provides a way to run background analysis and regular canary analysis without dealing with all of the setup and configuration required to run Kayenta. Additionally, this will provide options for analysis for services that are sensitive to replica count changes like Kafka consumers. 

The [newrelic-client-go](https://github.com/newrelic/newrelic-client-go) package provides an easy way to run NRQL queries against NRDB. The existing web metricprovider is not sufficient for working with New Relic's GraphQL API. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jwelch92** [comment]
I am planning on submitting a PR for this in the near future.

**Comment by jessesuen** [comment]
>The newrelic-client-go package provides an easy way to run NRQL queries against NRDB. The existing web metricprovider is not sufficient for working with New Relic's GraphQL API.

Thanks for raising this. You are correct in that a GraphQL interface warrants a new provider
