### ISSUE TITLE
Release manifests with CRD's using apiextensions.k8s.io/v1

### ISSUE THREAD

**Issue by kosukeoya** [argoproj/argo-rollouts#779]
# Summary

The apiextensions.k8s.io/v1beta1 version of CustomResourceDefinition is deprecated and will no longer be served in v1.19. Use apiextensions.k8s.io/v1 instead

https://github.com/kubernetes/kubernetes/blob/release-1.16/CHANGELOG/CHANGELOG-1.16.md#deprecations-and-removals

It would be good to update Argo Rollouts CRD's ([here](https://github.com/argoproj/argo-rollouts/tree/master/manifests/crds)) to use apiextensions.k8s.io/v1. If this is not favorable both versions can be published and everyone uses the one that fits their Kubernetes version.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
We should do this, but we'll need to provide both versions since it will otherwise raise minimum version to v1.15.

**Comment by jessesuen** [comment]
> and will no longer be served in v1.19

FYI, this has been postponed to v1.22, so we have time. See https://github.com/kubernetes/kubernetes/issues/82022

**Comment by artem-nefedov** [comment]
Hello. Please, raise priority for this. v1.22 is already in alpha.

**Comment by jessesuen** [comment]
This has been done in Rollouts v1.0
