### ISSUE TITLE
do not attempt to cache secrets for analysis templates

### ISSUE THREAD

**Issue by yanowitz** [argoproj/argo-rollouts#798]
## Summary 

My colleague (@mrak) and I expect the Argo Rollouts controller to successfully boot. In one our Kubernetes clusters, we have over 600MB of secrets and the Controller is unable to succeed at booting.

Issue #420 is where this functionality was introduced.

Given that we can just query for specific secrets at resolveArgs time, we want to grab these lazily, not cache everything.

We are planning to go do this now, so we can use Argo Rollouts in this cluster. We'll open a PR and reference this bug.

## Diagnostics

What version of Argo Rollouts are you running?

0.9.2.

```
# Paste the logs from the rollout controller

The logs aren't useful -- they just show you never get past "Waiting for controller's informer caches to sync"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
> we have over 600MB of secrets and the Controller is unable to succeed at booting.
> Issue #420 is where this functionality was introduced.

@yanowitz we made the conscious decision to use an informer because we did not want to incur extra load on the K8s API server during reconciliation. With your proposed change, the problem would shift to hammering the API server for AnalysisTemplates which need secrets.

**Comment by yanowitz** [comment]
Is there evidence that this hammering would happen in practice? What's the number of analysis runs occurring in parallel where this would be a problem that reference secrets?

I hesitate to add complexity, but if the caching is a hard-requirement for some folks (it's definitely not for us), then I guess we have to make it an option?

Alternatively, it would also be good to not wedge fetching the secrets but eventually timeout the attempt to cache them and fall back to a synchronous fetch (perhaps logging a warning about the implications if you have a lot of analysis runs that reference secrets).

I will say that the RSS of the process went from 8GB to 256MB once we switched to synchronously fetching secrets.

![image](https://user-images.githubusercontent.com/208486/97022945-6c957800-151a-11eb-8caa-ce971574237d.png)

I'm not trying to be a nay-sayer, but we were hard blocked on taking Argo Rollouts to production until we made this change locally. I'm happy to be part of a solution that meets the competing needs. What are folks' thoughts on the best way to proceed?

**Comment by jessesuen** [comment]
> Is there evidence that this hammering would happen in practice? What's the number of analysis runs occurring in parallel where this would be a problem that reference secrets?

No evidence, but principally, our design approach across all argoproj controllers has been to be able reconcile early and often, without consequence or impact to the system. Being able to make this assumption has freed a lot controller logic with simpler design. Whenever we have to start having to concerning ourselves with reconciliation/logic avoidance, it starts to make the control loop more complex.

That said, I understand why caching all secrets is probably undesirable versus querying the API server frequently.

Recently I've learned of the metadata informer, which allows informers to use less memory by only storing the object metadata of the objects. Essentially it acts like a watch, but with a lightweight cache of object metadata.

https://github.com/kubernetes/client-go/blob/master/metadata/metadatainformer/informer.go
Example usage:
https://github.com/culpinnis/metadata-informer-minimal-example/blob/master/main.go

Since the metadata informer only stores ObjectMeta, this obviously isn't enough since it would not cache the actual secret data. So I feel perhaps the best solution may be the combination of:

1.  the metadata informer to watch all secrets, and detect changes in secrets
2. an informer index on AnalysisRuns which reference Secrets, to identify and filter only Secrets are of relevant to Rollouts
3. a worker on the metadata informer to cache *only the relevant* secrets to an in-memory store, which would subsequently be used during reconciliation

What do you think of that approach?

**Comment by jessesuen** [comment]
BTW, the above technique would be desired and applicable across the board. Rollouts references Secrets, VirtualServices, Ingresses, which obviously not all would be used by a Rollout, and so other parts of the controller would benefit from discarding objects of no relevance to the controller.

**Comment by jessesuen** [comment]
Actually, the solution might be simpler. 

`k8s.io/client-go/tools/cache` allows you to create a custom cache.Config which have a custom Process() function, which we could then implement a function that returns a partial object (i.e Secret). The decision to return a full vs. partial Secret would be determined on whether or not the Secret is referenced by an AnalysisTemplate/Run.

**Comment by yanowitz** [comment]
So we would lazily resolve secrets and only cache referenced ones? I love that.

**Comment by yanowitz** [comment]
Sorry, I've been thinking this more and I'm still confused by the overall approach. It's quite possible I don't understand what's going on, because it seems like we aren't reducing load on the server at all, and are probably increasing it.

Specifically, the initial response:
> we made the conscious decision to use an informer because we did not want to incur extra load on the K8s API server during reconciliation. With your proposed change, the problem would shift to hammering the API server for AnalysisTemplates which need secrets.

1. With our proposed change, the only time AnalysisTemplates cause the apiserver to get hit is when they are being instantiated for an AnalysisRun, and only then if they reference a secret. I don't think this will hammer the server.
2. It seems likely that the set of secrets in a cluster is much larger than the ones that AnalysisTemplates reference so if we are going to cache them we are going to end up using a lot of resources in the argo-rollouts controller for no real win.
3. Anything that gets watched (i.e., using the informer) is inducing a regular load on the apiserver *even if the watched secret is never used* because, under the hood, the informer is using a watcher which is polling the apiserver to see if if what it is watching has 410'd (https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes). 
4. When it has 410'd, we then hit the server to update it again.

In order for using caching to be a win, I believe the creation rate of AnalysisTemplates that reference secrets would have to exceed all the incremental load from all of the watchers. It seems like, in practice, just fetching secrets as needed will always be a win. Even setting up watchers on them after we've fetched them will only be a win if the cost of hitting the watch endpoint regularly (i.e., "watching") is lower than the cost of fetching the secret as needed.

There's no such thing as a free lunch, and I *think* we're actually making this meal more expensive.

BUT, I am not a k8s expert by any means, so I'm probably missing something. 

What do you think?

I do want to raise whether this complexity is worth it -- instantiating AnalysisRuns already have to make requests for configmaps. 

As is, we are putting a bunch of load on argo rollouts to get notified of changes to every secret, regardless of whether that secret is ever referenced in by an AnalysisRun.

**Comment by yanowitz** [comment]
@jessesuen any thoughts?

**Comment by jessesuen** [comment]
@yanowitz I think your logic makes more sense. I think we can switch to looking up secrets on-demand. You mentioned you had a PR ready?

**Comment by yanowitz** [comment]
We'll open one for review next week. I imagine you'll want some changes but it will be a good place to start.

**Comment by mrak** [comment]
PRed as https://github.com/argoproj/argo-rollouts/pull/829

**Comment by jessesuen** [comment]
Fixed in https://github.com/argoproj/argo-rollouts/pull/829
