### ISSUE TITLE
kubectl plugin create should create objects using dynamic client

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#808]
## Summary 

Currently the plugin is tightly coupled with a specific rollout version because it unmarshals files into the typed objects (which might be out-of-date from the version running in the cluster.

For example, if the controller is running a newer version of rollouts, and the plugin is outdated, during a create the plugin will drop all unknown fields which are not known by the plugin.

We should instead use the dynamic client and deal with unstructured objects. This way, an older plugin will still be forwards compatible with newer rollout versions

## Diagnostics

What version of Argo Rollouts are you running?

v0.9.x

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by khhirani** [comment]
@jessesuen Should the plugin use the dynamic client only for object creation, or should the dynamic client replace the RO client entirely?

**Comment by jessesuen** [comment]
> @jessesuen Should the plugin use the dynamic client only for object creation, or should the dynamic client replace the RO client entirely?

It should do it for wherever it could cause problem of dropping fields. For example, the patches that happen in promote, abort, restart do not need to switch, since they have no risk of dropping fields (patches will not drop fields) 

However, creating an analysis run from a template, or local file has risk of dropping unknown fields, as does create.

**Comment by khhirani** [comment]
> However, creating an analysis run from a template, or local file has risk of dropping unknown fields, as does create.

Just to clarify, only creation has the risk of dropping unknown fields?
