### ISSUE TITLE
Pause documentation appears incorrect

### ISSUE THREAD

**Issue by nstogner** [argoproj/argo-rollouts#839]
## Summary 

Pause documentation for canaries [here](https://argoproj.github.io/argo-rollouts/features/specification/) reports that the `pause: {}` step sets the Rollout `.spec.paused` field to `true`:

```yaml
        # Sets .spec.paused to true and waits until the field is changed back
      - pause: {}
```

When running through the example, the `spec.paused` field never gets set:

`kubectl get ro rollouts-demo -ojson | jq '.spec.paused'` returns `null` while `kubectl argo rollouts get ro rollouts-demo` shows the rollout to be paused:

```
Name:            rollouts-demo
Namespace:       default
Status:          ॥ Paused
Strategy:        Canary
  Step:          1/2
  SetWeight:     5
  ActualWeight:  5
Images:          argoproj/rollouts-demo:blue (stable)
                 argoproj/rollouts-demo:yellow (canary)
Replicas:
  Desired:       1
  Current:       2
  Updated:       1
  Ready:         2
  Available:     2

NAME                                       KIND        STATUS     AGE    INFO
⟳ rollouts-demo                            Rollout     ॥ Paused   2m44s  
├──# revision:2                                                          
│  └──⧉ rollouts-demo-789746c88d           ReplicaSet  ✔ Healthy  98s    canary
│     └──□ rollouts-demo-789746c88d-sb7cx  Pod         ✔ Running  98s    ready:1/1
└──# revision:1                                                          
   └──⧉ rollouts-demo-7bf84f9696           ReplicaSet  ✔ Healthy  2m43s  stable
      └──□ rollouts-demo-7bf84f9696-c69z8  Pod         ✔ Running  2m43s  ready:1/1
```

Furthermore, the documentation says it waits for this field to be set back to false to proceed. However, setting `.spec.paused: false` does not trigger a promotion. It looks like clearing `.status.pausedConditions` promotes the rollout instead (which I found by looking through the [plugin promotion code](https://github.com/argoproj/argo-rollouts/blob/v0.9.3/pkg/kubectl-argo-rollouts/cmd/promote/promote.go#L42)).

This is odd, not only because it does not follow documentation, but also because this is counter to common kubernetes controller practices where `.status` fields are typically only used to report on the state of the world, but not to specify the state. `"Remember, status should be able to be reconstituted from the state of the world"` - [Quote from Kubebuilder Book](https://book.kubebuilder.io/cronjob-tutorial/controller-implementation.html?highlight=status#2-list-all-active-jobs-and-update-the-status).

I have only tested this behavior for canaries. I am not sure if this also applies to blue-green.

## Diagnostics

What version of Argo Rollouts are you running? `v0.9.3`

```
# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts
```

```
time="2020-11-12T02:53:16Z" level=info msg="No changes to canary ingress - skipping patch" ingress=rollouts-demo-rollouts-demo-stable-canary namespace=default rollout=rollouts-demo
time="2020-11-12T02:53:16Z" level=info msg="Reconciling StableRS" namespace=default rollout=rollouts-demo
time="2020-11-12T02:53:16Z" level=info msg="Reconciling new ReplicaSet 'rollouts-demo-789746c88d'" namespace=default rollout=rollouts-demo
time="2020-11-12T02:53:16Z" level=info msg="Reconciling old replica sets" namespace=default rollout=rollouts-demo
time="2020-11-12T02:53:16Z" level=info msg="Reconciling canary pause step (stepIndex: 1)" namespace=default rollout=rollouts-demo
time="2020-11-12T02:53:16Z" level=info msg="Not finished reconciling Canary Pause" namespace=default rollout=rollouts-demo
time="2020-11-12T02:53:16Z" level=info msg="No status changes. Skipping patch" namespace=default rollout=rollouts-demo
time="2020-11-12T02:53:16Z" level=info msg="Reconciliation completed" namespace=default rollout=rollouts-demo time_ms=5.9681
time="2020-11-12T02:53:16Z" level=info msg="Started syncing rollout at (2020-11-12 02:53:16.7342076 +0000 UTC m=+26471.943450972)" namespace=default rollout=rollouts-demo
time="2020-11-12T02:53:16Z" level=info msg="Cleaning up old replicasets, experiments, and analysis runs" namespace=default rollout=rollouts-demo
time="2020-11-12T02:53:16Z" level=info msg="Reconciling TrafficRouting with type 'Nginx'" namespace=default rollout=rollouts-demo
time="2020-11-12T02:53:16Z" level=info msg="No changes to canary ingress - skipping patch" ingress=rollouts-demo-rollouts-demo-stable-canary namespace=default rollout=rollouts-demo
time="2020-11-12T02:53:16Z" level=info msg="Reconciling StableRS" namespace=default rollout=rollouts-demo
time="2020-11-12T02:53:16Z" level=info msg="Reconciling new ReplicaSet 'rollouts-demo-789746c88d'" namespace=default rollout=rollouts-demo
time="2020-11-12T02:53:16Z" level=info msg="Reconciling old replica sets" namespace=default rollout=rollouts-demo
time="2020-11-12T02:53:16Z" level=info msg="Reconciling canary pause step (stepIndex: 1)" namespace=default rollout=rollouts-demo
time="2020-11-12T02:53:16Z" level=info msg="Not finished reconciling Canary Pause" namespace=default rollout=rollouts-demo
time="2020-11-12T02:53:16Z" level=info msg="No status changes. Skipping patch" namespace=default rollout=rollouts-demo
time="2020-11-12T02:53:16Z" level=info msg="Reconciliation completed" namespace=default rollout=rollouts-demo time_ms=3.0971
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
Ah yes. This behavior was changed a while back. `spec.paused` is now strictly for user pauses. The controller will no longer touch that field. There is now a `status.pauseConditions` which gets set by controller for pause steps, inconclusive analysis.

**Comment by nstogner** [comment]
Hey Jesse, thanks for the quick response! Is there a reason why `spec.paused` is only reserved for user pauses? Driving resource behavior by changing `.status` is a fairly big anti-pattern in k8s. Instead of changing the docs to match the current behavior, would we consider changing the behavior to match the docs?

**Comment by jessesuen** [comment]
We need a way to discern when a user manually pauses the rollout vs. the controller. For example, the problem we faced is when we were at a time-limited (1-hour) pause step, but the user decides that they then want the rollout to pause indefinitely by manually pausing it. The user is unable to make a change to the rollout to capture the intent to pause indefinitely, since the single field was already set to true by the controller. Thus we need two fields.

> Driving resource behavior by changing .status is a fairly big anti-pattern in k8s

I think there's many examples where I don't think this is true. I feel the status.pauseConditions under status would be akin to minReadySeconds in a Deployment. The controller sets a marker of when a pod became ready, but only considers the pod as **_available_** when it reaches the minReadiness seconds. Similarly, the pause condition of a rollout is a marker of when a rollout was paused, and when the duration elapsed the rollout should not be paused.
