### ISSUE TITLE
Istio VirtualService updates are not being corrected immediately

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-rollouts#849]
## Summary 

When testing istio, I noticed that when I manually adjusted the weights of my VirtualService (out-of-band from rollouts), the argo rollouts controller did not change it back to the current desired weight. The rollout controller has an informer on istio VirtualServices, and it is supposed to immediately correct the weight to what the Rollout controller wants it to be, for the current step.

## Diagnostics

What version of Argo Rollouts are you running? v0.10

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by khhirani** [comment]
@jessesuen Did you notice this on while testing on Minikube?

**Comment by jessesuen** [comment]
No, I noticed when testing on a GKE cluster
