### ISSUE TITLE
Argo Rollouts Operator requires read operations on Secrets

### ISSUE THREAD

**Issue by agrawal93** [argoproj/argo-rollouts#863]
# Summary
**What do you want to know about this project?**
Argo Rollouts Operator throws the error below, if I revoke all access to Secrets in ClusterRoleBinding. I would like to understand why does Argo Rollouts Operator need privileges to read list of secrets at cluster scope.
```
E1119 12:13:09.987199       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:105: Failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:argo-rollouts-stage:argo-rollouts" cannot list resource "secrets" in API group "" at the cluster scope
```

# Motivation
**Why do you need to know this, any examples or use cases you could include?**
As a central Kubernetes management team in an organization, we would like to give restricted access for Secrets, and just wanted to get an idea around what's the use-case which the operator is supporting.

**Comment by alexmt** [comment]
@agrawal93 , secret read is required because secret can be referenced from AnalysysTemplates and AnalysysRun.

**Comment by agrawal93** [comment]
AnalysisTemplate and AnalysisRun are at namespace level, so in that case shouldn't the read for secrets be namespace scoped?
