### ISSUE TITLE
Ability to restart up to maxUnavailable pods at a time for a bluegreen rollout

### ISSUE THREAD

**Issue by jay-lee-otsk** [argoproj/argo-rollouts#866]
# Summary

By #833 a case for Canary rollout was covered, however a **BlueGreen** rollout object also need this feature. 
Note that it is already mentioned in #592 ( I totally cannot understand why it is resolved by #833 )
With this enhancement, any DevOps member could also restart the pod easily from ArgoCD UI. I think it is one of the basic features which this kind of solution should have. 

# Use Cases

As described in the official page regarding Rollout Pod Restarts, the Rollout object should support restarting an application by having the controller do a rolling recreate of all the Pods in a Rollout without going through all the regular **BlueGreen** or Canary deployments. (https://argoproj.github.io/argo-rollouts/features/restart/) 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
Changes necessary are:
1. introduce `maxUnavailable` to `spec.strategy.blueGreen`
2. pod restarter reconciler will honor that value during a restart

NOTE: 
* not sure if we can re-use the canary maxUnavailable calculation but if we cannot, then maxUnavailable should be 20% of available.

**Comment by jessesuen** [comment]
Actually I mispoke. maxUnavailable defaults to 0 so we would restart 1 pod at a time, not 20%.

**Comment by jessesuen** [comment]
> Actually I mispoke. maxUnavailable defaults to 0 so we would restart 1 pod at a time, not 20%.

I mispoke again. Here is the truth looking at k8s source code:

```yaml
// SetDefaults_Deployment sets additional defaults compared to its counterpart
// in extensions. These addons are:
// - MaxUnavailable during rolling update set to 25% (1 in extensions)
// - MaxSurge value during rolling update set to 25% (1 in extensions)
// - RevisionHistoryLimit set to 10 (not set in extensions)
// - ProgressDeadlineSeconds set to 600s (not set in extensions)
func SetDefaults_Deployment(obj *appsv1.Deployment) {
	// Set DeploymentSpec.Replicas to 1 if it is not set.
	if obj.Spec.Replicas == nil {
		obj.Spec.Replicas = new(int32)
		*obj.Spec.Replicas = 1
	}
	strategy := &obj.Spec.Strategy
	// Set default DeploymentStrategyType as RollingUpdate.
	if strategy.Type == "" {
		strategy.Type = appsv1.RollingUpdateDeploymentStrategyType
	}
	if strategy.Type == appsv1.RollingUpdateDeploymentStrategyType {
		if strategy.RollingUpdate == nil {
			rollingUpdate := appsv1.RollingUpdateDeployment{}
			strategy.RollingUpdate = &rollingUpdate
		}
		if strategy.RollingUpdate.MaxUnavailable == nil {
			// Set default MaxUnavailable as 25% by default.
			maxUnavailable := intstr.FromString("25%")
			strategy.RollingUpdate.MaxUnavailable = &maxUnavailable
		}
		if strategy.RollingUpdate.MaxSurge == nil {
			// Set default MaxSurge as 25% by default.
			maxSurge := intstr.FromString("25%")
			strategy.RollingUpdate.MaxSurge = &maxSurge
		}
	}
```

We are not defaulting to 25% when restarting pods using the canary strategy so that's a bug that needs to be fixed.
