### ISSUE TITLE
Rollout Controller did not creating new pod

### ISSUE THREAD

**Issue by zionwu** [argoproj/argo-rollouts#869]
## Summary 
In our production env, our apps are deployed using Rollout with readiness probe configured. One day, Due to the issue of a middleware,  some of our apps became NotReady.  After the middleware recovered, we need to restart those apps so we deleted the pods of apps. After the pods are deleted, the new pods are not created by the rollout controller.  We tried to create a new rollout object, but its pods are not created either.  It seems the rollout controller is not working at all.

We restarted the rollouts controller and it started to work and created new pods.

## Diagnostics

What version of Argo Rollouts are you running?
v0.7.2

During the issue, the rollout controller took a long time (10 mins) to resync a rollout:
```
# log of kubectl logs -n argo-rollouts argo-rollouts-xxxx | grep project-8957 |grep "Started syncing"
time="2020-11-26T08:53:21Z" level=info msg="Started syncing rollout at (2020-11-26 08:53:21.187832086 +0000 UTC m=+11650151.516033885)" namespace=project-8957 rollout=csif-prd-2806
time="2020-11-26T09:04:21Z" level=info msg="Started syncing rollout at (2020-11-26 09:04:21.987807212 +0000 UTC m=+11650812.316009013)" namespace=project-8957 rollout=csif-prd-2806
time="2020-11-26T09:16:27Z" level=info msg="Started syncing rollout at (2020-11-26 09:16:27.887785044 +0000 UTC m=+11651538.215986840)" namespace=project-8957 rollout=csif-pre-2514
time="2020-11-26T09:23:45Z" level=info msg="Started syncing rollout at (2020-11-26 09:23:45.487833688 +0000 UTC m=+11651975.816035487)" namespace=project-8957 rollout=csif-prd-2806

```

When the controller is working normally, it takes only a few seconds to resync a rollout:
```
# log of kubectl logs -n argo-rollouts argo-rollouts-xxxx | grep project-8957 |grep "Started syncing"
time="2020-11-26T08:25:12Z" level=info msg="Started syncing rollout at (2020-11-26 08:25:12.087803101 +0000 UTC m=+11648462.416004901)" namespace=project-8957 rollout=csif-prd-2806
time="2020-11-26T08:25:14Z" level=info msg="Started syncing rollout at (2020-11-26 08:25:14.98776001 +0000 UTC m=+11648465.315961806)" namespace=project-8957 rollout=csif-prd-2806
time="2020-11-26T08:25:17Z" level=info msg="Started syncing rollout at (2020-11-26 08:25:17.787747747 +0000 UTC m=+11648468.115949542)" namespace=project-8957 rollout=csif-prd-2806
time="2020-11-26T08:25:21Z" level=info msg="Started syncing rollout at (2020-11-26 08:25:21.487787973 +0000 UTC m=+11648471.815989769)" namespace=project-8957 rollout=csif-prd-2806
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
> After the pods are deleted, the new pods are not created by the rollout controller. We tried to create a new rollout object, but its pods are not created either. It seems the rollout controller is not working at all.

Rollouts does not manage pods, it manages ReplicaSets. When pods are deleted, it's the responsibility of the ReplicaSet to recreate it.

> We tried to create a new rollout object, but its pods are not created either.

Could you grep the logs for a single `rollout=XXXXX`. The "Started syncing" messages are not enough.

**Comment by jessesuen** [comment]
> What version of Argo Rollouts are you running?
> v0.7.2

Also, this version is quite old. It's unlikely we'll be able to backport a potential fix to this release

**Comment by jessesuen** [comment]
The rollout should have a condition explaining the problem. Usually because one of the resources the rollout depends on is not valid or misconfigured (e.g. an istio virtual service). The plugin will display this (as will Argo CD when clicking on the resource). But as of now, theres just not enough information to go off of to do anything.
