### ISSUE TITLE
Rewrite Pod Topology Spread Constraints label selectors

### ISSUE THREAD

**Issue by jstewart612** [argoproj/argo-rollouts#970]
# Summary

Rewrite Pod Topology Spread Constraints label selectors if they use a label Argo Rollouts would normally modify on a rollout.

# Use Cases

Any time I wanted to use a Pod Topology Spread Constraint on a Deployment in a Rollout.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
@jstewart612 I dont quite understand the feature request here. Could you add some more details about the use case and how rollouts would address it?

**Comment by jstewart612** [comment]
*looks up*

*sees Argo Rollouts*

That's not Argo CD....

Oops!
