### ISSUE TITLE
Add Ephemeral Metadata for Blue Green strategy

### ISSUE THREAD

**Issue by cooperbenson-qz** [argoproj/argo-rollouts#973]
# Summary

Functionality for setting ephemeral metadata for Canary rollouts was proposed in #455 and implemented in #770. I would like to extend this functionality to the BlueGreen strategy as well. This would be done by adding `previewMetadata` and `activeMetadata` to the BlueGreen spec and using similar reconciliation logic to apply them to the replicasets and pods.

# Use Cases

Same use cases as ephemeral metadata for canary rollouts (i.e. tagging metrics with consistent labels). My specific use case is to tag Prometheus metrics with a label if the pod is active and use that for selecting custom HPA metrics.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by cooperbenson-qz** [comment]
I'm planning on authoring a PR for this if there are no objections to the proposed implementation 😄

**Comment by jessesuen** [comment]
@cooperbenson-qz this sounds great to have parity for blue-green. No objections to the proposal or you working on this. I'll assign the issue to you. Thanks!
