### ISSUE TITLE
Pull Requests still use CLA assistant, which is no longer required with DCO

### ISSUE THREAD

**Issue by benchi** [argoproj/argo-rollouts#980]
## Summary 

What happened/what you expected to happen?

I opened a PR and signed commits with DCO.
In the build, it was detected that I had not signed CLA.
<img width="840" alt="Screen Shot 2021-02-05 at 12 47 59 PM" src="https://user-images.githubusercontent.com/960184/107087547-716ff600-67b0-11eb-8013-bf6f211a1492.png">

## Diagnostics

What version of Argo Rollouts are you running?
n/a
```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment]
Fixed in https://github.com/argoproj/argo-rollouts/pull/979
